### ISSUE TITLE
[BUG] Duplicate processor_id not allowed in Pay::Customer

### ISSUE THREAD

**Issue by shettytejas** [pay-rails/pay#1010]
**Describe the Bug**:

In a multi-tenant application (with acts_as_tenant) where each Account can have multiple Users, users with the same email can exist across different accounts but not within the same account. During the billing process, when trying to initialize a customer for a user with the same email address that already exists as a customer in a different account, the system fails to create a new customer record. This issue persists even after attempting to tenant the customer table due to existing validation constraints.

**To Reproduce**:

- Create an account (Account A) and add a user with email example@example.com.
- Initialize a customer for this user under Account A.
- Create a different account (Account B) and add another user with the same email example@example.com.
- Attempt to initialize a customer for this user under Account B.

**Expected Behavior**:

The system should allow the initialization of a customer for the user under Account B, independent of the existing customer record for the same email under Account A.

**Actual Behavior**:

The system fails to initialize a customer for the user under Account B due to a validation constraint that prevents multiple customer records for the same email across different accounts.

Screenshots (if applicable):

![image](https://github.com/pay-rails/pay/assets/74608924/c8b045c1-d804-4cd9-977b-b6ddd320b41d)

**Environment**:

Pay gem version: 7.2.1
Ruby version: 3.3.3
Rails version: 7.1.3.4
Operating System: Windows + WSL2

**Possible Fix**:

Line number 14 [here](https://github.com/pay-rails/pay/blob/main/app/models/pay/customer.rb) can be either modified or be made optional.

**Labels to Apply**:

bug

Checklist:

- [x] I have searched for similar issues and couldn't find any.
- [x] I have checked the documentation for relevant information.
- [x] I have included all the required information.

**Comment by shettytejas** [comment]
@deanpcmad While I agree that Paddle doesn't allow to create multiple customers, my aim to point this out is a use case where the user objects have same email but in different tenant context. The paddle customer they'll be pointing to would be the same (or different Pay::Customer objects, but with same customer_id).

**Comment by deanpcmad** [comment]
Maybe the best way around that might be to have a separate model in your app just for Pay, and your Users/Accounts (whatever model you use), would link with that for billing?

**Comment by excid3** [comment]
You can set up your application to handle this as needed outside of Pay.
