### ISSUE TITLE
Stripe Webhook Issue

### ISSUE THREAD

**Issue by dtakeshta** [pay-rails/pay#1017]
I understand this is not an issue with the library, but I was hoping to create the issue to get some guidance.  

I have connect accounts and customers.  Connect accounts onboard through the account link, and customers will add a credit card through checkout `current_user.payment_processor.checkout(currency: 'usd', mode: 'setup')` that will later be charged and money will be sent to the connected account.  

When you create a webhook, you must select what you want to listen for as shown below.

![Screenshot 2024-07-03 at 9 09 21 AM](https://github.com/pay-rails/pay/assets/7004584/1655c69b-e08a-4816-b711-b9d72bb0b49b)

When I select `Events on Connected accounts`, the webhooks for `checkout.session.completed` work.

However, `payment_method.attached` will not work.  I can see the event recorded in in the events tab, but there is no webhook.

<img width="785" alt="Screenshot 2024-07-03 at 9 16 29 AM" src="https://github.com/pay-rails/pay/assets/7004584/830a696f-f147-4d0b-bef2-64952511e918">

<img width="1137" alt="Screenshot 2024-07-03 at 9 18 44 AM" src="https://github.com/pay-rails/pay/assets/7004584/0cdf1949-8517-4151-871d-a2b9ee991969">

If I create a second webhook, but this time choose `Events on your account`, then go through checkout to add the credit card, the webhook fires.  It fails of course because I don't have the right `STRIPE_SIGNING_SECRET`.  

<img width="575" alt="Screenshot 2024-07-03 at 9 20 33 AM" src="https://github.com/pay-rails/pay/assets/7004584/dda8f130-2832-421a-bde2-4c63c2a4f241">

So, from what I can tell, it's like I need both webhooks but that becomes problematic due to the `STRIPE_SIGNING_SECRET`.  I'm not exactly sure how I can receive both `checkout.session.completed` and `payment_method.attached`.   Oddly enough, all of this works when testing locally using stripe cli.  The webhooks for connect and account work with no issues.

I have also tried using the billing portal, but again, no webhook is fired but I can see the event. 

I'm really hoping I'm missing something here.  Any information would be greatly appreciated!

**Comment by excid3** [comment]
You can set multiple secrets in your Rails credentials and it will use each one until it finds a match.

https://github.com/pay-rails/pay/blob/main/app/controllers/pay/webhooks/stripe_controller.rb#L29-L31
