### ISSUE TITLE
[BUG] undefined methods when upgrading to v8

### ISSUE THREAD

**Issue by luizkowalski** [pay-rails/pay#1069]
## Bug Report

**Describe the Bug:**
After upgrading to v8, I'm seeing a couple of `NoMethodError`s for `cancel_now!` and `paused?`

**To Reproduce:**
I have a class like this

```ruby
class User
  def subscription
    payment_processor.subscription(name: Subscription::NAME)
  end
end
...
user.subscription.cancel_now!
```
inspecting `user.subscription.public_methods` indeed does not include `cancel_now!`.

and `paused?` also seems to be missing, triggered by `user.subscription.active?`

**Screenshots (if applicable):**

**Environment:**
- Pay gem version: 8.0
- Ruby version: 3.3.5
- Rails version: main
- Operating System: macOS Sonoma

**Additional Context:**
I checked the upgrade guide and ran the migration but it didn't do anything regarding this error

- [X] I have searched for similar issues and couldn't find any
- [X] I have checked the documentation for relevant information
- [X] I have included all the required information

**Comment by excid3** [comment]
What payment processor? Please provide a full example to reproduce.

**Comment by luizkowalski** [comment]
I'm using Stripe. I will try to create a reproducible example and get back to you

**Comment by luizkowalski** [comment]
ah, nevermind, I got ahead of myself here. 

it was happening only in test environment, and I tracked it down to a misconfigured fixture (forgot to add `type` to it)

smooth update now, thanks!
