### ISSUE TITLE
[BUG] Paddle Billing `cancel_now!` reports error.

### ISSUE THREAD

**Issue by codadrop** [pay-rails/pay#1097]
## Bug Report

**Describe the Bug:**
Calling this code:
``` ruby
    subscription = current_user.payment_processor.subscriptions.find_by(name: 'default')
    subscription.cancel_now! if subscription&.active?
```

Returns this error `ArgumentError (wrong number of arguments (given 1, expected 0)):`

**Expected Behavior:**
`cancel_now` should cancel the user's subscription

**Environment:**
- Pay gem version: 8.1.3
- Ruby version: 3.1.2
- Rails version: 7.04
- Operating System: MacOS

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Please provide a stacktrace.

**Comment by codadrop** [comment]
I'll remember the stack trace next time! Thank you!

[pay (8.1.3) app/models/pay/paddle_billing/subscription.rb:86:in `cancel' ](https://elegant-truly-muskox.ngrok-free.app/#)
[pay (8.1.3) app/models/pay/paddle_billing/subscription.rb:102:in `cancel_now!' ](https://elegant-truly-muskox.ngrok-free.app/#)
[app/controllers/users/registrations_controller.rb:5:in `destroy' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/base.rb:215:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/rendering.rb:165:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/callbacks.rb:234:in `block in process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks' ](https://elegant-truly-muskox.ngrok-free.app/#)
[turbo-rails (2.0.6) lib/turbo-rails.rb:24:in `with_request_id' ](https://elegant-truly-muskox.ngrok-free.app/#)
[turbo-rails (2.0.6) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actiontext (7.0.8.4) lib/action_text/rendering.rb:20:in `with_renderer' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actiontext (7.0.8.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `instance_exec' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:138:in `run_callbacks' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/callbacks.rb:233:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/rescue.rb:23:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `block in instrument' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `instrument' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activerecord (7.0.8.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/base.rb:151:in `process' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionview (7.0.8.4) lib/action_view/rendering.rb:39:in `process' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal.rb:188:in `dispatch' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal.rb:251:in `dispatch' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:32:in `serve' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/mapper.rb:48:in `serve' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:50:in `block in serve' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:32:in `each' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:32:in `serve' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:852:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch' ](https://elegant-truly-muskox.ngrok-free.app/#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/etag.rb:27:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/conditional_get.rb:40:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/head.rb:12:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/cookies.rb:704:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activerecord (7.0.8.4) lib/active_record/migration.rb:638:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:99:in `run_callbacks' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/executor.rb:14:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app' ](https://elegant-truly-muskox.ngrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:19:in `block in call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch' ](https://elegant-truly-muskox.ngrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[railties (7.0.8.4) lib/rails/rack/logger.rb:40:in `call_app' ](https://elegant-truly-muskox.ngrok-free.app/#)
[railties (7.0.8.4) lib/rails/rack/logger.rb:25:in `block in call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:99:in `block in tagged' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:37:in `tagged' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:99:in `tagged' ](https://elegant-truly-muskox.ngrok-free.app/#)
[railties (7.0.8.4) lib/rails/rack/logger.rb:25:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/request_id.rb:26:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/method_override.rb:24:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/runtime.rb:22:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/executor.rb:14:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/static.rb:23:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[rack (2.2.9) lib/rack/sendfile.rb:110:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/host_authorization.rb:138:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[railties (7.0.8.4) lib/rails/engine.rb:530:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[puma (5.6.8) lib/puma/configuration.rb:252:in `call' ](https://elegant-truly-muskox.ngrok-free.app/#)
[puma (5.6.8) lib/puma/request.rb:77:in `block in handle_request' ](https://elegant-truly-muskox.ngrok-free.app/#)
[puma (5.6.8) lib/puma/thread_pool.rb:340:in `with_force_shutdown' ](https://elegant-truly-muskox.ngrok-free.app/#)
[puma (5.6.8) lib/puma/request.rb:76:in `handle_request' ](https://elegant-truly-muskox.ngrok-free.app/#)
[puma (5.6.8) lib/puma/server.rb:443:in `process_client' ](https://elegant-truly-muskox.ngrok-free.app/#)
puma (5.6.8) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

**Comment by codadrop** [comment]
Thank you! I'll remember the stacktrace next time!

[Application Trace](https://a-atatatatagrok-free.app/#) | [Framework Trace](https://a-atatatatagrok-free.app/#) | [Full Trace](https://a-atatatatagrok-free.app/#)
[pay (8.1.3) app/models/pay/paddle_billing/subscription.rb:86:in `cancel' ](https://a-atatatatagrok-free.app/#)
[pay (8.1.3) app/models/pay/paddle_billing/subscription.rb:102:in `cancel_now!' ](https://a-atatatatagrok-free.app/#)
[app/controllers/users/registrations_controller.rb:5:in `destroy' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/base.rb:215:in `process_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/rendering.rb:165:in `process_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/callbacks.rb:234:in `block in process_action' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:118:in `block in run_callbacks' ](https://a-atatatatagrok-free.app/#)
[turbo-rails (2.0.6) lib/turbo-rails.rb:24:in `with_request_id' ](https://a-atatatatagrok-free.app/#)
[turbo-rails (2.0.6) app/controllers/concerns/turbo/request_id_tracking.rb:10:in `turbo_tracking_request_id' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks' ](https://a-atatatatagrok-free.app/#)
[actiontext (7.0.8.4) lib/action_text/rendering.rb:20:in `with_renderer' ](https://a-atatatatagrok-free.app/#)
[actiontext (7.0.8.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `instance_exec' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:138:in `run_callbacks' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/callbacks.rb:233:in `process_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/rescue.rb:23:in `process_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `block in instrument' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `instrument' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action' ](https://a-atatatatagrok-free.app/#)
[activerecord (7.0.8.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/abstract_controller/base.rb:151:in `process' ](https://a-atatatatagrok-free.app/#)
[actionview (7.0.8.4) lib/action_view/rendering.rb:39:in `process' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal.rb:188:in `dispatch' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_controller/metal.rb:251:in `dispatch' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:32:in `serve' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/mapper.rb:48:in `serve' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:50:in `block in serve' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:32:in `each' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:32:in `serve' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:852:in `call' ](https://a-atatatatagrok-free.app/#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call' ](https://a-atatatatagrok-free.app/#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch' ](https://a-atatatatagrok-free.app/#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/etag.rb:27:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/conditional_get.rb:40:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/head.rb:12:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/cookies.rb:704:in `call' ](https://a-atatatatagrok-free.app/#)
[activerecord (7.0.8.4) lib/active_record/migration.rb:638:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/callbacks.rb:99:in `run_callbacks' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/executor.rb:14:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call' ](https://a-atatatatagrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app' ](https://a-atatatatagrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:19:in `block in call' ](https://a-atatatatagrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch' ](https://a-atatatatagrok-free.app/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call' ](https://a-atatatatagrok-free.app/#)
[railties (7.0.8.4) lib/rails/rack/logger.rb:40:in `call_app' ](https://a-atatatatagrok-free.app/#)
[railties (7.0.8.4) lib/rails/rack/logger.rb:25:in `block in call' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:99:in `block in tagged' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:37:in `tagged' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:99:in `tagged' ](https://a-atatatatagrok-free.app/#)
[railties (7.0.8.4) lib/rails/rack/logger.rb:25:in `call' ](https://a-atatatatagrok-free.app/#)
[sprockets-rails (3.5.2) lib/sprockets/rails/quiet_assets.rb:17:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/request_id.rb:26:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/method_override.rb:24:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/runtime.rb:22:in `call' ](https://a-atatatatagrok-free.app/#)
[activesupport (7.0.8.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/server_timing.rb:60:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/executor.rb:14:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/static.rb:23:in `call' ](https://a-atatatatagrok-free.app/#)
[rack (2.2.9) lib/rack/sendfile.rb:110:in `call' ](https://a-atatatatagrok-free.app/#)
[actionpack (7.0.8.4) lib/action_dispatch/middleware/host_authorization.rb:138:in `call' ](https://a-atatatatagrok-free.app/#)
[railties (7.0.8.4) lib/rails/engine.rb:530:in `call' ](https://a-atatatatagrok-free.app/#)
[puma (5.6.8) lib/puma/configuration.rb:252:in `call' ](https://a-atatatatagrok-free.app/#)
[puma (5.6.8) lib/puma/request.rb:77:in `block in handle_request' ](https://a-atatatatagrok-free.app/#)
[puma (5.6.8) lib/puma/thread_pool.rb:340:in `with_force_shutdown' ](https://a-atatatatagrok-free.app/#)
[puma (5.6.8) lib/puma/request.rb:76:in `handle_request' ](https://a-atatatatagrok-free.app/#)
[puma (5.6.8) lib/puma/server.rb:443:in `process_client' ](https://a-atatatatagrok-free.app/#)
puma (5.6.8) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

**Comment by excid3** [comment]
Try that fix I just pushed to `main` branch. 👍

**Comment by codadrop** [comment]
Works wonderfully. Thank you!

**Comment by excid3** [comment]
Awesome, thanks for catching that!
