### ISSUE TITLE
[BUG] Unable to migrate to v8

### ISSUE THREAD

**Issue by doutatsu** [pay-rails/pay#1105]
## Bug Report

**Describe the Bug:**
I am following the upgrade instructions and 

**To Reproduce:**

1. Upgrade to version 8 from 7
2. Run `rails pay:install:migrations`
3. Run `rails db:migrate`

**Expected Behavior:**
Migrations run without errors and I can continue using the gem without interruption to my customers

**Actual Behavior:**
Migrations fail due to the tables already existing:

```
== 20241109074101 CreatePayTables: migrating ==================================
-- create_table(:pay_customers, {:id=>:primary_key})
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::DuplicateTable: ERROR:  relation "pay_customers" already exists
/Users/doutatsu/Documents/projects/kenmei-api/db/migrate/20241109074101_create_pay_tables.pay.rb:6:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "pay_customers" already exists (ActiveRecord::StatementInvalid)
/Users/doutatsu/Documents/projects/kenmei-api/db/migrate/20241109074101_create_pay_tables.pay.rb:6:in `change'

Caused by:
PG::DuplicateTable: ERROR:  relation "pay_customers" already exists (PG::DuplicateTable)
/Users/doutatsu/Documents/projects/kenmei-api/db/migrate/20241109074101_create_pay_tables.pay.rb:6:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Screenshots (if applicable):**

**Environment:**
- Pay gem version: 8.1.3
- Ruby version: 3.3.4
- Rails version: 7.1
- Operating System: MacOS 14.3.1

**Additional Context:**

**Possible Fix:**
Documentation and potentially migration task needs to be updated. It's been awhile, but I assume that the task simply creates everything from scratch, for people that start using the pay gem for the first time. If that's the case, documentation needs to indicate which migration is not needed and should be deleted and which one should remain. Otherwise I have to manually double check which tables should remain and which shouldn't before manually fixing the migrations

**Steps to Reproduce with Fix (if available):**

**Related Issues:**

**Labels to Apply:**

**Checklist:**

- [ ] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Earlier versions of Pay weren't using models & migrations from the gem. You'll just want to make sure you delete the duplicate migration.

**Comment by doutatsu** [comment]
@excid3 I think the documentation is still very confusing - anyone coming in to migrate from 7 to 8, following instructions as is, would face this issue... Which duplicate is duplicate for example, I presume is the first one? Considering how high risk doing anything with payments are, for live systems, I am sure I am not the only that worries everytime I have to upgrade to a new version and touch existing data structures
