### ISSUE TITLE
[BUG] Pay Subscriptions name field not set with paddle billing

### ISSUE THREAD

**Issue by codadrop** [pay-rails/pay#1106]
## Bug Report

**Describe the Bug:**
Entries are `default` for the name field in the `pay_scubscriptions` table when using Paddle Billing with named subscriptions.

**Expected Behavior:**
Name field entries in the `pay_scubscriptions` table should reflect the name of the Paddle Billing subscription.

**Environment:**
- Pay gem version: `main` branch
- Ruby version: 3.1.2
- Rails version: 7.0.4
- Operating System: MacOS 13.4

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
The name attribute is for differentiating subscriptions in the application and does not sync the name from the payment processor.

**Comment by codadrop** [comment]
Thank you for the clarification and quick reply!
