### ISSUE TITLE
[BUG] if a subscription canceled, use on_trial? returns true

### ISSUE THREAD

**Issue by cnsnet** [pay-rails/pay#1115]
## Bug Report

**Describe the Bug:**
I am using Stripe to create a subscription. if I set this subscription as canceled, use `payment_processor.subscription.on_trial?` will return a `true` value. but it should be return a `false`

I am using `payment_processor.subscription.active? && payment_processor&.subscription&.on_trial?` to determine it's on trial status.

**To Reproduce:**
1. create a subscription.
2. use `cancel_now!` to cancel this subscription
3. use `payment_processor.subscription.on_trial?` to see wether this subscription is on_trial or not.

**Expected Behavior:**
get a `false`

**Actual Behavior:**
get a `true`

**Screenshots (if applicable):**

**Environment:**
- Pay gem version: `gem 'pay', '~> 8'`
- Stripe version: `gem 'stripe', '~> 13'`
- Ruby version: `3.3.4`
- Rails version: `gem 'rails', '7.2.2'`
- Operating System: `Windows WSL version 2`

**Additional Context:**

**Possible Fix:**

**Steps to Reproduce with Fix (if available):**

**Related Issues:**

**Labels to Apply:**

**Checklist:**

- [ ] I have searched for similar issues and couldn't find any
- [ ] I have checked the documentation for relevant information
- [ ] I have included all the required information

**Comment by excid3** [comment]
Do you have webhooks enabled? This should be handled by those.

We do our best to keep things accurate in case webhooks aren't enabled, so we can probably update `trial_ends_at: Time.current` to `cancel_now!`, but webhooks will always be required to be completely up-to-date with what's in Stripe.

**Comment by cnsnet** [comment]
@excid3 Thank you, I am going to check this.
