### ISSUE TITLE
[BUG]  TypeError no implicit conversion of Symbol into Integer in Pay::Webhook.rehydrated_event

### ISSUE THREAD

**Issue by Olli** [pay-rails/pay#1119]
## Bug Report

**Describe the Bug:**
TypeError no implicit conversion of Symbol into Integer
This happens in the Stripe API on Stripe::Event.construct_from when the Queued Webhook Job is processed. 
It's because on the event attribute is only a string instead of a JSON Object (which Stripe::Event.construct_from expects)

**To Reproduce:**
1. Set up a webhook for Stripe in rails like suggested in the docs
2. stripe trigger payment_intent.succeeded 

**Expected Behavior:**
It should be processed without any error

**Actual Behavior:**
```
TypeError (no implicit conversion of Symbol into Integer):
.rvm/rubies/ruby-3.3.6/lib/ruby/gems/3.3.0/gems/stripe-13.2.0/lib/stripe/stripe_object.rb:94:in `[]'
.rvm/rubies/ruby-3.3.6/lib/ruby/gems/3.3.0/gems/stripe-13.2.0/lib/stripe/stripe_object.rb:94:in `construct_from'
.rvm/rubies/ruby-3.3.6/lib/ruby/gems/3.3.0/gems/pay-8.2.1/app/models/pay/webhook.rb:27:in `rehydrated_event'
```
**Environment:**
- Pay gem version: 8.2.1
- Ruby version: 3.3.6
- Rails version: 7.2.2.1
- Operating System: Linux

**Possible Fix:**
::Stripe::Event.construct_from(JSON.parse(event, symbolize_names: true)) works but 

**Steps to Reproduce with Fix (if available):**
1. Set up a webhook for Stripe in rails like suggested in the docs
2. stripe trigger payment_intent.succeeded 

With the fix the Job is processed correctly 

**Labels to Apply:**
bug

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Your `event` column in the database should be `json` or `jsonb` and ActiveRecord will return a Hash for these.

If it is `text`, you'll need to convert it to a json column format.

**Comment by Olli** [comment]
I've used the migration files provided by Pay. Because I just came to the same conclusion that has something to do with the I've deleted the Pay Tables and run the actual migrations again just to make sure everything is correct.
The problem is the same.
I think I should add that I'm using MariaDB (11.4.3)

**Comment by excid3** [comment]
Maria DB is not supported. It does not implement real `json` columns. They are just text columns that are validated as json.

See #429
