### ISSUE TITLE
Migration with same name has already exists

### ISSUE THREAD

**Issue by BrandonKlotz** [pay-rails/pay#115]
Will occur if you've started creating payment gateways in your app manually and then decided to use the pay gem.

Running the pay migrations generated 3 changes instead of 4. 
- I stopped there to resolve the differences between my already existing table and the pay table.
`NOTE: Migration 20170727235816_create_charges.rb from pay has been skipped. Migration with the same name already exists.`

💭 Potential solution
- Should the pay table migrations name be scoped to `CreatePayCharges`?
- Or a note in the docs

**Comment by excid3** [comment]
The migration already creates a pay_charges table, so I think the migrations just need renaming to include "pay" in them so they don't conflict. 👍

**Comment by BrandonKlotz** [comment]
Cool, that's what I did to resolve.

**Comment by excid3** [comment]
In general, I wouldn't expect you to use this gem if you already had some payments implemented. That said, I would love to port the GoRails and Hatchbox payments code over to it, so I'll probably be doing something similar. Might as well fix it while I'm at it.

**Comment by excid3** [comment]
And done!
