### ISSUE TITLE
Is it possible to have multiple billable_class and billable_table?

### ISSUE THREAD

**Issue by nicastelo** [pay-rails/pay#117]
First of all, I want to thank you, this gem saves me a lot of work. It's great you shared this.

The reason why I'm asking is because of some product requirements I have, I need to make Teams and Users both billable. Is this possible? How would you recommend me doing it?

Thanks!

**Comment by excid3** [comment]
Sure! You just would need to duplicate the billable migration so each model has the associated fields and include the `Billable` module in both models. Should be as simple as that.
