### ISSUE TITLE
Best approach to handling 3DS with subscriptions

### ISSUE THREAD

**Issue by lukeredpath** [pay-rails/pay#127]
Firstly I just want to say thanks for this excellent library, it has saved a lot of time setting up a Subscription system for a client project I'm working on. I was even able to successfully implement my own pseudo-payment provider to handle a custom voucher-based payment system.

I'm still trying to iron out some niggles in the Javascript on the subscribe page, using Stripe. I currently have the basic happy path with a successful transaction but I'm unsure of the best approach to handling 3DS.

Current Javascript code loads the Stripe elements into the form then on submit, calls `createPaymentMethod` and submits the payment method ID, plan ID and user's name/email to the server where it does something like this:

```ruby
user.processor = 'stripe'
user.card_token = params[:payment_method_id]
user.subscribe(plan: params[:plan_id])
``

And responds with:

```ruby
stripe_subscription = user.subscription&.processor_subscription(expand: ['latest_invoice'])
render json: stripe_subscription.json
```

Javascript checks the returned JSON subscription object, specifically the status of the payment intent on the latest invoice. If it isn't `requires_action` or `requires_payment_method` it treats it as successful and the process is complete.

If the JSON returned from the server indicates that that it requires a payment method or requires action, we use the client secret from the payment intent and call `stripe.confirmCardPayment()` which starts the 3DS verification process.

Where I'm not entirely certain is how to handle 3DS if it is successfully submitted. The Stripe docs seem to indicate that we should be making a request to our own server to "confirm the subscription". I know if that 3DS process is successful then the invoice/payment/subscription will be completed and Stripe will send webhooks that the app will receive and update the local `Subscription` model but there can be a delay between getting the 3DS successful callback on the client and the server receiving the webhook. 

My current approach is to exclusively rely on the webhook to complete the process on the server and have the client poll the server (to an endpoint which returns the Stripe subscription as JSON and the local `Subscription#status` value) until it is updated. This seems a bit wrong to me, is there a better way of doing this?

Should my "check_subscription" end point be explicitly calling some Pay Rails API to force it to check the server status and update itself without waiting for the webhook to arrive?

**Comment by lukeredpath** [comment]
A bit of a follow-on from this - I'm also wondering if there were plans to add support for re-attempting payments with new card details when the initial payment fails. Stripe suggests the following workflow when the initial charge for a subscription fails:

1. Prompt the user to enter new card details again
2. Concert new card to a payment token and submit to the server
3. Attach the new payment method to the existing customer and set it as their default payment method.
4. Make a call to the /pay endpoint for the latest invoice ID.

Pay seems to have some API for updating card details which sets the new card as the default which could handle step 3 of the above but there's no built-in way to make it re-attempt payment on the outstanding invoice. 

I can manually handle this fairly easily with this code:

```ruby
user.update_stripe_card(payment_method)
latest_invoice_id = user.subscription.processor_subscription.latest_invoice
Stripe::Invoice.pay(latest_invoice_id)
```

However the `Subscription` will not be updated until a web hook is received or I manually fetch the Stripe subscription (although there's no built-in way to synchronise the `Subscription` model with Stripe other than waiting for the webhook).

I've currently got something like this to work around this but was wondering if this was something that you'd consider including?

```ruby
def sync_with_processor
    Pay::Stripe::Webhooks::SubscriptionUpdated.new.call(processor_subscription_update_event)
  end

  private

  # Wrappers for the Stripe Subscription that can be passed to the webhook object
  UpdateEvent = Struct.new(:data)
  UpdateEventData = Struct.new(:object)

  def processor_subscription_update_event
    UpdateEvent.new(UpdateEventData.new(processor_subscription))
  end
```

**Comment by excid3** [comment]
The way we handle SCA subscriptions in this gem is we capture the payment method, attach it to the user, then try to create the subscription. If it's successful, you'll have a Subscription that's active.

If it requires SCA, then you'll get a subscription that has an `incomplete` status. The subscription will have a latest_invoice with a `payment_intent_id` on it that you can send back to the browser to have Stripe JS run against that.

We have some example JS here: 
https://github.com/pay-rails/pay/wiki/Stripe-Elements-v3-SCA-Compatible

The gem includes an SCA page that handles this step too. It's used for two situations: 
* Failed subscription payments. We'll email the user that a payment failed and they are taken to the payment page to confirm SCA or add a new card
* Subscription create that requires SCA. I setup my controller to just redirect to the payment page with the `latest_invoice.payment_intent_id`
