### ISSUE TITLE
Apple pay

### ISSUE THREAD

**Issue by eugenedm** [pay-rails/pay#132]
Hi guys, I'm not 100% sure it has it, but I don't think apple pay works within Pay.
I just used apple pay the first time in my life and I loved it... So fast and easy on iphones.
Is it hard to implement Pay with Apple Pay?

**Comment by excid3** [comment]
Shouldn't be. Pay is just the backend code, so all you would need to do is add the Stripe Javascript for handling Apple Pay.

**Comment by eugenedm** [comment]
Wow. OK. So I guess I have more questions... I'd love a few lines of such a code. I'll look around 
Thank you!

**Comment by eugenedm** [comment]
I found  this guide: 
https://stripe.com/docs/stripe-js/elements/payment-request-button
