### ISSUE TITLE
If a card  is expiring soon, how does webhook catch it?

### ISSUE THREAD

**Issue by eugenedm** [pay-rails/pay#134]
If a card  is expiring soon, does webhook catch it?
If so, how does that work? I've been re-reading the docs and I can't figure out what will happen say if when the card expires...
Does Stripe send a message to my https://wga.com/hook
And it changes the database to "cancelled".. or How does that work?
Also I know I can check this by a method. I think it connects to Stripe and it seems kinda slow and I don't want to make it too long when they log in...
How do you recommend to go about it without worsening customer experience...

**Comment by excid3** [comment]
If a card expires and Stripe tries to charge their subscription, it will send invoice failed webhooks. Stripe allows 3-4 failed charges before a subscription is canceled.

I normally use a service like JustDunning, Profitwell Retain, or Baremetrics to handle those for me, but that's something we'll probably add to this at some point.

We use the stripe_event gem to catch webhooks. You can add your own listeners to that webhook if you would like to handle that yourself in the app. Right now, we've only got webhook listeners to sync card, charge, and subscription changes to our db. This may be a feature we will add in the future.
