### ISSUE TITLE
Model Generator Uses inccorrect constant name 

### ISSUE THREAD

**Issue by charleystran** [pay-rails/pay#135]
The model generator currently generates a model file with a name like this:
db/migrate/20200404010351_add_pay_billable_to_users.rb

However the internal class constant is generated as 
AddPayToUsers
which leads to an error of
NameError: uninitialized constant AddPayBillableToUsers

PR for fix is https://github.com/pay-rails/pay/pull/136

**Comment by excid3** [comment]
Doh, thanks @charleystran 🙏
