### ISSUE TITLE
Split payments on the roadmap?

### ISSUE THREAD

**Issue by asecondwill** [pay-rails/pay#137]
Will it be possible to take split payments using pay in the future? So a user can have an account with us, charge their sub-users and we (the platform) take a cut?

**Comment by excid3** [comment]
Definitely something we'd like to add! I just need to figure out what changes we'll need to make that happen. I'm not sure if we'll add new methods or just add other options to the existing stuff. Have to do a deep dive on it to figure that out.

**Comment by archonic** [comment]
👍 for Stripe Connect support!

**Comment by kieranklaassen** [comment]
https://github.com/pay-rails/pay/issues/189 would support a fee to go to another account. Same with Stripe marketplaces
