### ISSUE TITLE
Add support for proration date

### ISSUE THREAD

**Issue by lukeredpath** [pay-rails/pay#138]
I'm working on a plan change feature for a client so would be willing to open a PR for this, I just wanted to check you're happy with my proposed implementation.

When changing say from a monthly to a quarterly billing plan, Stripe will prorate any unused time on the current plan when generating the next invoice. Stripe allows you to generate a preview invoice before you swap the user's plan allowing you to build a UI that shows you exactly what the customer will be charged (or refunded) before they proceed with the plan swap:

```ruby
subscription = user.subscription.processor_subscription

items = [{
    id: subscription.items.data[0].id,
    plan: 'new_plan_id', # Switch to new plan
}]

proration_date = Time.current.to_i

invoice = Stripe::Invoice.upcoming({
    customer: 'cust_id',
    subscription: 'sub_id',
    subscription_items: items,
    subscription_proration_date: proration_date,
})
```

Taken from: https://stripe.com/docs/billing/subscriptions/prorations#previewing-proration

As Stripe calculates to the second its possible for the preview invoice to differ from the final invoice when you perform the plan swap unless you explicitly pass in a proration date. By passing in the same proration date you used when generating the preview invoice when updating the subscription. you can sure that it results in the same proration value

```ruby
Stripe::Subscription.update(
  'sub_id',
  {
    items: [
      {
        id: subscription.items.data[0].id,
        plan: 'new_plan_id,
      },
    ],
    proration_date: proration_date,
  }
)
```

To support this, it would be good if the existing `Subscription#swap` method supported this.

I suggest two possible APIs:

1. Set proration date independently before performing the swap:

```ruby
class Subscription
  attribute :proration_date, :time, default: -> { Time.current }
end

subscription = Subscription.find(x)
subscription.proration_date = 1.day.from_now
subscription.swap('new_plan_id')
```

2. Parameter to swap:

```ruby
subscription = Subscription.find(x)
subscription.swap('new_plan_id', proration_date: Time.current)
```

I feel like the second API is a bit nicer but it would also mean adding a parameter to the `processor_swap()` methods for each payment gateway adapter, whereas making it an attribute means no change to the existing public API or internal API, the gateway adapter would just need to be updated to set the proration_date before saving.

**Comment by excid3** [comment]
I think we want to keep `swap` as the method that actually does the swap.

Stripe has the `upcoming` method on Invoice, so we would probably want to mimic that and add a `upcoming` method on Subscription.

I would imagine we'd want the interface like this:

```ruby
subscription = Subscription.find(id)
subscription.upcoming
# or with options
subscription.upcoming(plan: 'new_plan_id', proration_date: 10.days.from_now)
```

**Comment by excid3** [comment]
Also yes, I think we will want to add an options hash as an additional argument to `swap()` so you can pass in other options like proration_date.

**Comment by lukeredpath** [comment]
Thanks for the feedback - unfortunately I'll have to leave this one in your hands for now if you feel it's a priority as after talking to my client we decided to not use prorations and are now using subscription schedules to schedule the plan change at the end of the current billing cycle.
