### ISSUE TITLE
Maybe a bug at /subscriptions can't write unknown attribute `owner_type`

### ISSUE THREAD

**Issue by eugenedm** [pay-rails/pay#139]
Hey guys,
I'm having a weird error when I run current_user.subscribe... I've checked my code... and I can't find a clue anywhere...
Everything was working perfectly until a few days ago... And now I can't get subscriptions to work... 

Funny enough stripe processes the payment and it shows up under subsriptions in Stripe's dash... But my app breaks and I get this... and it WON'T save the payment to db...

This might be a bug...
---
I get this error: 

ActiveModel::MissingAttributeError at /subscriptions
can't write unknown attribute `owner_type`

in subscriptions_controller.rb
---
Code: 
newplan='plan_GyF4Qxxxxxx'
 current_user.processor = 'stripe'
 current_user.card_token = 'pm_card_visa'
 current_user.subscribe(plan: newplan)    <<<<error here

----
Rails version: 6.0.2.2
Ruby: 2.6.1p33

**Comment by excid3** [comment]
Sounds like you probably upgraded to Pay v2.1 but didn't add the migration to add the `owner_type` column to subscriptions and charges.

https://github.com/pay-rails/pay/blob/master/CHANGELOG.md#210

**Comment by eugenedm** [comment]
Ohhhh!!!! 🤯🤯🤯
Got it!
Thanks!
