### ISSUE TITLE
AddFieldsToBillable  migration is not reversable in some cases

### ISSUE THREAD

**Issue by skatkov** [pay-rails/pay#142]
## Steps
1. Start integrating pay to new project, that doesn't have users table 
2. Run `bin/rails pay:install:migrations`
3. Run `rake db:migrate`
4. Try to reverse this change by running `rake db:rollback STEP=4`

## Result
User table is still in database, but only with a single column called "id".

## Expected result
I would expect that database migration should be reversible. 

The severity of this issue is certainly not critical ;-)
But I got quite annoyed by this while working in multiple branches.

Code in question seems to be here:
https://github.com/pay-rails/pay/blob/b9d613b0ec4253dbb9a0047ab5144d79508009d2/db/migrate/20170503131610_add_fields_to_billable.rb#L3-L5

We can probably drop table if `Pay.billable_table` has only one column with name "id"?

**Comment by excid3** [comment]
This migration doesn't need to exist anymore now that we have the `rails g pay User` generator to add billable fields to multiple models. I removed this migration and released the new version so that shouldn't cause issues anymore.
