### ISSUE TITLE
undefined method `amount' for #<Stripe::SetupIntent:0x00007fac54abf718>

### ISSUE THREAD

**Issue by stevesizer** [pay-rails/pay#144]
I tested the sign up process for a subscription using a card that required SCA action and upon redirect I got this error...

Can anyone help?

**Comment by excid3** [comment]
This is one of the complexities of Stripe SCA. If you're charging the card immediately, you have to use a PaymentIntent, not a SetupIntent. 

SetupIntents are used for collecting a card (without an amount) either for a trial, or for updating their card on file.

PaymentIntents are created automatically by Pay if you use the `charge` or `subscribe` methods. 

You'll need to check if the user is subscribing to a plan with a trial to choose the right branch to go down. I wish it was simpler, but we can probably handle this somewhat inside Pay in the future if we add a plan model into the gem.

**Comment by stevesizer** [comment]
The subscription had a trial so I think that was causing the issue. 

Thanks,
Stephen

**Comment by excid3** [comment]
Cool, let me know. In that case it should automatically inherit the plan's trial. We do that here: https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/billable.rb#L58

**Comment by excid3** [comment]
If you're still having issues, send some more details like what code you're running and the stacktrace of the error. 👍

**Comment by henrydjacob** [comment]
I am facing the same issue "undefined method `amount' for #<Stripe::SetupIntent" where my plan has "trail", any solution on how to handle this?
