### ISSUE TITLE
Creating a dashboard/admin view or subscribers

### ISSUE THREAD

**Issue by dankmitchell** [pay-rails/pay#146]
What's the best way to build a dashboard of active, unsubscribed, failed, incomplete subscribers?

Should I be using my user model or join to the associated subscription?

I have migrated over to this gem which is great but need to update my admin dashboard.

**Comment by excid3** [comment]
I would just query the Pay::Subscription table to find what you want. You can join the owner association to get whatever the related model is since it's a polymorphic relationship.

**Comment by dankmitchell** [comment]
Perfect!
