### ISSUE TITLE
Best practice to expand webhooks

### ISSUE THREAD

**Issue by dankmitchell** [pay-rails/pay#154]
I'm looking to add users to a MailChimp list when they have subscribed. 

It makes sense to tie this [charge succeeded](https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/webhooks.rb#L8) but I don't want to override the current `Pay::Stripe::Webhooks::ChargeSucceeded`. I guess I could copy and paste that class into my repo but that's not maintainable.

**Comment by excid3** [comment]
Need to confirm this, but you can just add your own subscriber to the stripe event like we do. I'm pretty sure it will run both our listener and your listener. 

https://github.com/integrallis/stripe_event
