### ISSUE TITLE
Dummy app and Documentation Mismatch?

### ISSUE THREAD

**Issue by asecondwill** [pay-rails/pay#163]
In the README, it says

> To sync over customer names, your Billable model should respond to the first_name and last_name methods. Pay will sync these over to your Customer objects in Stripe and Braintree.

But here in the Team model in the dummy, it has an email method but not first_name or last_name. Is the dummy up to date?

https://github.com/pay-rails/pay/blob/fd7e6de39d3078a02aab08670918b0642b7b3da8/test/dummy/app/models/team.rb#L6

**Comment by excid3** [comment]
Name isn't required on Stripe, so Teams don't have them and it shows that it works without. 👍

**Comment by asecondwill** [comment]
Cool, thanks.  I have set it up locally and it gave a nice error saying add the email method to the Account model.   : )

**Comment by excid3** [comment]
Hmm, can you paste me that and the stacktrace?

**Comment by asecondwill** [comment]
I don't think you need to reopen the ticket for this, it is correctly saying add the email method for the account model, and doing that fixes it.  Sorry for the confusion.  The only (tiny) improvement I can see here is to add it to the docs, on line 81 of the Readme perhaps.  But really, its pretty obvious what to do because the error message (attached) is clear.  



<img width="1128" alt="Screenshot 2020-06-08 at 11 18 13" src="https://user-images.githubusercontent.com/156546/84019835-c0dbf900-a979-11ea-9563-214a31d1d8fc.png">

**Comment by excid3** [comment]
I just updated the readme to mention that `email` is a required attribute. 👍
