### ISSUE TITLE
Account.subscription returns Nil if Subscription name is not 'Default'

### ISSUE THREAD

**Issue by asecondwill** [pay-rails/pay#166]
I think i've misunderstood something here, 

I have a subscription page working, that creates a subscription with the name "Tiny"

` @account.subscribe(plan: @account.plan, name: "Tiny")`

The @account.plan comes from the form, and according to the error messages I got, had to be set to the pricing id, price_1234QWERT456.

When I test to see if the account has an active subscription, I get what seems like the wrong answer:

```
 <% if @account.subscription.try(:active?) %>
      You Are Subscribed to the <b><%= @account.subscription.name %></b> Plan.
    <% else  %>
      <%= link_to "Subscription", new_admin_subscription_path %>
    <% end %>
```

Looking at the logs, @account.subscription looks for only subscriptions with the name "Default".

If i plan to have say 3 different plans possible, Tiny, Medium, Large.  How should I store that? 

I think this means that the plan Name is not a subscription level. It is to subscribe to different things.

**Comment by excid3** [comment]
Yeah, the `name` is like a product name. That way a user could have multiple subscriptions at once.

If it's the same product, but 3 different plans, you'd just leave the name empty (or the same) and change the plan.

**Comment by asecondwill** [comment]
Ok, thanks for clarifying that.
