### ISSUE TITLE
Undefined method `trial_ends_at?`

### ISSUE THREAD

**Issue by archonic** [pay-rails/pay#169]
I'm getting `NoMethodError: undefined method 'trial_ends_at?' for #<User:0x0000561697e0ba88>` when calling `current_user.on_trial?` as described under usage in the readme.

The culprit appears to be here: https://github.com/pay-rails/pay/blob/master/lib/pay/billable.rb#L75

I believe `trial_ends_at?` should be `trial_ends_at` or `trial_ends_at.present?`.

**Comment by excid3** [comment]
Your billable model should have a `trial_ends_at` column on it. Is that missing?

**Comment by archonic** [comment]
So the `users` table needs a `trial_ends_at` column? That wasn't generated by the pay migrations. There's a `trial_ends_at` column on the `pay_subscriptions` table. I guess both columns are needed for subscriptions and generic subscriptions?

**Comment by excid3** [comment]
Yeah, I was going to say the migration _should_ be adding that field. I can't remember if we added it later though, so maybe it was missed somewhere along the way.
