### ISSUE TITLE
No signature found and invoice settings problems

### ISSUE THREAD

**Issue by marcoroganovic** [pay-rails/pay#172]
First of all, thanks for such a wonderful gem. I'm integrating it for our SaaS project, and few things are not clear to me, or rather maybe could not figure out it from the docs.

I have started to test webhook integration with ngrok, and I'm getting this error when payload comes to the webhook endpoint.

```No signatures found matching the expected signature for payload```

As I can see on Google, people usually read the raw request body to validate properly.

The second problem is when I try to call the subscribe method, it says:

```NoMethodError (undefined method `invoice_settings' for #<Stripe::Customer:0x00007fdf103c0a90>):```

Subscriptions worked in the beginning (I could see them inside of Stripe dashboard properly) but now this exception happens.

Did anyone encounter similar issues?

**Comment by excid3** [comment]
Webhooks require you to have configured the signing secret in Pay to match the signing secret for the webhook on Stripe. That error is saying your webhook signature doesn't match that secret. I'd double check to make sure you have the correct signing secret configured.

**Comment by marcoroganovic** [comment]
Thanks!

Actually it was my mistake, you are correct. It was my mistake.

Any info maybe on invoice_settings method?

**Comment by excid3** [comment]
It could be that `invoice_settings` is missing because of an API version.

What version are you on?

**Comment by marcoroganovic** [comment]
```gem 'pay', '~> 2.0'```

**Comment by excid3** [comment]
Sorry, wasn't clear. :)

Stripe API versions are important. Look it up in your Stripe dashboard and paste the version number here for me. 👍

**Comment by marcoroganovic** [comment]
This one is used so far 2019-12-03

**Comment by excid3** [comment]
It looks like they may have moved the `invoice_settings` nested under a `default_settings` in November. https://stripe.com/docs/upgrades#2019-11-05

I'm not sure my API version is that up-to-date yet. Could be the issue.

**Comment by marcoroganovic** [comment]
Ok, thank you very much @excid3

**Comment by excid3** [comment]
I guess that we'll need to figure out somehow which API version you're on in order to make that work consistently in Pay. Strange.

**Comment by marcoroganovic** [comment]
Please @excid3 tell me how I can help, as far as versions go, here is the list:
```
gem 'pay', '~> 2.0'
gem 'stripe', '< 6.0', '>= 2.8'
gem 'stripe_event', '~> 2.3'
gem 'receipts', '~> 1.0.0'
```

**Comment by excid3** [comment]
We'll have to probably modify the gem to reference the default_settings (without breaking the older versions).

**Comment by marcoroganovic** [comment]
May I ask also here, what config I need to have in order to send transactional emails?

Because I've made my setup for ActionMailer with Mailgun, and emails like verify the account, reset the password, etc, are delivered, but the ones that should be sent by this gem, are not.

Also, I need to list to the user all transactions with receipts on the front-end, do you recommend creating a special controller for it or there is a way to expose some endpoint from gem?

**Comment by excid3** [comment]
Yep, just configure actionmailer. Your webhooks must be enabled for it to send anything.

I typically just create a charges_controller to render the list and show receipts / invoices.

**Comment by marcoroganovic** [comment]
But as I said, for some reason transactional emails are not delivered, nor send. I have configured webhooks, and ```pay_charges``` table gets populated correctly, but mails are not sent. I'll try to debug somehow, thank you very much for help.

**Comment by excid3** [comment]
Make sure you're running your background jobs. The emails are sent with ActiveJob.

**Comment by GeorgeRDBuckley** [comment]
> It looks like they may have moved the `invoice_settings` nested under a `default_settings` in November. https://stripe.com/docs/upgrades#2019-11-05
> 
> I'm not sure my API version is that up-to-date yet. Could be the issue.

@excid3 @marcoroganovic 

This change appears to be on `subscription schedules` which doesn't appear to be used inside Pay, `invoice_settings` is still an attribute on the customer object. I have tried to recreate this issue, but they only way I could get this to error `undefined method `invoice_settings' for #<Stripe::Customer:...` was by deleting the customer and then attempting to call `.invoice_settings` on that customer.

Steps taken to attempt to reproduce:

```
customer = Stripe::Customer.create({})

customer.invoice_settings
=> #<Stripe::StripeObject:0x1180> JSON: {
  "custom_fields": null,
  "default_payment_method": null,
  "footer": null
}

customer.delete
=> #<Stripe::Customer:0x1194 id=cus_HeRwSpfiWAnqNf> JSON: {
  "id": "cus_HeRwSpfiWAnqNf",
  "object": "customer",
  "deleted": true
}

 customer.invoice_settings
=> NoMethodError (undefined method `invoice_settings' for #<Stripe::Customer:0x00007fbefeb73ad0>.  HINT: The 'invoice_settings' attribute was set in the past, however.  It was then wiped when refreshing the object with the result returned by Stripe's API, probably as a result of a save().  The attributes currently available on this object are: id, object, deleted)
```

This is using the most recent API version. Do we have any other reproducible steps?
