### ISSUE TITLE
How to properly pass a quantity option to subscribe?

### ISSUE THREAD

**Issue by justalever** [pay-rails/pay#173]
I've been trying to append some options to a subscription and get this error.

```
Received both items and quantity parameters. Please pass in only one.
```

[Per the docs](https://github.com/pay-rails/pay#creating-a-subscription), you can pass options to the subscribe method along with the plan object:

```ruby
def subscribe(name: 'default', plan: 'default', **options)
  ...
end

```

Is quantity not supported? 

I'm trying to do something like the following:

```ruby
options = {
  quantity: @plan.quantity
}

current_account.subscribe(plan: processor_id, trial_period_days: @plan.trial_period_days, **options)
```

A new quantity column exists on the `Plan` model. I'm striving for the $x/user/mo approach as the end goal.

**Comment by excid3** [comment]
I forget what causes that situation but someone else had it too. I'd make sure you're on the latest version.

We've got a test for quantities: https://github.com/pay-rails/pay/blob/master/test/pay/billable/stripe_test.rb#L209

**Comment by justalever** [comment]
Ah, nice. I'll double-check my version (I hadn't). Appreciate the speedy response 🙌

**Comment by justalever** [comment]
So, I had no luck with version bumps.

I did notice the `POST` body on stripe _might_ be skewed a bit.

So with something like this

```ruby
  current_account.subscribe(plan: processor_id, trial_period_days: @plan.trial_period_days, quantity: @plan.quantity)
```
results in this on Stripe's end. 

```json
{
  "expand": {
    "0": "pending_setup_intent",
    "1": "latest_invoice.payment_intent"
  },
  "items": {
    "0": {
      "plan": "xxxxxxxxxxxxxxx",
      "shouldn't quantity go here?"
    }
  },
  "off_session": "true",
  "trial_period_days": "0",
  "quantity": "10"
}
```

Which looks right but I think quantity isn't set per item but rather as a whole. I may be off though!

**Comment by excid3** [comment]
What's your Stripe API version?

**Comment by justalever** [comment]
![](https://i.imgur.com/A45F3Uq.png)

**Comment by excid3** [comment]
If you run that test with your API key, does it pass or fail?

**Comment by justalever** [comment]
It passes so that's interesting. I'll tinker around more and see what might be the issue on my end. At the moment I'm a bit stumped.

**Comment by justalever** [comment]
```ruby
current_team.subscribe(name: 'business', plan: processor_id, trial_period_days: @plan.trial_period_days)
```

The above works fine

```ruby
current_team.subscribe(name: 'business', plan: processor_id, trial_period_days: @plan.trial_period_days, quantity: @plan.quantity)
```

This code above fails. For some reason, quantity is passed outside of the `items` object for me when it hits Stripe. I haven't been able to pinpoint why. The end goal is to charge a team an annual plan based on seat quantity. 


The POST request:

```json
{
  "expand": {
    "0": "pending_setup_intent",
    "1": "latest_invoice.payment_intent"
  },
  "items": {
    "0": {
      "plan": "price_1Gz9nXBtajRjwpdHahsCIsFx"
    }
  },
  "off_session": "true",
  "trial_period_days": "0",
  "quantity": "10" 
}
```

The response

```json
{
  "error": {
    "message": "Received both items and quantity parameters. Please pass in only one.",
    "type": "invalid_request_error"
  }
}
```


For context this is my `create` action on my `subscriptions_controller.rb` file. It borrows heavily from your work on Jumpstart minus my junky additions lol. I'm still using the `Team`concept at the moment.

```ruby
class SubscriptionsController < ApplicationController
...
 def create
    current_team.assign_attributes(subscription_params)
    @plan = Plan.without_free.find(current_team.plan) # Get the Stripe or Braintree specific ID
    @plan.quantity = params[:team][:quantity].to_i
    processor_id = @plan.processor_id(current_team.processor)
    current_team.subscribe(plan: processor_id, trial_period_days: @plan.trial_period_days)
    redirect_to root_path, notice: "Thanks for subscribing!"
  rescue Pay::ActionRequired => e
    redirect_to pay.payment_path(e.payment.id)
  rescue Pay::Error => e
    flash[:alert] = e.message
    render :new
  end

...

private

  def subscription_params
    params.require(:team).permit(:card_token, :plan, :processor, :quantity, :extra_billing_info)
  end

end
```

Over on Stripe they now call "plans" => "prices". It's quite confusing!

If you don't have the time to review no biggie. I appreciate your attention thus far!

**Comment by excid3** [comment]
Yeah, the whole Price change is annoying, but it supports one-time payments which is cool. I guess that'll be something we're going to have to support.

As for that quantity error, maybe I never released that quantity change to rubygems? The literal first line of code in the method is deleting the quantity option so it goes in items, so what you're seeing still seems to make me think you're on a somewhat earlier version somewhere...

**Comment by justalever** [comment]
Ok cool. I'll keep chugging along and report back if I figure things out 👍. I'm hoping you're right about a version. That would make for an easier fix 🤞

**Comment by excid3** [comment]
What's the version in your Gemfile.lock? I also don't remember when I tested the quantity stuff and if I published it to Rubygems. Can also try using it directly from git.

**Comment by justalever** [comment]
I'm showing. I'll try the git approach 👍

```ruby
pay (2.1.2)
```

```ruby
 stripe (5.22.0)
    stripe_event (2.3.1)
      activesupport (>= 3.1)
      stripe (>= 2.8, < 6)
```


```ruby
DEPENDENCIES
   pay (~> 2.1, >= 2.1.2)
  ...
  stripe (>= 2.8, < 6.0)
  stripe_event (~> 2.3, >= 2.3.1)

**Comment by excid3** [comment]
It seeeems like I maybe just never cut it as a release.

**Comment by justalever** [comment]
Chris... 

![](https://media.giphy.com/media/ToMjGpKniGqRNLGBrhu/giphy.gif)

**Comment by justalever** [comment]
YEP!! Pulling from the master branch in the Gemfile did the trick. 🎉

**Comment by excid3** [comment]
Fantastic! 😎

Guess I better cut a new release with `quantity` support.

**Comment by excid3** [comment]
Released a new version. Also confirmed that Stripe works when passing in `price_` as `plan` during subscribe.

**Comment by justalever** [comment]
Thanks man!
