### ISSUE TITLE
Inconsistent assignment of subscription `processor_plan`

### ISSUE THREAD

**Issue by archonic** [pay-rails/pay#174]
I noticed some odd behaviour when writing request tests that call `swap` on the user subscription.

After setting up my subscribed user which is testing against live Stripe,`user.subscription(name: "example").processor_plan` is a JSON blob:

```
{
  "id": "price_1GvnFzFpMcvkWhcFuMrM9m9c",
  "object": "plan",
  "active": true,
  "aggregate_usage": null,
  "amount": 900,
  "amount_decimal": "900",
  "billing_scheme": "per_unit",
  "created": 1592584799,
  "currency": "usd",
  "interval": "month",
  "interval_count": 1,
  "livemode": false,
  "metadata": {
  },
  "nickname": null,
  "product": "prod_HU72MDZXgDBkYM",
  "tiers": null,
  "tiers_mode": null,
  "transform_usage": null,
  "trial_period_days": 14,
  "usage_type": "licensed"
}
```

After calling `user.subscription(name: "example").swap("pm_xxx")`, the `processor_plan` attribute is just the ID string (`price_1GvnFFFpMcvkWhcFleWYnqs5`).

As far as I can tell, it looks like the intention was for `processor_plan` to just be the ID string. If that's true, it looks like this is the culprit:
https://github.com/pay-rails/pay/blob/master/lib/pay/billable.rb#L135

Happy to submit a PR, just wanted to ask what the intention was for that attribute first.

**Comment by archonic** [comment]
This was happening because I was passing in the whole Stripe::Plan object instead of just the ID. My mistake, but perhaps there should be an argument error if `plan` is not a `String`?

**Comment by excid3** [comment]
I think that'd be a great PR. ;P
