### ISSUE TITLE
AddStatusToPaySubscriptions Migration Failing

### ISSUE THREAD

**Issue by redlightmikey** [pay-rails/pay#176]
When running rake db:migrate on setup, I am getting the following error:

```
== 20200627205203 AddStatusToPaySubscriptions: migrating ======================
-- add_column(:pay_subscriptions, :status, :string)
   -> 0.0033s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `type' for :boolean:Symbol
```

Prior to running DB:migrate I ran:

`rails g pay User`

Not sure what else, I can do at this point, I am running rails 4.2.10...

**Comment by excid3** [comment]
Hmm, I don't think we have any booleans in our migrations. See if you can get a stacktrace to show where that stems from.

**Comment by redlightmikey** [comment]
```
-- add_column(:pay_subscriptions, :status, :string)
   -> 0.0033s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `type' for :boolean:Symbol
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_methods/time_zone_conversion.rb:64:in `create_time_zone_conversion_attribute?'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_methods/time_zone_conversion.rb:53:in `block (2 levels) in inherited'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:61:in `block in matching'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:60:in `select'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:60:in `matching'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:56:in `decorators_for'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:47:in `apply'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:29:in `block in add_user_provided_columns'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:28:in `map'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:28:in `add_user_provided_columns'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attributes.rb:93:in `columns'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attributes.rb:98:in `columns_hash'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:109:in `block in sanitize_sql_hash_for_assignment'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:108:in `each'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:108:in `map'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:108:in `sanitize_sql_hash_for_assignment'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:40:in `sanitize_sql_for_assignment'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/relation.rb:332:in `update_all'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/querying.rb:8:in `update_all'
/Users/mikeyc/Workspace/road_project/db/migrate/20200627205203_add_status_to_pay_subscriptions.pay.rb:9:in `up'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:571:in `up'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:611:in `exec_migration'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:591:in `block in migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:590:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:768:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1069:in `ddl_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:984:in `block in migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `each'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
NoMethodError: undefined method `type' for :boolean:Symbol
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_methods/time_zone_conversion.rb:64:in `create_time_zone_conversion_attribute?'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_methods/time_zone_conversion.rb:53:in `block (2 levels) in inherited'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:61:in `block in matching'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:60:in `select'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:60:in `matching'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:56:in `decorators_for'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:47:in `apply'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:29:in `block in add_user_provided_columns'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:28:in `map'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attribute_decorators.rb:28:in `add_user_provided_columns'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attributes.rb:93:in `columns'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/attributes.rb:98:in `columns_hash'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:109:in `block in sanitize_sql_hash_for_assignment'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:108:in `each'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:108:in `map'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:108:in `sanitize_sql_hash_for_assignment'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/sanitization.rb:40:in `sanitize_sql_for_assignment'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/relation.rb:332:in `update_all'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/querying.rb:8:in `update_all'
/Users/mikeyc/Workspace/road_project/db/migrate/20200627205203_add_status_to_pay_subscriptions.pay.rb:9:in `up'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:571:in `up'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:611:in `exec_migration'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:591:in `block in migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:590:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:768:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1069:in `ddl_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:984:in `block in migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `each'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/mikeyc/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
Michaels-Air:road_project mikeyc$ 

```

**Comment by excid3** [comment]
Since it's coming from `time_zone_conversion`, looks like it's got something to do with `:boolean` being treated as a time.

As you can see in the migration, there's nothing related to booleans or times:
https://github.com/pay-rails/pay/blob/master/db/migrate/20190816015720_add_status_to_pay_subscriptions.rb

Must be something you've got going on with your model. Doesn't seem like it has to do with Pay from what I can tell.

**Comment by redlightmikey** [comment]
> Since it's coming from `time_zone_conversion`, looks like it's got something to do with `:boolean` being treated as a time.
> 
> As you can see in the migration, there's nothing related to booleans or times:
> https://github.com/pay-rails/pay/blob/master/db/migrate/20190816015720_add_status_to_pay_subscriptions.rb
> 
> Must be something you've got going on with your model. Doesn't seem like it has to do with Pay from what I can tell.

Hmmm, how does that migration interact with my model? I thought it wasn't until migration 4 does it touch the model? 

I'm not sure of my next step..

I also tried again not against my User model by my AssociationProfile Model:

```
class AssociationProfile < ActiveRecord::Base
  include Pay::Billable
```

**Comment by excid3** [comment]
The migration just adds the string column, as you can see in the link I sent. You've got something else going on.

Try sharing your db/schema.rb

**Comment by redlightmikey** [comment]
ActiveRecord::Schema.define(version: 20200627205202) do

  create_table "association_profiles", force: :cascade do |t|
    t.string   "first_name"
    t.string   "last_name"
    t.string   "phone_number"
    t.integer  "user_id"
    t.datetime "created_at",            null: false
    t.datetime "updated_at",            null: false
  end

  create_table "association_profiles_instructor_associations", id: false, force: :cascade do |t|
    t.integer "instructor_association_id", null: false
    t.integer "association_profile_id",    null: false
  end

  create_table "packages", force: :cascade do |t|
    t.string   "name"
    t.string   "description"
    t.string   "package_type"
    t.integer  "price_in_pence"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pay_charges", force: :cascade do |t|
    t.integer  "owner_id"
    t.string   "owner_type"
    t.string   "processor",       null: false
    t.string   "processor_id",    null: false
    t.integer  "amount",          null: false
    t.integer  "amount_refunded"
    t.string   "card_type"
    t.string   "card_last4"
    t.string   "card_exp_month"
    t.string   "card_exp_year"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pay_subscriptions", force: :cascade do |t|
    t.integer  "owner_id"
    t.string   "name",                       null: false
    t.string   "processor",                  null: false
    t.string   "processor_id",               null: false
    t.string   "processor_plan",             null: false
    t.integer  "quantity",       default: 1, null: false
    t.datetime "trial_ends_at"
    t.datetime "ends_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "payment_links", force: :cascade do |t|
    t.integer  "instructor_profile_id"
    t.integer  "student_profile_id"
    t.string   "payment_token"
    t.datetime "payment_timestamp"
    t.integer  "requested_amount_in_pence"
    t.text     "reason"
    t.datetime "created_at",                                                null: false
    t.datetime "updated_at",                                                null: false
    t.boolean  "status",                                    default: false
    t.datetime "date_paid"
    t.string   "stripe_payment_id"
    t.string   "confirmation_sent_to_email"
    t.boolean  "has_instructor_been_paid",                  default: false
    t.boolean  "has_student_confirmed_lesson_is_delivered", default: false
    t.string   "confirmation_request_token"
    t.datetime "lesson_date_and_time"
    t.datetime "instructor_marked_lesson_delivered_at"
  end
 
  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: ""
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.string   "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.string   "unconfirmed_email"
    t.integer  "failed_attempts",        default: 0
    t.string   "unlock_token"
    t.datetime "locked_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "invitation_token"
    t.datetime "invitation_created_at"
    t.datetime "invitation_sent_at"
    t.datetime "invitation_accepted_at"
    t.integer  "invitation_limit"
    t.integer  "invited_by_id"
    t.string   "invited_by_type"
    t.integer  "invitations_count",      default: 0
    t.string   "account_type"
    t.integer  "personalised_search_id"
    t.datetime "drop_off_email_sent_at"
  end

  add_index "users", ["invitation_token"], name: "invitation_token_index", unique: true
  add_index "users", ["invitations_count"], name: "index_users_on_invitations_count"
  add_index "users", ["invited_by_id"], name: "index_users_on_invited_by_id"

end

**Comment by excid3** [comment]
Looks fine to me. I'd probably have to poke around your code to see what's going on. Doesn't seem like it has to do with Pay.

**Comment by redlightmikey** [comment]
I've looked around and can't see anything that would do this... I've also tried to update to Ruby and Rails versions. But still errors. 

it all works by commenting out

`# Pay::Subscription.update_all(status: :active)`

What would be the consequences of this? Is this update_all(status: :active) used else where?

**Comment by redlightmikey** [comment]
When I comment out the that line running my application soon as I use the AssociationProfile.new I get the following error:

`undefined method `type' for :string:Symbol`

Seems similar to this issue: https://github.com/pay-rails/pay/issues/12

**Comment by redlightmikey** [comment]
I've tried absolutely everything I can think of. Changed my rails version and I still end up with the same error:

```
Caused by:
NoMethodError: undefined method `type' for :boolean:Symbol
/Users/michaelcarr/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.11.3/lib/active_record/attribute_methods/time_zone_conversion.rb:64:in `create_time_zone_conversion_attribute?'
```
Called by: 
`Pay::Subscription.update_all(status: :active)`

Googling that led me: https://stackoverflow.com/questions/39642354/rails-4-2-time-zone-conversion-rb-error-how-do-i-fix-this

Which then led me to: https://stackoverflow.com/questions/11894194/how-to-install-ruby-oci8

Finally got that ruby-oci8 installed after hours and it's failing at the exact same line. 

Any suggestions would be appreciated...

**Comment by excid3** [comment]
Yeah, definitely strange since this migration doesn't have anything to do with booleans or time zones!

Would you be able to invite me to your git repo so I can try and replicate it on my machine?

**Comment by excid3** [comment]
This ruby-oci8 thing is for Oracle databases, are you using an OracleDB?

**Comment by redlightmikey** [comment]
> This ruby-oci8 thing is for Oracle databases, are you using an OracleDB?

No, not at all... I just ended up down a weird path trying to get:

gem 'activerecord-oracle_enhanced-adapter'
gem 'ruby-oci8'

to install since, they are the only thing that I found as a solution to that error.
