### ISSUE TITLE
Square payments support

### ISSUE THREAD

**Issue by kieranklaassen** [pay-rails/pay#189]
I'm willing to add Square payments support. Maybe marketplaces integration with them too. Their subscription API is in beta.

https://developer.squareup.com/reference/square/payments-api

Adding it here so people can upvote.

**Comment by excid3** [comment]
Awesome. Would love to see that.

**Comment by 0bserver07** [comment]
hi @kieranklaassen, how would you go about starting? Happy take a stab at it.
Currently, I'm planning to make a fork and add some stuff.

**Comment by kieranklaassen** [comment]
Currently it's on hold from my perspective. Please take it!

**Comment by excid3** [comment]
Their API looks pretty straightforward like Stripe's so I'm excited to see this. 👍
