### ISSUE TITLE
How to associate a Stripe webhook Charge with business models?

### ISSUE THREAD

**Issue by drnic** [pay-rails/pay#196]
In a Rails/Stripe app there are two flows to have a `Pay::Charge` (or `chargeable_class` subclass) created:
1. Rails controller `#create` or `#update` where `current_account.charge(1000, {description: "MyThing sold for $10", currency: "aud", metadata: {mything_id: 123}}` succeeds without a `Pay::ActionRequired` exception raised
2. Via the Stripe webhook back into `Pay::Stripe::Webhooks::ChargeSucceeded`

In the former, after the Charge is created successfully, the controller can associate the business model/activerecord with the `Charge` object; or even can just `mything.update(paid_at: DateTime.now)` annotated the business model.

In the latter, we have no hooks from `ChargeSucceeded` back into our application. Additionally, any metadata we might attach to our initial `current_account.charge(1000, {metadata: {mything_id: 123}})` call is discarded by the `ChargeSucceeded#create_charge` method.

I must be missing something. How are other people rewiring the `ChargeSucceeded#create_charge` webhook back into their Rails app without Stripe::Charge metadata or a hook back into your app?

**Comment by drnic** [comment]
One answer is at https://github.com/pay-rails/pay/issues/154 -- but I'm confused it might be best practice to have a duplicate webhook handler class.

**Comment by excid3** [comment]
We aren't syncing the metadata and other fields in the webhook code currently. I think that would be good to add, but I am not sure about Braintree or Paddle compatibility.

In the Paddle branch, I've added a `data` serialized column for storing extra metadata (for Paddle, that's URLs since theirs are managed). We could probably use the `data` column and store more of the stripe details like metadata in there.

**Comment by excid3** [comment]
Workaround for now would be:

1. Override the `Pay::Stripe::Webhooks::ChargeSucceeded.create_charge` method
2. Or use the `processor_charge` method to retrieve the Stripe::Charge from the API (makes an extra network request, so not ideal)

**Comment by excid3** [comment]
Pay v3 will supports `metadata` option on `charge` and `subscribe`. 

If you're selling a License, for example, you can now say `@user.payment_processor.charge(149_00, metadata: { license_id: 1})` and that will be stored on the `Pay::Charge` (or `Pay::Subscription`)

My last todo is to add a callback so you can take a successful charge and do anything you need (like updating the license status as "paid"). Just need to make sure it's called consistently throughout the payment processors.
