### ISSUE TITLE
Confused by SCA instructions

### ISSUE THREAD

**Issue by mepatterson** [pay-rails/pay#202]
I've watched the "How to use..." video and setup the js and ruby form sides of things, and it works fine. But then there's this line in the Stripe Elements v3 SCA Compatible wiki page:

> We recommend setting these IDs as data attributes on your form as `data-payment-intent="x"` or `data-setup-intent="y"`.

I'm confused by what this is implying I should do to ensure my app handles SCA properly. What is `x` or `y` and where do I get them?

In the video, Chris just sticks the SCA-required credit card number into the form and it prompts for the SCA stuff. When I do the same locally, with all the same code as in the video, it just succeeds without redirecting me anywhere. I guess it's great that everything I'm doing is succeeding, but I'm nervous that when this goes to production, I will run into problems because I didn't setup SCA properly...

**Comment by excid3** [comment]
Stripe SCA requires all their Javascript for the workflow to be functional. If the card requires SCA, there are several different ways it branches.

You can read up on the Stripe docs if you aren't familiar with PaymentIntents or SetupIntents, but the basic idea is a payment intent is used when you want to charge the customer immediately and a setup intent is used for storing a card to be charged later (for trials, updating a card on file for subscription, etc).

The wiki has a document on setting up your Javascript for Stripe SCA:
https://github.com/pay-rails/pay/wiki/Stripe-Elements-v3-SCA-Compatible

**Comment by mepatterson** [comment]
Right. So I setup all that javascript from that wiki page. Is that all I need to do? It _seems_ like it's working...

**Comment by excid3** [comment]
You have to create a payment intent or setup intent (depending on what you're trying to do) and then add the intent's client_secret in the form's data attribute. That's the `x` and `y` you mentioned.

**Comment by excid3** [comment]
The `test/dummy` folder now includes an app with example Javascript and controllers for Stripe and Braintree.
