### ISSUE TITLE
Should Charge be created on new Subscription creation?

### ISSUE THREAD

**Issue by mguidetti** [pay-rails/pay#211]
Hello, 

I've been developing an app that has subscriptions (using stripe in my case) and I had some confusion about charges. 

I had expected that once a new Subscription was created, a new Charge would also be created that represented the first payment of the subscription. But looking closer it seems like Charges are a separate thing from Subscriptions and only represent one-time payments initiated by themselves (not recurring payments from subscriptions). Am I correct?

My goal is that I'd like to be able to list the automatic payments my users have made for their subscriptions on their user profile panel. 

Would it make sense to have charges made after subscription payments? Or am I thinking of a third currently non-existent model (Invoices?) 

Many thanks for your work on this gem!

**Comment by excid3** [comment]
Charges are only created via web hooks for stripe so make sure you're running the stripe cli to forward webhooks in development. 👍

**Comment by mguidetti** [comment]
Ah of course my problem actually had to do with a screwed up stripe cli config within my local docker-compose set up :facepalm: 

But now I understand Pay a bit better, thanks for the reply and clarification!

**Comment by excid3** [comment]
Happy to help! SCA has made this whole thing a lot more complicated, especially since Stripe now requires webhooks to be fully functional in development. At least the stripe-cli helps make that easier than using ngrok or something.
