### ISSUE TITLE
How can we migrate existing customers?

### ISSUE THREAD

**Issue by archonic** [pay-rails/pay#219]
I'm looking to migrate a few hundred existing customers and their subscriptions to Pay. Is there any way to associate Pay::Billable records with an existing subscription? I've noticed that `account.customer` will query the API directly from `owner.email`. That's a good start, but it looks like the only methods of local subscription creation are intended to happen with a card token.

**Comment by excid3** [comment]
There is nothing built-in to Pay to import records from a payment provider if that's what you're asking. You could create the Pay::Subscription records directly. They need the processor, processor ID, etc fields. Same with adding the processor and processor_id on the Billable model.

I've got a pre-gem version of Pay in Hatchbox right now and need to migrate to the gem version at some point so this is particularly relevant to me as well.

**Comment by deikka** [comment]
I'm in the same point. Next week will try with some clients. @excid3 are you thinking about an automated option to do this? Maybe a job, or something?

**Comment by excid3** [comment]
My migration would be existing data in the database, so it'll be probably a custom rake task or something.

As for importing subscriptions via the API, it probably also has to be somewhat custom since Pay won't know which model to use as the `owner`.

The best we can probably do is a documented example you can modify for your app. 

Here's some pseudo code for it that you can adapt. I don't know if this will work exactly, but a rough guideline.

```ruby
Stripe::Subscription.all.each do |stripe_sub|
  user = User.find_by(processor: :stripe, processor_id: stripe_sub.customer)
  if user.nil?
    customer = Stripe::Customer.retrieve(stripe_sub.customer)
    user = User.find_by(email: customer.email)
    user.update(processor: :stripe, processor_id: customer.id)
  end

  subscription = user.subscriptions.where(processor: :stripe, processor_id: stripe_sub.id).first_or_initialize
  subscription.update(
    processor_plan: plan,
    trial_ends_at: (stripe_sub.trial_end.present? ? Time.at(stripe_sub.trial_end) : nil),
    ends_at: (stripe_sub.ended_at.present? ? Time.at(stripe_sub.ended_at) : nil),
    status: stripe_sub.status,
    quantity: stripe_sub.quantity,
  )
end
```

**Comment by deikka** [comment]
> My migration would be existing data in the database, so it'll be probably a custom rake task or something.
> 
> As for importing subscriptions via the API, it probably also has to be somewhat custom since Pay won't know which model to use as the `owner`.
> 
> The best we can probably do is a documented example you can modify for your app.
> 
> Here's some pseudo code for it that you can adapt. I don't know if this will work exactly, but a rough guideline.

Thanks!! Will try and comment :)

**Comment by archonic** [comment]
Just completed this migration myself. I think the biggest challenge is knowing how to asses the status of the subscription when you're working off code that's already migrated to be Pay dependent. My app had just enough data on the Account model to be tied with Stripe (no local representation of a subscription beyond the ID and some bools for status). I ran this in a console, using `Account.first` as a guinea pig. Once I knew the loop would work, I ran this:

```
Account.find_each do |account|
  next if account.sub.present?

  account.processor_id = "stripe"
  account.product_id = 3
  account.save
  status = if account.unpaid?
    'unpaid'
  elsif account.cancelled?
    'cancelled'
  elsif account.current_period_end > Time.current && account.card_last4
    'active'
  elsif account.current_period_end > Time.current
    'trialing'
  else
    'past_due'
  end

  subscription = Pay::Subscription.create(
    owner: account,
    name: account.product_name,
    processor: 'stripe',
    processor_id: account.stripe_subscription_id,
    processor_plan: account.plan.stripe_id,
    quantity: 1,
    trial_ends_at: account.current_period_end,
    ends_at: nil,
    status: status
  )
end
```

`account.sub` is the same as `account.subscriptions.first` in my app.

**Comment by marckohlbrugge** [comment]
What's the current status on importing Stripe data? I'd like to fill all the Pay tables with the same data as if I'd been using the gem from the start.

Any pointers would be greatly appreciated.

**Comment by marckohlbrugge** [comment]
@excid3 Thank you! This (mostly) did the trick!

Only issue I run into when syncing subscriptions is this: https://github.com/pay-rails/pay/issues/829
