### ISSUE TITLE
Make subscription default name settable

### ISSUE THREAD

**Issue by archonic** [pay-rails/pay#220]
I'm blowin up your inbox tonight but I think this is a good idea 😄 

I imagine most people would have a single subscription per billable model. Making the name optional makes sense but it requires a name of "default".
https://github.com/pay-rails/pay/blob/3a0cdfe4f74d28add7b02ff46fe04d0ac09f4e60/lib/pay/billable.rb#L92

It would be nice if we could set `config.default_product_name` or something like that in the pay initializer. Happy to make a PR if you agree.

**Comment by excid3** [comment]
Fine with me to add. Just have to make sure it's pulled out in all places. I know it's used in a handful of method arguments. 👍
