### ISSUE TITLE
How to restart a subscription?

### ISSUE THREAD

**Issue by asecondwill** [pay-rails/pay#221]
If a user creates a subscription, and then later cancels it.  After the grace period is over, they can not resume.

How should I handle that with Pay?  Just create a new subscription?  Should I destroy the previous Subscription when I do that? 

If I don't delete the previous subscription, it create duplicates. 

If I then do things like `@user.subscription.active?`  it looks at the oldest, most not active subscription, not the nice new active one.

**Comment by excid3** [comment]
Yep, just create a new subscription. Stripe and Braintree (and most other APIs) don't allow you to resume a canceled subscription. You just simply create a new one.

If you're listening to webhooks, the new subscription will be the one used for `.active?` and everything.

**Comment by asecondwill** [comment]
Oh right, yes I had got my webhooks muddled up (which i often do) and also needed to be careful with setting Name for subscription and then using the name when querying the Subscription. 

Thanks
