### ISSUE TITLE
How to update a card for a subscription?

### ISSUE THREAD

**Issue by asecondwill** [pay-rails/pay#222]
How should I update a card for an ongoing subscription?

**Comment by excid3** [comment]
https://github.com/pay-rails/pay#updating-a-customers-credit-card

**Comment by asecondwill** [comment]
OK, so I set it up as below. Seems to work. So simple I couldn't work it out!

When I try a card number that should require SCA, it doesn't kick off the SCA process. Should it do? Or is that because it isn't taking a payment in that moment, so will do it when the subscription comes due? 

This card requires authentication on all transactions, regardless of how the card is set up. 
Card: 4000002760003184
```

  def card
  end

  def cardupdate
   @current_retailer.update_card(params[:card_token])
    redirect_to retailer_subscription_path, notice: "Your card has been updated"
    rescue Pay::ActionRequired => e
      redirect_to pay.payment_path(e.payment.id, back: '/retailer/dash')
    rescue Pay::Error => e
      flash[:alert] = e.message
      render :new
  end


          <%= form_with url: retailer_retailer_cardupdate_path, local: true, id: 'payment-form' do |form| %>
              <div class="form-group">
                <label for="card-element">Credit or debit card</label>
                <div id="card-element" class="form-control"></div>
                <div id="card-errors" role="alert"></div>
              </div>
              <div class="form-group">
                <%= form.label "name_on_card", "Name On Card" %>
                <%= form.text_field :name_on_card, id: "name_on_card", placeholder: "Full Name", class: 'form-control' %>
              </div>
              <div class="form-group actions text-right">
                <%= form.submit "Update Card", class: 'btn btn-primary' %>
              </div>
          <% end%>
```

... and the js from the wiki.

**Comment by excid3** [comment]
Updating a card requires a SetupIntent since it's collecting for future use and not immediate payment. Pass that to the form to get your new payment method ID.

**Comment by asecondwill** [comment]
Is that something I create using the gem methods or back to basics with stripe?

**Comment by asecondwill** [comment]
a ha!

https://github.com/pay-rails/pay/blob/c456537091c323bec5e70fa9509dbad05fdf21df/lib/pay/stripe/billable.rb#L17

**Comment by excid3** [comment]
Yup 👍

You can read up on the Stripe docs to learn how it works. It's because of the SCA complexity. 😅

**Comment by asecondwill** [comment]
Sorry, where do I add this? To a field? Or to the data attributes?  

<%= form_with url: retailer_retailer_cardupdate_path,
                        local: true,
                        id: 'payment-form',
                        data: {setupIntent: @current_retailer.create_setup_intent} do |form| %>

**Comment by excid3** [comment]
I do it in the controller and set it as an instance variable. Then the data attribute is set to `@setup_intent.client_secret`.

**Comment by asecondwill** [comment]
Ok, great thanks.  I got this working. 

I had to make some changes to the JS because when  add a data item to the form as above, rails makes it all lowercase, so to make it work i changed this line:

`let setupIntentId = form.dataset.setupIntent`

to 

`let setupIntentId = form.dataset.setuptintent`

In case that helps anybody that looks at this ticket in the future.

**Comment by excid3** [comment]
Use underscores in your data hash `data: { setup_intent: @setup_intent.client_secret }` and it will work without changes. 👍

**Comment by asecondwill** [comment]
That is confusing! Have updated and confirm it works.  Thanks again.
