### ISSUE TITLE
How can I translate error messages?

### ISSUE THREAD

**Issue by dominikdarnel** [pay-rails/pay#228]
Any chance for i18n support?

**Comment by dominikdarnel** [comment]
Any chance for  i18n support?

**Comment by excid3** [comment]
Just was thinking about this yesterday. Definitely need to do that. 👍

We mostly have to just migrate all the strings into a locale file. I'm not sure when I'll have time but after Thanksgiving I'll have time. If anyone wants to create PR that'd be great.

**Comment by dominikdarnel** [comment]
Hey Chris!
Thank you for your blazing fast response!
I would love to hop in and do translation handling!
Any suggestions or ideas how should I approach it?

**Comment by excid3** [comment]
We've actually gotten a start on this that I forgot about. https://github.com/pay-rails/pay/blob/master/config/locales/en.yml
These are for the PaymentsController primarily. 

We just need to go through `app` and `lib` to extract all the other strings we missed and put them in the locales file. 👍

**Comment by dominikdarnel** [comment]
That sounds good!
There is one thing tough.
I am calling `Pay::Billable#subscribe` directly in an API project of mine.
The problem is that when there is an error, this method returns only the error message, not the whole error object:

https://github.com/pay-rails/pay/blob/be2f8cdaf1f484060718873a3bb8a30894b4ec41/lib/pay/stripe/billable.rb#L81-L84

Is there any way to change that?
If it returned the whole object, I would be able to reference the code in my translations as such:

```ruby
      rescue Pay::Error => e
        Rails.logger.error(e.message)
        render json: {
          message: I18n.t("stripe.errors.#{e.code}")
        }, status: :unprocessable_entity
      end
```
Thank you very much!

**Comment by excid3** [comment]
We would need to modify the Pay::Error class to let us pass in the original exception. That would be useful to do.

BraintreeErrors already have something similar, so we can probably do it like that. https://github.com/pay-rails/pay/blob/master/lib/pay.rb#L108

**Comment by dominikdarnel** [comment]
https://github.com/pay-rails/pay/pull/229

**Comment by dominikdarnel** [comment]
okay, I am gonna start working on it in this PR: #229 
So hoefully If I extend Pay::Error, to work like Pay::BraintreeError, it would do the trick for us.
I will adjust the tests too.
ANyways, is it not going to create breaking changes?

**Comment by excid3** [comment]
Yeah I'm not sure if it will be a breaking change. If so, we can probably set it up slightly different.

I'm not at the computer much today for the holiday here but I'll take a look tomorrow. 👍

**Comment by dominikdarnel** [comment]
Okay Chris!
Happy Thanksgiving!
I am looking forward to work on this issue, and hear back from you!
