### ISSUE TITLE
Unable to swap plans on an active subscription

### ISSUE THREAD

**Issue by archonic** [pay-rails/pay#235]
I've found that I can swap on a subscription that is trialing but not one that is active. The error when it's active is:

```
Pay::Error: This customer has no attached payment source or default payment method.
from /usr/local/bundle/gems/pay-2.2.1/lib/pay/stripe/subscription.rb:45:in `rescue in stripe_swap'
```

This is despite setting the billable `card_token`, which I don't think is a requirement from Stripe in order to swap plans.

I'm stubbing an active subscription by running this after going through a normal factory to subscribe a user:
```
user.subscriptions.first.update(
  status: "active",
  trial_ends_at: nil,
  ends_at: 30.days.from_now
)
```

I've reproduced this with a failing test here: https://github.com/archonic/limestone/blob/swap-bug/spec/requests/subscriptions_spec.rb#L135

The trial user context works and the active subscription user does not.

**Comment by excid3** [comment]
That error comes from Stripe (as you can see in the rescue): https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/subscription.rb#L50-L51

An active subscription in Stripe would require a card (because you're paying for a subscription). I'm not sure how you created an active subscription in Stripe without a payment method?

**Comment by archonic** [comment]
I can set the `card_token` on the billable model and I get the same error.

```
pry(#<SubscriptionsController>)> current_user.card_token = params[:payment_method_id]
=> "pm_1HwBviFpMcvkWhcFmO3mAXZQ"
[3] pry(#<SubscriptionsController>)> current_user.sub.swap(stripe_plan_id)
Pay::Error: This customer has no attached payment source or default payment method.
from /usr/local/bundle/gems/pay-2.2.1/lib/pay/stripe/subscription.rb:45:in `rescue in stripe_swap'
```

Am I missing some way to attach the payment method or set it as default?

**Comment by excid3** [comment]
You have to call `update_card(token)` if you want to explicitly update the card before a swap (at least currently). 

We do automatically call that on creation of a charge or subscription, but not on swaps.

**Comment by archonic** [comment]
It's behaving as if it's acting on cached data. I set the `card_token` and it had the same error, but I checked `current_user.customer.invoice_settings`, saw the payment method set there, then reran `current_user.sub.swap(stripe_plan_id)` and it worked. Very weird...

**Comment by excid3** [comment]
Hmmm, trying to think what would cause that.

**Comment by archonic** [comment]
I have tests passing with this patch:

```
current_user.card_token ||= params[:payment_method_id]
# ???
current_user.customer.invoice_settings
current_user.sub.swap(stripe_plan_id)
```

Perhaps things are caching on the Stripe side of things?

**Comment by excid3** [comment]
That should really be the following:

```
current_user.update_card(params[:payment_method_id])
current_user.sub.swap(stripe_plan_id)
```

**Comment by archonic** [comment]
Ok, I've got the testing flow figured out. A truly active subscription will have had the `update_card` method called when a user entered their card. So the steps are:

1. Create the user which in my case also creates a trialing subscription (no card req.)
2. Call `update_card` on `after(:create)` on the `:subscribed` trait in the factory (simulating the user entering their card).
3. Call `user.subscriptions.first.update(status: "active", trial_ends_at: nil, ends_at: 30.days.from_now)` in order to simulate the trial ending and receiving a Stripe webhook.
4. Test `swap`.

Step 3 doesn't really feel right to me. I'm open to suggestions on how to do that better.

**Comment by excid3** [comment]
What about step 3 doesn't feel right? The only way Pay knows about subscription changes is via a webhooks, so you've got to fake it for tests since you're not going to get those. We don't have any "fake" webhook events to simulate in testing.

**Comment by archonic** [comment]
I guess it doesn't feel right because I just guessed at what that webhook would change 😛. I'll come back around to it if I learn it was wrong.

**Comment by excid3** [comment]
Yeah, it's hard to abstract everything since all the services work differently. The `trial_ends_at` and `ends_at` are the main sources of truth. Status is mostly just for syncing with Stripe.
