### ISSUE TITLE
Keep track of Stripe's `current_period_end`

### ISSUE THREAD

**Issue by benjaminwood** [pay-rails/pay#242]
I see Stripe's `current_period_end` is used when canceling a subscription but it is not otherwise used/stored in the DB. My understanding is that this attribute can be used to determine when a subscription will be renewed. 

Is my understanding correct? If so, is there any specific reason *not* to keep track of `current_period_end` so it can be used, for example, to show the user when the next charge will occur?

Thanks for your work on this gem. :+1:

**Comment by benjaminwood** [comment]
Thinking this through, perhaps it has to do with proration. I suppose `current_period_end` doesn't indicate that there is actually an amount due.

**Comment by excid3** [comment]
Yeah, we're not currently keeping track of the next billing date in the gem. At the moment, the only thing we're tracking is cancellation dates (ends_at) so we know when the subscription is over.

We probably should but not sure about supporting that for Braintree or Paddle.

Would definitely love to add this feature so we can show when the next payment is due.

**Comment by scope2229** [comment]
For now would it be possible to override the [pay/stripe/webhooks/subscription_created](https://github.com/pay-rails/pay/blob/86074c13a121b8515f7417cf2e983a1512b54840/lib/pay/stripe/webhooks/subscription_created.rb#L34) so that we could add our own current_period_ends field to Pay::Subscriptions.

**Comment by excid3** [comment]
Yeah, so I just prepend a module to override those right now. 

For example:

```ruby
module Webhooks
  module ChargeSucceededExtension
    def notify_user(billable, charge)
      Pay::UserMailer.with(billable: billable, charge: charge).receipt.deliver_later
    end
  end
end

Rails.application.config.to_prepare do
    require "pay/stripe/webhooks"

    class Pay::Stripe::Webhooks::ChargeSucceeded
      prepend Webhooks::ChargeSucceededExtension
    end
  end
end
```

You could add the `current_period_end` in that way. I may start recording that for Stripe and just leave it out for Braintree and Paddle. These payment providers will never end up being consistent.

**Comment by benjaminwood** [comment]
I questioned this earlier but after a bit of testing (and a chat with Stripe support), I can confirm that `current_period_end` cannot be used to indicate the date of the subscriber's next payment due. If proration applies, the next invoice amount can be $0.

Still, it may be useful for some people so I think it's worth keeping track of. I do wish Stripe offered a `next_payment_due_on` or something along those lines. Stripe support verified that there is no such information available via their API.  The best you can do is request the next "upcoming" invoice, and check to see if the amount due is > $0.

**Comment by excid3** [comment]
That's good to know and makes sense. It seems like the upcoming invoice is the way to go.
