### ISSUE TITLE
Ability to add extra details of Customer before creating it on Stripe

### ISSUE THREAD

**Issue by BilalBudhani** [pay-rails/pay#250]
Stripe India requires extra details of the customer like country, address line 1 before it can be created. The current implementation breaks whenever `Pay` tries to create a customer with just email. 

It would be great if there is a method to define extra params which can be called before creating a customer in Stripe.

**Comment by excid3** [comment]
Awesome, would love to see that.

I imagine we could do this a few different ways, but two ideas off the top of my head:

1. An method you can override that returns a hash:

```ruby
def stripe_customer_fields
  { name: name, email: email }
end
```

2. An array of attributes used to generate the hash

```ruby
class User
  stripe_customer_fields :name, :email
end
```

Then Pay could create the customer by taking each of those and transforming it into a hash:

```ruby
@stripe_customer_fields.map { |field| [field, send(field)] }.to_h
#=> { name: "Chris", email: "chris@example.com" }
```

I prefer the latter, but it isn't as flexible.

**Comment by BilalBudhani** [comment]
Your suggestions look great. I lean towards the former PORO approach would avoid DSL. 

So, If there is a payment provider specific method defined in the `Model` like `[payment_provider]_customer_fields` than `Pay` would just merge the output hash with default params and send it to respective API.

**Comment by ledermann** [comment]
Is there any news here? I am also looking for an easy way to sync customer data (like address) with Stripe. 
Having a method like the above describe `stripe_customer_fields` would be great - I prefer the first approach, too.

**Comment by excid3** [comment]
We've added `pay_customer metadata: :customer_metadata`. https://github.com/pay-rails/pay/blob/master/lib/pay/attributes.rb#L81

It only supports metadata currently. You can always update the Stripe::Customer as needed directly too.
