### ISSUE TITLE
NoMethodError when resuming Stripe subscriptions

### ISSUE THREAD

**Issue by dzacarias** [pay-rails/pay#253]
It seems that the `paddle?` check introduced [here](https://github.com/pay-rails/pay/blob/59ab4da98b89c5266f7cc4a9051a408a414913f6/app/models/pay/subscription.rb#L74) creates a NoMethodError when trying to resume Stripe subscriptions. 

If I understand the lib correctly, that symbol only exists for paddle subscriptions. When trying to resume, it's first checked if it's on its grace period and then if it's paused. When we hit the `paused?` method there's a check if it's a paddle sub, and the error follows.

**Comment by excid3** [comment]
Paddle is the only payment provider we support that supports a "paused" state. Stripe subscriptions are either active, canceled, or flagged to be canceled at the end of the period.

Basically the pause functionality would not be used if you're using Stripe.

**Comment by dzacarias** [comment]
Right. But I'm hitting this code path using Stripe, and the library is throwing an error because it doesn't have the `paddle?` symbol.

**Comment by excid3** [comment]
Gotcha, yeah this probably should not have any paddle specific logic on that layer.
