### ISSUE TITLE
Any plans to support square payment?

### ISSUE THREAD

**Issue by poudelprakash** [pay-rails/pay#257]
https://squareup.com/us/en

**Comment by excid3** [comment]
Not at the moment as I've never used it, but if someone would like to contribute I'd be more than happy to help with the integration. 👍

**Comment by eclectic-coding** [comment]
Found out [Square](https://github.com/square/square-ruby-sdk) has a Ruby SDK gem. 

Square is very popular as a POS payment processor and might be a good addition to your gem.
