### ISSUE TITLE
How to check if a users subscription is active?

### ISSUE THREAD

**Issue by jespr** [pay-rails/pay#26]
What's the preferred way to see if the users subscription is active? Here I'm thinking we want to show a link to a let's say billing page if the user is subscribed.

The current api sort of expects us to pass in a name for a subscription to `user.subscription` - and since we can have many different plans, that'll be a bit tedious. 

Would the preferred way be to do `user.subscriptions.last.active?` or could we change `user.subscription` to just take the latest subscription if no name is given?

**Comment by excid3** [comment]
You would just say `user.subscription.active?`

The name is optional so you can ignore it unless you need it. If you wanted multiple subscriptions, you'd specify the name like so `user.subscription('secondary').active?`

**Comment by jespr** [comment]
Ah. I think the documentation might've confused me then - I get what you're saying, and I understand what I did wrong. 

When I subscribe, I need to invoke the method as such: `current_user.subscribe('default', 'mystripeplanname')` - that confused me, so I intentionally supplied a different name.

Maybe it would be better if we change the method to:
```
def subscribe(name: 'default', plan: 'default', options={})
  check_for_processor
  send("create_#{processor}_subscription", name, plan, options={})
end
```

So I don't have to specify the default name, if I don't need multiple subscriptions.

**Comment by excid3** [comment]
Yeah I think that would be good. Some of the API in these parts needs polishing as it changed several times as we were working on it. I much prefer the named parameters, but I always forget that I can use them. Old habits die hard.

Want to make a PR for that?

**Comment by jespr** [comment]
Definitely! Will do

**Comment by jasoncharnes** [comment]
Thanks, @jespr sorry for the delay. Thanks @excid3 for hopping in.
