### ISSUE TITLE
uninitialized constant Pay::VERSION with stripe gem

### ISSUE THREAD

**Issue by hss-mateus** [pay-rails/pay#267]
When initializing a new rails project with the latest versions of `pay` and `stripe`, running the migration generator gives this error.

In my gemfile:

```ruby
gem "pay", "~> 2.4"
gem "stripe", "~> 5.29"
gem "stripe_event", "~> 2.3"
gem "receipts", "~> 1.0"
```

Relevant stacktrace part:

```
NameError: uninitialized constant Pay::VERSION
/home/mt/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.4.3/lib/pay/stripe.rb:19:in `setup'
/home/mt/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.4.3/lib/pay/engine.rb:39:in `block in <class:Engine>'
```

A temporary solution is to get the gem version and assign it to a constant in an initializer

```ruby
# config/initializers/pay.rb

Pay::VERSION = Gem.loaded_specs["pay"].version.to_s
```

**Comment by excid3** [comment]
Just released 2.4.4. That should be fixed now.

I had been missing the `require "pay/version"` line in the gem. It's in the gemspec, so it all worked in testing, but not once you release it. 😅
