### ISSUE TITLE
How to customize paddle webhooks?

### ISSUE THREAD

**Issue by hcyildirim** [pay-rails/pay#268]
I'm trying to add an extra parameter to the user's subscription after her subscription got created. So far I tried:

```ruby
# app/lib/paddle/webhooks/subscription_created.rb

module Paddle
  module Webhooks
    module SubscriptionCreated
      def initialize(data)
        subscription = Pay::Paddle::Webhooks::SubscriptionCreated.new(data)
        plan = Plan.find_by!(paddle_plan_id: subscription.processor_plan)

        subscription.update!(addons: plan.addons)
      end
    end
  end
end

# config/initializers/subscription_extensions.rb

Rails.application.config.to_prepare do
  require 'pay/paddle/webhooks'

   class Pay::Paddle::Webhooks::SubscriptionCreated
     prepend Paddle::Webhooks::SubscriptionCreated
   end
end
```

Could you point me in the right direction? What should I do?

**Comment by excid3** [comment]
How about if you do this:

```ruby
# config/initializers/pay.rb

module SubscriptionCreated
  def initialize(data)
    subscription = Pay::Paddle::Webhooks::SubscriptionCreated.new(data)
    plan = Plan.find_by!(paddle_plan_id: subscription.processor_plan)

    subscription.update!(addons: plan.addons)
  end
end

Rails.application.config.to_prepare do
  Pay::Paddle::Webhooks::SubscriptionCreated.prepend(SubscriptionCreated)
end
```

**Comment by hcyildirim** [comment]
That works! But I just found out it's an endless loop, we prepend `SubscriptionCreated` to `Pay::Paddle::Webhooks::SubscriptionCreated` and call it inside the `SubscriptionCreated` module so it always calls itself

**Comment by excid3** [comment]
Yeah, you will want to call `super` instead so it calls the original method. I updated the example for you. 👍

**Comment by hcyildirim** [comment]
Thank you!

**Comment by hcyildirim** [comment]
Hi @excid3, when I reload the app on the rails console or change any file on the project `SubscriptionCreated` class throws an error: `ArgumentError (wrong number of arguments (given 1, expected 0))`

I know it's been almost 6 months but I couldn't figure it out. Do you have any idea?
