### ISSUE TITLE
Create subscribe without pinging an api for select processor_id's 

### ISSUE THREAD

**Issue by jeremiahlukus** [pay-rails/pay#275]
I want to be able to create a subscription to apple pay or google play using their api. When i get a success back i want to be able to do` user.subscribe(plan: processor_id)`  if the `processor_id` is `apple_pay` (or whatever i pass) i want to just add the subscription to the user model.

**Comment by excid3** [comment]
I'm not sure what your question is exactly, but Apple and Google Pay would just be in Javascript on the client side. You'll get a payment method ID back and you'd save that to your customer before subscribing.

**Comment by jeremiahlukus** [comment]
In the jumpstart rails pro template how did you create the free plan and assign it to a user so that is shows up in user.subscriptions ha

**Comment by jeremiahlukus** [comment]
subscriptions.create(subscription_params)

**Comment by excid3** [comment]
Yep, just created a fake subscription. 👍 

I want to add that as a feature to Pay so we can have a Fake processor you can use for giving free subscriptions to users.
