### ISSUE TITLE
Document need to set config.action_mailer.default_url_options

### ISSUE THREAD

**Issue by ryanfb** [pay-rails/pay#276]
If not set this defaults to `nil` in my current Rails 6.1.3 environment. Due to [this line](https://github.com/pay-rails/pay/blob/v2.6.1/lib/pay/stripe/billable.rb#L17), this results in somewhat obscure errors like the following when trying to e.g. create a checkout session with `current_user.payment_processor.checkout(mode: "subscription", line_items: "default")`
```
undefined method `merge' for nil:NilClass
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:263:in `call'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:213:in `call'
actionpack (6.1.3) lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
pay (2.6.1) lib/pay/stripe/billable.rb:201:in `checkout' 
```
It's sufficient to set e.g. `config.action_mailer.default_url_options = {}` to avoid this in development.

**Comment by excid3** [comment]
Since we have to generate URLs for Stripe Checkout, we'll need default URL options configured somewhere.

Maybe that could become:

```ruby
Rails.application.config.action_mailer.default_url_options || {}
```

We should replicate this in a test and see if something like the above fixes it.

**Comment by excid3** [comment]
That did the trick. You'll now get the normal `ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true` if it's not set.

Also added a note to the Installation instructions in the readme.
