### ISSUE TITLE
Class including Pay::Billable not inspectable because of processor method override

### ISSUE THREAD

**Issue by grk** [pay-rails/pay#277]
Since https://github.com/pay-rails/pay/commit/703492fd66a14aaab7e0c4b003655eaacc69a331 the processor method is overwritten with

```ruby
    def processor
      super.inquiry
    end
```
which fails when the record doesn't have any processor.

As far as I can tell this inquiry is not used anywhere, so could be either dropped or changed to `super&.inquiry`.

**Comment by excid3** [comment]
That definitely should be `super&.inquiry` 👍 

The point of this is to let you ask which processor the object is using so we want to keep it.

```ruby
user.processor.stripe? #=> true
```
