### ISSUE TITLE
List invoices and payments with Stripe

### ISSUE THREAD

**Issue by guillaumebriday** [pay-rails/pay#278]
How can I retrieve invoices and payments to show them in my application?

**Comment by excid3** [comment]
You'd just use the association `current_user.charges`

**Comment by excid3** [comment]
If you don't have any records, then you don't have your webhooks hooked up. Webhooks are required because of SCA (even in dev).

**Comment by guillaumebriday** [comment]
Ah! Ok I didn't understand this was related, I'm a newbie with Stripe, will try to set this up then! Thanks

**Comment by excid3** [comment]
I'm going to be updating the docs to include more info on that. For now, the Stripe webhooks are mentioned here: https://github.com/pay-rails/pay#strong-customer-authentication-sca
