### ISSUE TITLE
Add Stripe checkout.session.completed webhook handler

### ISSUE THREAD

**Issue by ryanfb** [pay-rails/pay#285]
As noted in https://github.com/pay-rails/pay/issues/282#issuecomment-786031845, it seems like sometimes Stripe Checkout will *only* fire the `checkout.session.completed` webhook without the corresponding subscription hooks, e.g.:
* checkout.session.completed
* charge.succeeded
* invoice.updated
* invoice.updated

Or another example, where `customer.subscription.updated` fires but the subscription isn't created first and no subscriptions currently get attached to the user:
* checkout.session.completed
* payment_method.attached
* invoice.created
* invoice.updated
* invoice.payment_succeeded
* payment_intent.succeeded
* customer.subscription.updated
* invoice.paid

The `checkout.session.completed` event does have `subscription` metadata which could be used to load/create/update the corresponding subscription, if present.

**Comment by excid3** [comment]
This has been added along with `checkout.session.async_payment_succeeded`
