### ISSUE TITLE
Unable to change product on Pay::Charge

### ISSUE THREAD

**Issue by jeremiahlukus** [pay-rails/pay#297]
I am creating a new charge like 

```
@charge = Pay::Charge.new(subscription_params)
@charge.product = "foo"
```

i get the error 
undefined method `product=' for #<Pay::Charge:0x00007fbb4a20d4d0>  

However `Pay::Charge.last.product`  returns a string so product is being attached somehow. How can i change the product attached to the charge?

**Comment by excid3** [comment]
There isn't a `product` on Pay::Charge: https://github.com/pay-rails/pay/blob/master/app/models/pay/charge.rb

What are you tryign to do?

**Comment by jeremiahlukus** [comment]
That is what i saw after i posted.. somehow in jumpstart I'm able to do `Pay::Charge.last.product` and it returns a string looks like application name. I don't see anywhere in the code where this is happening. I would like to change the product so that my receipt will show whatever i choose.

**Comment by jeremiahlukus** [comment]
seems like a question for 
https://github.com/excid3/receipts  

sorry

**Comment by jeremiahlukus** [comment]
Ah ha 

https://github.com/pay-rails/pay/blob/39ee56ab3b4992eb22d86f4a7d1a1a7179cc968d/lib/pay/receipts.rb#L19  


How do i change this?

**Comment by excid3** [comment]
Ah, yes. Forgot about that.

You can add a `product` method to the Pay::Charge model in your app to override that.
