### ISSUE TITLE
Unable to cancel a subscription, error offers no details

### ISSUE THREAD

**Issue by archonic** [pay-rails/pay#298]
I've got workspaces in production that have failed to delete because the subscription can't be cancelled.

At first I thought the error might have been that an unpaid subscription can't be cancelled but I could cancel it from the Stripe dashboard. The error just says `Pay::Stripe::Error (Pay::Stripe::Error)`. Do you know of a way to bubble the error from Stripe, and could Pay do that by default?

**Comment by excid3** [comment]
Yeah, it just wraps the Stripe error: https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/charge.rb#L22
We need to refactor that so it's a bit cleaner.

Try accessing error.result to see the Stripe error I believe?

**Comment by archonic** [comment]
The object returned is unfortunately `nil`.

>

**Comment by excid3** [comment]
We've got tests for the error messages actually:

```ruby
  test "handles exception when creating a charge" do
    exception = assert_raises(Pay::Stripe::Error) { @user.charge(0) }
    assert_equal "This value must be greater than or equal to 1.", exception.message
  end
```

**Comment by excid3** [comment]
Try 345dff4

I removed the initialize method on the error so Ruby can deal with it. It seems like it properly sets the `to_s` now and you can always reference `exception.cause` to access the original error.

**Comment by archonic** [comment]
I couldn't reproduce the issue locally and when I upgraded to pay master on production, cancelling the subscription worked. I'm not sure what the error ever was. I noticed that `account.charge(0)` matches the test output.

I suppose I can close this. How would I access the exception object though?
