### ISSUE TITLE
[STRIPE] Create subscription with bad card, then retrying with good card, is guaranteed to fail

### ISSUE THREAD

**Issue by suan** [pay-rails/pay#300]
I might be missing something, but I think **there's a logic flaw that prevents you from successfully creating a Stripe subscription, if the first attempt was with a bad card**. Specifically this is from a jumpstart-rails project but I believe the issue is entirely within `pay` - Here's the sequence of events:

- From new slate: No Stripe customer exists yet
- Enter a bad card and submit: `Billable#subscribe` called
- It [creates stripe customer and adds the card as a payment_method](https://github.com/pay-rails/pay/blob/6d9aaa48361645a99d30bfa2519993cb4cd96f53/lib/pay/stripe/billable.rb#L32-L42)
- Stripe Subscription creation fails, but a stripe customer has now been saved, cause that was a separate call...

Then immediately:

- Enter _valid_ card and submit: `Billable#subscribe` called again
- Now **because the stripe customer already exists**, it [doesn't attach the new card](https://github.com/pay-rails/pay/blob/6d9aaa48361645a99d30bfa2519993cb4cd96f53/lib/pay/stripe/billable.rb#L30)
- This ultimately results in a Stripe-side error of _"This customer has no attached payment source or default payment method"_

---

Is this "expected behavior", and library users are expected to detect if the Stripe customer already exists and manually update their card first if so? (If so, I'd highly recommend a change to jumpstart-rails to handle this case, as it's something that happens alot when customers enter card numbers)

**Comment by excid3** [comment]
Thanks for this. Should be fixed now. 👍
