### ISSUE TITLE
Checkout redirects before user.subscribe() has completed.

### ISSUE THREAD

**Issue by scope2229** [pay-rails/pay#303]
When i checkout in development using a fresh user the database hasn't been updated and so i get an error complaining about missing method 

ActionView::Template::Error (undefined method `strftime' for nil:NilClass):

Refresh the page when stripe webhooks are complete and the error is gone and the time is formatted as needed.

**Comment by excid3** [comment]
You'll have to provide some more details. Sounds like your code is trying to access a record that doesn't exist yet until the webhooks are complete.

**Comment by scope2229** [comment]
That's exactly what's happening. Is there a way to intercept the webhook and only redirect once complete

**Comment by excid3** [comment]
You can query the backend with an AJAX endpoint or send a websocket message to the client if you want to wait until it's completed.
