### ISSUE TITLE
Multiple Stripe API keys

### ISSUE THREAD

**Issue by fabn** [pay-rails/pay#304]
I discovered this gem and I think it's awesome.

However I cannot use it in my current project because it's a multitenant project and I need to interact with multiple stripe accounts. Obviously the same would be helpful for Braintree as well.

I understand this use case will require a lot of refactoring but is it something you may want to consider to support in the future? 

Thanks

**Comment by excid3** [comment]
Already working on it: https://github.com/pay-rails/pay/pull/294

I don't have plans to support Braintree Marketplace functionality at the moment, but anyone's welcome to contribute that. Should be fairly easy to do once we have the Stripe Connect piece finished.

I've heard Braintree may be merging into PayPal anyways and it looks like the Braintree developer docs are moving to PayPal's site, so it may be best to hold off on that anyways. Seems like they're making some big changes.

**Comment by fabn** [comment]
Hi @excid3, #294 is a great PR but I wanted to express a different concept here. I meant to say would it be possible to use different *stripe api keys*, not accounts in the sense of Stripe Connect parlance.

**Comment by excid3** [comment]
Ah. You can set `Stripe.api_key` outside of the gem. We won't be building anything for that.

**Comment by kudapara** [comment]
Won't setting `Stripe.api_key` affect the global scope of the gem, e.g affecting other tenants of the same system?

**Comment by kudapara** [comment]
I had not realised this issue was there when I opened #316 , but I think it's the same issue.

**Comment by fabn** [comment]
> Won't setting `Stripe.api_key` affect the global scope of the gem, e.g affecting other tenants of the same system?

Yes, especially because `Stripe.api_key` is global (no thread current, no locks, etc) so you cannot doing something like 

```ruby
begin
  Stripe.api_key, old_key = key_from_somewher, Stripe.api_key
  # your stuff with temporary key
ensure
  Stripe.api_key = old_key
end
```

But this will not be thread safe unless you wrap it with some kind of mutex.

The only way I found until now to do something similar is to wrap individual api calls in a service class and pass key as parameter and invoke Stripe with that key, e.g.

```ruby
Stripe::Customer.create(params, api_key: customer_api_key)
```

But that would mean to not be able to use this gem anymore. Maybe a suggestion you could wrap `Stripe.api_key` to use into some kind of thread local variable and use that as key.

**Comment by excid3** [comment]
Stripe wants you to use Stripe Connect if you're building an app that processes payments on behalf of other Stripe accounts. The Stripe global API is designed to be the platform's API key for that reason.

I'd recommend discussing this more with Stripe.

**Comment by kudapara** [comment]
@fabn check the solution I posted under #316 and see if it can help you. I did not post it here, because it also includes solution for Braintree.
