### ISSUE TITLE
Add invoice Model

### ISSUE THREAD

**Issue by guillaumebriday** [pay-rails/pay#305]
We the stripe gem, we can retrieve an invoice:

```ruby
invoice_id = Stripe::Charge.retrieve(charge.processor_id).invoice
invoice = Stripe::Invoice.retrieve(invoice_id)
```

it has many useful information like `invoice_pdf` to download a pdf directly from Stripe.

Do you think we should create an invoice model to get this information directly?

**Comment by excid3** [comment]
I just updated the code to auto-expand the invoice and subscription when you retrieve a Stripe charge. That should make it so you don't have to make multiple API calls: https://github.com/pay-rails/pay/commit/73f559997cba8f2829a45d68c912c662fce04357

I could see adding an Invoice object. The hard part is making that stuff semi-consistent across Braintree, Paddle, etc.

**Comment by guillaumebriday** [comment]
I tried on master:

```ruby
= charge.processor_charge.invoice.hosted_invoice_url
```

it works fine!

I will open a PR to add all this part of the code in the README, what do you think?

**Comment by excid3** [comment]
Sounds good! I think long term well end up adding an Invoice model too but this will be good for now. 👍
