### ISSUE TITLE
Checkout button not clickable on Safari

### ISSUE THREAD

**Issue by noramari** [pay-rails/pay#307]
Hi!

I implemented a payment system with Pay to my app. It works perfectly with Chrome, but when trying it on Safari in production, nothing happens when the checkout button is clicked. 

The button is rendered with the following code. I have not edited the Pay partial views.

`<%= render partial: 'pay/stripe/checkout_button', locals: { session: @checkout_session, title: "Select Plan" } %>`

I am not very experienced so I apologize if this is not an issue I should report here.

**Comment by excid3** [comment]
Can you open the developer tools and paste any Javascript errors?

**Comment by noramari** [comment]
Well, this is embarrassing, the problem was totally unrelated to Pay... It was about Stripe and a certificate issue with my site, which I believe I can fix myself. Sorry about cluttering the issues, I will close this now!
