### ISSUE TITLE
Received unknown parameter: currency

### ISSUE THREAD

**Issue by scratchoo** [pay-rails/pay#308]
issue in the file: https://github.com/pay-rails/pay/blob/87c36286b375fdc98befb0ada7463416e8be9db3/lib/pay/stripe/billable.rb#L223

in the method **checkout_charge**, the price_data has:

`currency: options[:currency] || "usd",
`

Then after it you pass **options without deleting the key :currency if set by the user

The error I'm getting:  "Received unknown parameter: currency"

So I think this is the cause of the error 

It would be nice if you add to the doc how to do one time charge with custom price, that what I was trying to do :)

I switched back to use **checkout()** instead of **checkout_charge()** because I need to set the currency. and yeah the first one is working without issue!

**Comment by excid3** [comment]
Ah yes, that should be `currency: options.delete(:currency) || "usd"`

**Comment by excid3** [comment]
Alrighty, pushed up 44381ab

Want to try master and make sure that fixes it for ya?

**Comment by scratchoo** [comment]
@excid3 yes it's working fine now, thank you Chris!  

btw the charges I have belongs to users but what we charge the user for is a "Reservation"

Actually user has_many reservations

when a charge succeeds I know it's for USER1 but I have no idea which reservation is for!

Do I need to make pay for Reservation instead of User? 

or should I add reservation_id in pay_charges table (but in this case how I can fill it?)

**Comment by excid3** [comment]
You would pass the reservation_id in as metadata. Then setup a webhook to listen for the checkout completed event and update your reservation.

https://github.com/pay-rails/pay/blob/master/docs/webhooks.md

**Comment by excid3** [comment]
Released this as 2.6.10 🚀

**Comment by scratchoo** [comment]
@excid3  this is not the first time that I noticed it happens...  the same charge is created twice, **I will send you a screenshot of my log**, and listening for the webhook charge succeeded (as you told me) 

Can you please tell me where exactly to put the metadata? I added it in the session creation like this (but it didn't wokr):

```
@checkout_session = payer.payment_processor.checkout_charge(
      amount: price * 100,
      name: "réservation",
      quantity: 1,
      currency: "eur",
      success_url: thank_you_url,
      locale: 'fr',
      metadata: {reservation_id: @reservation.id},
    )
```

**Comment by scratchoo** [comment]
Here is the screenshot of charge created twice in the database: http://i.imgur.com/4A2wIPU.png 

also as I told you, adding a listener to the webhook  `Pay::Webhooks.delegator.subscribe "stripe.charge.succeeded", ChargeSucceededStripe.new`  seems to be executed 4 times (I have a "puts event"  and I see the event in my logs 4 times
