### ISSUE TITLE
Rails API-only integration?

### ISSUE THREAD

**Issue by doutatsu** [pay-rails/pay#309]
I have a SPA app and an API only rails app. I wanted to set up pay, considering there shouldn't be much difference, as long as I send back session URLs, but unfortunately keep on hitting `(undefined local variable or method 'root_url' for #<Pay::Stripe::Billable:0x00007fb94dda9720`

Looking into it, I presume it's happening in this method: https://github.com/pay-rails/pay/blob/44381ab827a46cf854a5d6d64725d8055d5cd153/lib/pay/stripe/billable.rb#L195-L217

Which is simply setting up URLs to go back to, in which case that would be the page in my SPA, where I initiated the request. But I don't believe I am able to provide these URLs as part of the checkout method, meaning I can't make it work with SPA.

It would be great if such a feature was added as well as a tutorial provided on how to integrate with an API-only Rails app, not just one for a monolith. Thanks!

**Comment by excid3** [comment]
Is it because your app doesn't have a root_url? Does adding one fix it?

**Comment by doutatsu** [comment]
@excid3 Ah, I just realised that `root_url`, would be the `routes.rb` `root to: ...`. I don't have it set indeed, but even if I set it, it won't really function like I'd like here. API is making a request for checkout or billing, but I want to return to my SPA, which is on an entirely different domain, instead of the API `root`. Which is why being able to see these URLs would still be needed, I think

**Comment by excid3** [comment]
Right, I just wanted to confirm that was where the error was coming from. 👍 

We can reorder this code to fix that easily.

**Comment by doutatsu** [comment]
Fantastic, thanks @excid3. I've started implementing stripe on my own after having this issue and realised just how much needs to be built to make it work, so I'd really like to use your gem instead 😂

**Comment by excid3** [comment]
Will you try the `fix-checkout-url-options` branch? I just changed it to check options first, then fallback to `root_url` if none was passed. That should fix it for you.

There is seriously a ton of work to build an integration, so I'm happy to make that easier. 🤓

**Comment by doutatsu** [comment]
Just tried it @excid3, works like a charm (checkout that is, haven't tried billing, but I imagine it'll be fine now as well)

**Comment by excid3** [comment]
Billing portal was already doing that properly, just Checkout that wasn't so we should be good to go there. 👍

**Comment by excid3** [comment]
Released this as 2.6.10 🚀

**Comment by doutatsu** [comment]
You are a legend @excid3 🎉 Thanks for such a prompt fix. I was considering opening a PR myself, if I haven't heard back in a few days, but I forget you are so quick to address issues 😄

**Comment by excid3** [comment]
PRs are always welcome! I'm definitely crazy busy these days so sometimes issues will fall through the cracks for a while. 😜
