### ISSUE TITLE
undefined method `payment_processor' for #<User:0x0000xxxxxxxxx>

### ISSUE THREAD

**Issue by MelvinNau** [pay-rails/pay#324]
Hi,

The function "payment_processor" is not available from my side.

My User model have "Pay::Billable" module in first, and migration are ok. What I missing ?

https://www.youtube.com/watch?v=MKWq_soCzsQ

Here is CheckoutsController, from Video and from my code:

```
class CheckoutsController < ApplicationController

  before_action :authenticate_user!

  def show
    current_user.processor = :stripe
    current_user.customer
    @checkout_session = current_user.payment_processor.checkout(
        mode: "payment",
        line_items: "price_1I1avTDKEeuuD2zw0G0jLIA9"
    )
  end

end
```

EDIT:
I update my Gemfile with: gem "pay", "~> 2.6.10"

I've another problem: cannot load such file -- pay/stripe/webhooks (LoadError)

**Comment by MelvinNau** [comment]
I check the commit log, my version gem (2.4.4) is no longuer up to date I think.
I already did "bundle update pay"

**Comment by mustafaalhayali** [comment]
the same issue seems to be present in 2.7 I had to revert to 2.6.9

**Comment by Jemma5** [comment]
Did you overcome this problem?

**Comment by sscirrus** [comment]
Try:

    current_user.set_payment_processor :stripe

**Comment by excid3** [comment]
`set_payment_processor` is new in Pay 3, but this issue was for an earlier version of Pay. Going to close since it's not longer relevant.

**Comment by shawndeprey** [comment]
I am still running into this exact issue while running `pay 3.0.21`. Neither function `processor`, `payment_processor`, `set_payment_processor`, or anything which seems should exist actually exists when including `Pay::Billable` on my user model. It's worth noting I was following the same guide as the original thread poster and got stuck at the exact same point.

@excid3 & @sscirrus & @Jemma5 & @MelvinNau were any of you able to overcome this problem?

**Comment by excid3** [comment]
Pay 3 uses `pay_customer` instead of `include Pay::Billable` now. See the docs: https://github.com/pay-rails/pay/blob/master/docs/1_installation.md#models

**Comment by KimGemRuby** [comment]
nope , i make pay_customer but always the same relevant current_user.processor = :stripe,

**Comment by x64code** [comment]
Same issue here - pay_customer produces the same error

**Comment by MeterSoft** [comment]
Some issue in version 3.0.24

**Comment by lkenyan** [comment]
Using pay 6.2.3, the method is now `current_user.set_payment_processor :stripe` (no equals sign). Hope this helps someone else.
