### ISSUE TITLE
Wondering about how webhooks will handle payment failures...

### ISSUE THREAD

**Issue by duartemvix** [pay-rails/pay#326]
As far as I've read I could understand Stripe docs and Pay's code but still a few questions remain. If a payment failure happens isn't it necessary for such a webhook like `ìnvoice.payment_failed` to exist? I've had a chance to read about the `invoice.payment_action_required` but I'm not quite sure if one could replace the other.

At this point, our integration seems to work just fine in development but I'm afraid I couldn't test anything closer to a production environment. Most payment methods used from Stripe's testing docs are pretty standard such as `pm_card_visa` and seemed to work everytime without much complication.

However, I might be missing just one more test that perhaps changes the customer's payment_method to a `pm_card_chargeDeclined` payment method and attempt to collect early on rather than on period's end. Any tips on how to proceed and get this fully automated already?

Just to be clear: I've already managed to integrate Pay to create new subscriptions but I wondered about payment failures during billing cycles rather than on subscription creation.

**Comment by excid3** [comment]
You'd listen to the `charge.failed` webhook and email your customer about the failed payment and link them back to the app to update their card and retry the payment.

Tools like Overdue.io, Profitwell, Baremetrics, etc all provide automations for this, but it'd be great to have it built in as part of this. I haven't built this yet, but I'd like to have a listener built in and send several emails until the subscription is automatically canceled.

Your subscription state should be updated to "past_due" (iirc) so you can use that to display a banner when the user is signed in to update their card.

A good way to test this is to create a test subscription that renews daily and use a card that will fail.

**Comment by duartemvix** [comment]
> You'd listen to the `charge.failed` webhook and email your customer about the failed payment and link them back to the app to update their card and retry the payment.
> 
> Tools like Overdue.io, Profitwell, Baremetrics, etc all provide automations for this, but it'd be great to have it built in as part of this. I haven't built this yet, but I'd like to have a listener built in and send several emails until the subscription is automatically canceled.
> 
> Your subscription state should be updated to "past_due" (iirc) so you can use that to display a banner when the user is signed in to update their card.
> 
> A good way to test this is to create a test subscription that renews daily and use a card that will fail.

That's right... it seems `past_due` is redudant and will give me the same logic for a payment failure. In this case, Pay already has a `subscription.updated` webhook. I should be able to get these subscriptions and their status by checking them with `.active?`

Well, it seems this question is really resolved for me then. Thank you Chris!

**Comment by excid3** [comment]
Yep, and you can just update the status manually if you want to test it out. I believe there's also `.past_due?` if you want to ask if it's specifically a past_due subscription state. In Stripe they're still considered active, but we treat them as inactive subscriptions so customers are encouraged to pay.

**Comment by clemoun** [comment]
One thing that is quite confusing though is that a `past_due` subscription will be returned in the `:active` scope but will give a `false` with the `active?` method.

Maybe the `:active` scope should be renamed `:on_going` ?

**Comment by excid3** [comment]
@clemoun open a new issue for it please

**Comment by clemoun** [comment]
Sorry, first time I ever write in Github issues (I think)
