### ISSUE TITLE
Support non integer ids in owner resource

### ISSUE THREAD

**Issue by mcansky** [pay-rails/pay#330]
As a project is using `uuid` type for all resources ids I have found that at least one process, but probably a few more in the gem, are not working happily.

The migration that creates the `pay_subscriptions` table uses an `integer` type for the `owner_id` field. Thus, when a subscription is created and the `owner_id` is written whatever value sent is forced into an integer column. This results in :
- a silent error upon create
- a more visible error on other tasks such as when a cancellation / delete is handled through the webhooks

There is a work around : change the type of the `owner_id` column to match the application needs either in the migration generated by the pay gem generators or in a subsequent migration.

I am wondering if this is just a matter of adding a few words in the documentation about this or if something a bit more automatic could be handled.

Please let me know if you have a preference on the approach and possibly a pointer or two and I will have a go at a PR.

Thanks for the gem, saving a lot of time and energy.

**Comment by excid3** [comment]
I don't know that it would be worth it to add any automated checking considering we don't know the models you're associating with. Plus it's simple enough to just edit the migrations. 

Feel free to make a PR to the docs. 👍

**Comment by mcansky** [comment]
related : https://github.com/pay-rails/pay/pull/334
