### ISSUE TITLE
Trials for stripe checkout subscriptions

### ISSUE THREAD

**Issue by simonsapiel** [pay-rails/pay#336]
I couldn't find from the docs how to set up trials for subscribing users with the checkout method? From `billable.rb` I found that 

```ruby
def checkout(**options)
    args = {
      customer: processor_id,
      payment_method_types: ["card"],
      mode: "payment",
      # These placeholder URLs will be replaced in a following step.
      success_url: options.delete(:success_url) || root_url,
      cancel_url: options.delete(:cancel_url) || root_url
    }
    
    # Line items are optional
    if (line_items = options.delete(:line_items))
      args[:line_items] = Array.wrap(line_items).map { |item|
        if item.is_a? Hash
          item
        else
          {price: item, quantity: options.fetch(:quantity, 1)}
        end
      }
end
```
doesn't contain `trial_end` or `trial_period_days` which both are parameters for the `Stripe::Subscription.create` method. Is there a way to do this currently with checkout?

Edit: Apparrenlty the `Stripe::Checkout::Session.create` method takes in a child parameter `subscription_data` for which the following would work 

```
subscription_data: {
    trial_end=1605387163
}
```

**Comment by excid3** [comment]
You can pass in any additional options you want and they'll be merged into our defaults.

```ruby
@user.checkout(subscription_data: { trial_period_days: 14 })
```

https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-subscription_data-trial_period_days
