### ISSUE TITLE
[Bug] Unable to run AddDataToPayBillable migration

### ISSUE THREAD

**Issue by doutatsu** [pay-rails/pay#342]
When I am trying to run this particular migration, I get errors:

![image](https://user-images.githubusercontent.com/4270980/119224532-bd903d80-baf6-11eb-8383-d58d4d189a24.png)

**Comment by excid3** [comment]
You're missing your `RAILS_MASTER_KEY` env var or credentials file if you're running it locally. We load the models in the migration, so that's why it might appear to be related to Pay, but it's not.

**Comment by doutatsu** [comment]
Hm, the weird thing is that I had no issue running the migrations just the other week. The only thing that changed, that I can think of, is that I used my production database dump to populate my local database 🤔  Could that be the case? I don't think I ever had the rails master key. I do have `credentials.yml.enc`, which hasn't changed

**Comment by excid3** [comment]
This new migration loads the models, so if you use credentials in them, it will load that. 

You should have a `master.key` file . If you lost it, you'll have to regenerate it unfortunately.

**Comment by doutatsu** [comment]
Hm, I am fairly certain I never had a master.key, as I don't use rails credentials, instead using `application.yml` with `figaro` gem. So I never had a need for encrypted credentials, as I don't put them into source control. 

I guess I'll have to investigate around credentials, but this is very weird behaviour as I said - nothing changed in my code, except grabbing the new gem version and running migration on the database taken from the production.

**Comment by excid3** [comment]
You have an encrypted credentials file, so you would have had a master key. They're always created together. See the Rails docs for details on that.

**Comment by doutatsu** [comment]
I've went back to look into this and something in the gem causing this error after all. I do have a `master.key` after all, which indeed was added by default, even though I don't use any credentials. So I went to dig further.

Running Pay migrations ends up running `rake db:load_config`, so I decided to take that command and see what will cause running it raise an error and what will not.

With the pay gem, I tried dropping the database (as StackOverflow did suggest running staging/production DB causes this issue) and re-create it from scratch. That didn't change anything (and running any `db:` task started to cause this error)

So I went ahead and uninstalled the gem... and lo and behold, running `rake db:load_config` or other db related tasks would not raise an error anymore. So I installed the gem again, without doing _anything_ else, and just installing the gem re-introduced this error.

So I'll have to give up on the gem for now, unfortunately, as it seems to be the cause after all, for whatever reason that is. Considering it worked before, I have tried to rollback the gem version to `2.5` but that didn't help either, so I am pretty much stuck 😞

**Comment by excid3** [comment]
Your screenshot from above shows that you're using Credentials in `config/storage.yml`. Have you commented that out you're not using it?

**Comment by doutatsu** [comment]
@excid3 It looks like it was setup with Rails, but I don't use it in anything

![image](https://user-images.githubusercontent.com/4270980/120338093-cb5e7380-c2eb-11eb-9e28-cb2439cdc2fa.png)

As mentioned before, I use [Figaro](https://github.com/laserlemon/figaro) instead

**Comment by excid3** [comment]
Your error stacktrace says it accessed it in `config/storage.yml`

**Comment by doutatsu** [comment]
This is my storage config:

```rb
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
```

I was expecting the commented out code not to trigger anything, but just in case, I have deleted the commented out code, that has credentials mentioned... which didn't fix the issue. The trace looks like this now:

```rb
➜  kenmei-api git:(features/add-pay-stripe-integration) ✗ rails db:migrate
/Users/doutatsu/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/doutatsu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/Users/doutatsu/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/doutatsu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/Users/doutatsu/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/doutatsu/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
rails aborted!
ActiveSupport::MessageEncryptor::InvalidMessage: ActiveSupport::MessageEncryptor::InvalidMessage
/Users/doutatsu/Documents/projects/kenmei-api/config/environment.rb:5:in `<main>'
/Users/doutatsu/Documents/projects/kenmei-api/bin/rails:9:in `<top (required)>'
/Users/doutatsu/Documents/projects/kenmei-api/bin/spring:15:in `<top (required)>'

Caused by:
OpenSSL::Cipher::CipherError:
/Users/doutatsu/Documents/projects/kenmei-api/config/environment.rb:5:in `<main>'
/Users/doutatsu/Documents/projects/kenmei-api/bin/rails:9:in `<top (required)>'
/Users/doutatsu/Documents/projects/kenmei-api/bin/spring:15:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

`environment.rb` just initialises the app:

```rb
# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!
```

And seeing spring mentioned, I tried disabling it as well, knowing it does cause issues at times... still no luck unfortunately. I did a search across the whole repo and nowhere I call `Rails.application.credentials`

**Comment by doutatsu** [comment]
Aaaand I've got it 😂  Looking at the trace, I noticed that the code that triggers the exception from the gem is this part:
```rb
    def find_value_by_name(scope, name)
      ENV["#{scope.upcase}_#{name.upcase}"] ||
        credentials&.dig(env, scope, name) ||
        secrets&.dig(env, scope, name) ||
        credentials&.dig(scope, name) ||
        secrets&.dig(scope, name)
    end
```

And because there was no `ENV["STRIPE_PRIVATE_KEY"]` found, it would go and try to fetch from credentials... resulting in the exception being raised. Setting the env variable fixed the issue 🎉

**Comment by doutatsu** [comment]
I guess it's not particularly a bug - you are assuming that credentials are set up correctly, as they do with new rails applications. But if someone has them broken like me, you end up in this situation. 

Not sure if you can highlight it somehow in the read me -> making sure stripe keys are setup, before running anything would make sure this error doesn't happen. But on the other, I imagine anyone would want to make sure their credentials setup is valid, even if they are not using them 🤔

**Comment by doutatsu** [comment]
I went ahead and regenerated credentials and master.key, as I am not using it anyways. This has fixed the issue, even if I remove the key from `ENV`. Which is what you suggested from the start. 

Sorry about the trouble, at least this was educational for me, to get a better understanding as to why _exactly_ pay gem specifically was breaking the app for me

**Comment by excid3** [comment]
Ah ha! Try one more thing for me real quick. If you're not using credentials, delete `config/credentials.yml.enc` `config/master.key` and the `config/credentials/` folder. Then I think Rails will not attempt to load the credentials and that should fix your issue as well.

I just did that on an app to test and it just returns nil when there are no credentials. 

```
Rails.application.credentials.dig("test")
#=> nil
```

Since yours was partially there, it tried to decrypt causing that problem.

**Comment by doutatsu** [comment]
@excid3 Yup just tried that -> That also results in no errors whatsoever! Going to leave it deleted, as I think it'll avoid issues like these

**Comment by excid3** [comment]
Great! I think I may add a rescue and a friendly error message. You're not the only one to run into that I'm sure. Credentials have confused a lot of people!

**Comment by doutatsu** [comment]
Thanks for that! I could have done a better job at investigating this, sorry for blaming the gem for my misconfiguration 😓  Been trying to integrate with Stripe for weeks now, so got quite frustrated, after getting so excited to discover pay and then end up not being able to use it 😭
