### ISSUE TITLE
NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x0000...>

### ISSUE THREAD

**Issue by ricardobucho** [pay-rails/pay#343]
Hey everyone.

After running a `bundle update` it seems there's some sort of error with a `store_accessor_for`.

I've looked around for a while but I don't have enough experience with this accessors to be sure of what I am doing, hopefully someone here can provide some insight.

Just for context, what I am doing is using **Stripe** and trying to fetch the **customer** of the billable model which is **User**. Everything worked before the update.

I've already tried fully restarting the server, including stopping spring.

```ruby
# Running
user = User.first
user.processor = :stripe

user.customer # this outputs the below
user.stripe_account # doing this directly also outputs the below

# Outputs
=begin
  NoMethodError: undefined method `accessor' for #<ActiveModel::Type::Value:0x00007fae9c58a370 @precision=nil, @scale=nil, @limit=nil>
  from /Users/ricardo/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/store.rb:217:in `store_accessor_for'
=end
```

---

Versions
```ruby
ruby '3.0.1'

gem 'rails', '~> 6.1.1'
gem 'pay', '~> 2.7'
gem 'stripe', '< 6.0', '>= 2.8'
```

---

I believe the issue is related to `store_accessor :pay_data, :stripe_account` on `lib/pay/stripe/billable.rb:30` somehow, but like I said, not sure what's going on here 😢 

Any help is appreciated, thanks!!

**Comment by excid3** [comment]
Sounds like you haven't run the new migrations. Do that to add the pay data column to your billable models.

**Comment by ricardobucho** [comment]
Yep that was it, I actually looked around for so long and forgot to look at the most obvious thing.
Thanks a lot for the help, it's working properly now!
