### ISSUE TITLE
Creating Billable model after Pay migrations will fail

### ISSUE THREAD

**Issue by doutatsu** [pay-rails/pay#349]
Possibly something to highlight in the docs, but if you are creating a new table to make `billable`, there will be a failure during the migration process, like this:

`PG::UndefinedTable: ERROR:  relation "payment_accounts" does not exist` which is caused by this migration:

```rb
  def change
    # Load all the billable models
    Rails.application.eager_load!

    Pay.billable_models.each do |model|
      add_column model.table_name, :pay_data, data_column_type
    end
  end
```

Hence, the billable table needs to be created _before_ these migrations are run, to make sure it works.

**Comment by excid3** [comment]
We probably need to drop this migration in a future version. This was added for compatibility for older migrations that didn't have the `pay_data` column.

The `rails g pay:billable User` generator adds the `pay_data` column now automatically.
