### ISSUE TITLE
Is there any way to add reference to `pay_charges` table?

### ISSUE THREAD

**Issue by the-anthony-s** [pay-rails/pay#351]
I am trying to figure out if there is any way to use Stripe Checkout with products. In my case, I have X amount of products (to be specific, I want to give access to the page after the purchase) that have the same price. When the user buys a product, I want to associate this charge with the `pay_charges` table to validate if the user bought specifically this product.

On the Stripe side, I want to create a single product and use it for all products that I have on the website.

Also, I am not sure if I configured everything correctly. Still, the Stripe Checkout don't remember the user's credit card information on checkouts (non-subscription payments), and none of these charges is visible in Stripe Portal.

**Comment by excid3** [comment]
You can customize the charge model by following this: https://github.com/pay-rails/pay#customizing-pay-models

**Comment by the-anthony-s** [comment]
I am sorry, @excid3 , my mistake. I didn't read the `README` well enough.
