### ISSUE TITLE
Stripe connect merchant_processor

### ISSUE THREAD

**Issue by simonsapiel** [pay-rails/pay#355]
I ran to an error while trying to use stripe connect with pay. It seems that the migrations doesn't include `merchant_processor`? Which in truns returns 

`NameError (undefined local variable or method 'merchant_processor' for #<User:0x0000560738d07420>)`

when following the docs and running `user.merchant.create_account`.

**Comment by mustafaalhayali** [comment]
seeing a similar issue when I create a stripe `customer`.
`undefined method `accessor' for #<ActiveModel::Type::Value:0x000055639a97cab8 @precision=nil, @scale=nil, @limit=nil>`

**Comment by excid3** [comment]
@mustafaalhayali that's unrelated. See https://github.com/pay-rails/pay/issues/343

@simonsapiel yeah we haven't added a generator yet. I think we'll do something like `rails g pay:merchant Account` like Devise does to add the merchant field(s) to a model.

**Comment by excid3** [comment]
Added `rails g pay:merchant ModelName` to generate those. 👍

**Comment by excid3** [comment]
And merged!
