### ISSUE TITLE
undefined local variable or method `table_name' when running merchant generator

### ISSUE THREAD

**Issue by simonsapiel** [pay-rails/pay#357]
Getting error with the new merchant generator when running the migrations. Is this a bug? 

```
undefined local variable or method `table_name' for #<AddPayMerchantToUsers:0x000055e4eeb22cc0>
```
It seems to generate the following migration

```
# frozen_string_literal: true

class AddPayMerchantToUsers < ActiveRecord::Migration[6.1]
  def change
    add_column table_name, :merchant_processor, :string

    # We may already have the pay_data column if a Pay::Billable object is also a Pay::Merchant
    unless ActiveRecord::Base.connection.column_exists?(table_name, :pay_data)
      add_column table_name, :pay_data, Pay::Adapter.json_column_type
    end
  end
end
```
should `table_name` be `:users` in the case when you're running `rails g pay:merchant User`? Also it isn't quite clear from the docs if I should run both `rails g pay:merchant User` and `bin/rails g pay:billable User` in order to set up stripe connect?

**Comment by excid3** [comment]
Sorry, that was a typo. Missing the erb tags in the template to actually execute it during the generator.
