### ISSUE TITLE
Error running migrations to add Pay to the User Model

### ISSUE THREAD

**Issue by paulsizer** [pay-rails/pay#359]
Running the below migration worked fine.

```
pay:install:migrations
```

After this I tried to run the below migration but it failed.

```
rails g pay:billable User
```

This is the error I got.

```
Running via Spring preloader in process 5159
Could not find generator 'pay:billable'. 
Run `bin/rails generate --help` for more options.
```

Any thoughts on what I am doing wrong here?

**Comment by excid3** [comment]
That `pay:billable` generator is only in master at the moment. Haven't released it yet.

**Comment by paulsizer** [comment]
Shall I just create my own migration at the minute with the contents of billable_migration.rb in templates? Or is there more to it to get this working?

**Comment by excid3** [comment]
You can use the gem from master.

**Comment by crivotz** [comment]
`gem 'pay', git: 'https://github.com/pay-rails/pay', branch: 'master'`

**Comment by paulsizer** [comment]
@excid3 Hi Chris this worked using the gem from github latest below:

`gem 'pay', git: 'https://github.com/pay-rails/pay.git'`

Unfortunately when trying to add a subscription to the user

`@user.subscribe(plan: @user.plan)`

It fails with the following error:

undefined method `accessor' for #<ActiveModel::Type::Value:0x00007f8a273cfb78>

Looking through other issues #343  it seems to be an issue with the the pay_data column. It doesn't look like its added pay_data column with the billable migration.

`rails g pay:billable User`

**Comment by excid3** [comment]
Yeah, looks like I forgot that in the pay:billable migration.

You can add this migration for now:
https://github.com/pay-rails/pay/blob/master/db/migrate/20210309004259_add_data_to_pay_billable.rb
