### ISSUE TITLE
Multi tenancy via the initializer

### ISSUE THREAD

**Issue by dvodvo** [pay-rails/pay#362]
The readMe indicates some changes can be effected via an initializer.
```
Pay.setup do |config|

  # For use in the receipt/refund/renewal mailers
  config.business_name = "Business Name"
  config.business_address = "1600 Pennsylvania Avenue NW"
  config.application_name = "My App"
  config.support_email = "helpme@example.com"

  config.send_emails = true
[...]
```
I would surmise that this would be the perfect place to handle multi-tenancy. for example,

config.public_key = @shop.public_key
config.private_key = @shop.private_key
config.signing_secret = @shop.signing_secret

Is this doable at the present time?

**Comment by excid3** [comment]
Pay only supports Stripe Connect so the keys will always be your Stripe account keys and you will pass in the Stripe Account to charge a customer another Stripe account.
