### ISSUE TITLE
undefined method `accessor' for #<ActiveModel::Type::Value:0x00007fc80fd83c98>

### ISSUE THREAD

**Issue by gareth326771** [pay-rails/pay#365]
Hello,

Trying to add Billable to a model other than User and have hit an issue.

By default the Pay::Charge is associated with the User model but we want to associate them with a Campaigns model instead.

```
Have followed the instructions on the Pay gem read.me as follows:

We also need to run migrations to add Pay to the User, Account, Team, etc models that we want to make payments in our app.

bin/rails g pay:billable User

This will generate a migration to add Pay fields to our User model and automatically includes the Pay::Billable module in our User model. Repeat this for all the models you want to make payments in your app.

Note: An email attribute or method on your Billable model is required.

To sync customer names, your Billable model should respond to the first_name and last_name methods. Pay will sync these over to your Customer objects in Stripe and Braintree.
```

However when trying to create a Stripe customer to make a checkout_session I get the following error while calling the .customer method on my Campaigns model:

`undefined method `accessor' for #<ActiveModel::Type::Value:0x00007f91af51c7d0>`

Have tried putting email methods in the LocalCampaign model and adding email as attributes.

It seems the issue is in lib/pay/stripe/billable.rb customer method:

```
      def customer
        stripe_customer = if processor_id?
          ::Stripe::Customer.retrieve(processor_id, {stripe_account: stripe_account})
        else
          sc = ::Stripe::Customer.create({email: email, name: customer_name}, {stripe_account: stripe_account})
          billable.update(processor: :stripe, processor_id: sc.id, stripe_account: stripe_account)
          sc
        end
```

There does not seems to be a stripe_account and that is what is causing the error?

**Comment by excid3** [comment]
Try using master. I think it's fixed but hasn't been released yet.

**Comment by gareth326771** [comment]
Thanks Chris.

The problem I had was I had followed the instructions and run the migrations BEFORE adding Billable module to the Campaign model (I had run originally with the User model and gone back and added it in).

Hopefully this helps anyone that may have done the same.

**Comment by excid3** [comment]
Ah yeah. I'm in the process of cleaning that stuff up so it's simpler. I think we may even go as far as adding a Pay::Customer and Pay::Merchant model so you don't have to add columns to your models ActiveStorage / ActionText style.

**Comment by gareth326771** [comment]
Sounds great - the gem already takes away a lot of complexity but I was following the video on Stripe Checkout where you do it only for the User model so had run the migrations already...

Then went back and tried to add the `include Pay::Billable` in my Campaigns model but obviously you need the pay_data column in there so need to run the migrations again or at least `add_column model.table_name, :pay_data, Pay::Adapter.json_column_type`.

Thanks again for the help.

**Comment by archonic** [comment]
I hit this issue just updating from master 302f260 to master c66fc90. The current master is still getting this error.
