### ISSUE TITLE
scary race condition in stripe webhooks

### ISSUE THREAD

**Issue by osheroff** [pay-rails/pay#371]
I've only encountered this in development mode, but it appears that stripe has made their webhooks usability even worse these days by now firing off three events (in my case, `payment_intent.succeeded`, `charge.succeeded`, and `invoice.paid`) in parallel.  Since we aren't enforcing any uniqueness constraints, these three webhooks calls raced against each other, and I ended up with 3 identical subscription rows in the DB.  

Any ideas on how to fix?  a unique index on (`processor`, `processor_id`) in subscriptions might fix this case but I'm not sure how it would ripple out to the system.

Other than that we could do some transaction select-for-update stuff.  maybe.

**Comment by excid3** [comment]
That's a great question. We do need a uniqueness validation probably on both the Pay::Charge and Pay::Subscription models.

I recently changed the webhooks to simply trigger a sync. Sometimes the webhooks come in out of order, so occasionally it would update a record like a Subscription with old state. Now the webhooks just trigger an API request to get the latest information every time.

The uniqueness validation should take care of creating duplicates, but it might be a good idea to lock the record as well for updates.

Think that would handle most situations?

**Comment by osheroff** [comment]
not clear, are you talking about doing a rails uniqueness validation or a db-level constraint?  
seems likely that doing it as just a rails validation would just be subject to the same race condition.

I've never been clear in my mind how locking a yet-to-be-inserted record works.  does AR have some kind of pattern?

**Comment by excid3** [comment]
Both, for sure. The database level constraint will be the only reliable way to handle that, and the Rails validation can just help a bit.

I don't think you can lock a yet-to-be-inserted record. But locking the row would be useful for updating subscription state.

**Comment by osheroff** [comment]
yeah @excid3 that all sounds good.  You want to do the code changes or me?

**Comment by excid3** [comment]
I leave for vacation tomorrow, so if you've got time, that would be awesome. 👍

**Comment by osheroff** [comment]
hah i leave for vacation tomorrow too.

**Comment by excid3** [comment]
LOL, hilarious timing. I may take a quick stab at it today if I get some free time.

**Comment by excid3** [comment]
@osheroff I'm back from vacation and was poking at this again. I merged without the retry but was playing with that too.

Does this make sense for retries?

```ruby
      def self.sync(charge_id, object: nil, try: 0, retries: 5)
        object ||= ::Stripe::Charge.retrieve(id: charge_id)
        owner = Pay.find_billable(processor: :stripe, processor_id: object.customer)
        return unless owner

        attrs = {
          amount: object.amount,
          amount_refunded: object.amount_refunded,
          application_fee_amount: object.application_fee_amount,
          card_exp_month: object.payment_method_details.card.exp_month,
          card_exp_year: object.payment_method_details.card.exp_year,
          card_last4: object.payment_method_details.card.last4,
          card_type: object.payment_method_details.card.brand,
          created_at: Time.at(object.created),
          currency: object.currency,
          stripe_account: owner.stripe_account
        }

        # Associate charge with subscription if we can
        if object.invoice
          invoice = (object.invoice.is_a?(::Stripe::Invoice) ? object.invoice : ::Stripe::Invoice.retrieve(object.invoice))
          attrs[:subscription] = Pay::Subscription.find_by(processor: :stripe, processor_id: invoice.subscription)
        end

        # Update or create the charge
        processor_details = {processor: :stripe, processor_id: object.id}
        if (pay_charge = owner.charges.find_by(processor_details))
          pay_charge.with_lock do
            pay_charge.update!(attrs)
          end
        else
          owner.charges.create!(attrs.merge(processor_details))
        end
      rescue ActiveRecord::RecordInvalid
        try += 1
        if try <= retries
          sleep 0.1
          retry
        else
          raise
        end
      end
```

Which means
* If creating the record fails, we retry it
* This causes a new query to the database which should find the existing record this time which was created by a different thread
* When we have the record, we lock and update
* If this failed several times, we re-raise the `ActiveRecord::InvalidRecord` error (I'm not sure this can even happen?)

**Comment by osheroff** [comment]
- it's a pity there isn't anything more specific than `RecordInvalid` to catch here.   There's https://github.com/Shopify/activerecord-rescue_from_duplicate (and back at Zendesk we had put in a similar patch) but I don't imagine we want to take on that dependency...
- I think only one retry makes any real sense -- the call to `create!` may race exactly once but the second time through the code it should definitely be there... I think...

**Comment by excid3** [comment]
* I'd rather not add the dependency, but if this solution doesn't work well, that's not a bad option.
* I agree, I'll update that to only one retry makes sense. The database will let one record get created, and the lock will handle the retries safely. (at least I hope!)

**Comment by excid3** [comment]
@osheroff have you had a chance to use this / notice any issues?

**Comment by osheroff** [comment]
@excid3 no, sadly have been transitioning pastures so I probably won't have the opportunity to futz with this.

**Comment by excid3** [comment]
No worries!

**Comment by excid3** [comment]
This should be resolved now in Pay 3 by using database uniqueness constraints and updating with row locks.
