### ISSUE TITLE
`user.subscribe` does not create a charge

### ISSUE THREAD

**Issue by A7madXatab** [pay-rails/pay#380]
When creating a subscription through stripe, stripe bills the customer right away, but pay does not create a corresponding subscription, is the the desired behaviour?

Thanks.

**Comment by excid3** [comment]
You must listen to webhooks in development using the stripe Cli. Check the documentation for details. 👍

**Comment by A7madXatab** [comment]
Great!. sorry i missed that!

**Comment by A7madXatab** [comment]
Can we override the controllers that `pay` provides? in my case. a charge `belongs_to: :transaction` which is an internal ledger that we use. can i override the controller for pay?

**Comment by excid3** [comment]
You can include a module in the Pay::Charge class to add functionality to it:

```
# config/initializer/pay.rb

module PayChargeExtension
  extend ActiveSupport::Concern
end

Rails.configuration.to_prepare do
  Pay::Charge.include PayChargeExtension
end
```
