### ISSUE TITLE
Overriding webhooks?

### ISSUE THREAD

**Issue by A7madXatab** [pay-rails/pay#389]
Hi, 

So, in my case a `Pay::Subscription` and `Pay::Charge` have some extra association that needs to be set when the webhooks gets called, my question is how can i override/extend the current webhooks and my code to them, is that possible?

**Comment by excid3** [comment]
I want to add a callback to Pay so that we can have a single place for processing charges after they're successful. SCA makes this a bit tough, but for now, you would want to override the webhook class.

```ruby
# config/initializers/pay.rb

# Monkey patch the charge succeeded webhook to associate charge with record.
module Pay
  module Stripe
    module Webhooks
      class ChargeSucceeded
        def call(event)
          pay_charge = Pay::Stripe::Charge.sync(event.data.object.id)

          # Add your code here

          notify_user(pay_charge.owner, pay_charge) if pay_charge
        end
      end
    end
  end
end
```
