### ISSUE TITLE
undefined method `amount' for #<Stripe::SetupIntent

### ISSUE THREAD

**Issue by guillaumebriday** [pay-rails/pay#400]
When a user is on trial and use a authentication required card like `4000 0027 6000 3184`, I have this error on [this page](https://github.com/pay-rails/pay/blob/master/app/views/pay/payments/show.html.erb#L34). I don't have it when the user trial ended.

I suppose it's because of [this delegate](https://github.com/pay-rails/pay/blob/master/lib/pay/payment.rb#L5) and this class that does not have an amount attribute.

```ruby
::Stripe::SetupIntent.retrieve(id)
```

My id actually starts with `seti_`.

I have no idea how to fix or improve that. I wish I could. 

Do you have any idea?

Thanks @excid3

**Comment by excid3** [comment]
PaymentIntents are for a specific amount and that's what that `payment_path` is used for. SetupIntents are used when signing up for a trial or saving a card for future use. 

We should probably update that page so it can work with SetupIntents. Also that page uses Vue.js that I'd like to replace with Stimulus.

**Comment by excid3** [comment]
Actually, ignore all that.  We fixed the trial / setup intent issue in 420db918142374f5ba051d3dc5a1fb1eb0e3218c

I should cut this as a new release.

I think we'll keep the payment page only for validating PaymentIntents.

**Comment by excid3** [comment]
Released 2.7.2 with the trial setup intent validation fix. 🔥
