### ISSUE TITLE
Checkout sessions not saving payment_method_token

### ISSUE THREAD

**Issue by simonsapiel** [pay-rails/pay#411]
Currently it seems that the checkout sessions are not saving the payment_method_token at least while in `setup` mode.

Running the following

```ruby
current_user.set_payment_processor :stripe
current_user.payment_processor.customer
@checkout_session = current_user.payment_processor.checkout(mode: "setup", payment_method_types: ['sepa_debit'])
```

will correctly setup the stripe customer with the appropriate payment_method, but it doesn't get stored in the `Pay::Customer` record. 

Is there a way to handle this somehow currently? This in turn will result in an error immediately when you try to charge this customer from Pay.

**Comment by simonsapiel** [comment]
Isn't it still getting migrated by https://github.com/pay-rails/pay/blob/master/db/migrate/20170727235816_create_pay_charges.rb#L6 this?

**Comment by simonsapiel** [comment]
Adding 

```ruby
# Drop unneeded columns
    remove_column :pay_charges, :owner_type
    remove_column :pay_charges, :owner_id
    remove_column :pay_charges, :processor
    remove_column :pay_charges, :card_type
    remove_column :pay_charges, :card_last4
    remove_column :pay_charges, :card_exp_month
    remove_column :pay_charges, :card_exp_year
    remove_column :pay_subscriptions, :owner_type
    remove_column :pay_subscriptions, :owner_id
    remove_column :pay_subscriptions, :processor
```
from the upgrade quides (https://github.com/pay-rails/pay/blob/master/UPGRADE.md) `UpgradeToPayVersion3` migration to the original `CreatePayV3Models` does the trick.

**Comment by excid3** [comment]
It needs to be backwards compatible, so you can't just ignore the old migrations. Kinda tricky.

**Comment by simonsapiel** [comment]
Yeah I guess that would do it. As of now, if you run the current `UpgradeToPayVersion3` against the migrations defined in master it will throw an error since the user model doesn't contain a processor column (it did in V2?). Assuming you're running the `UpgradeToPayVersion3` only against `MODELS = [User]`.

```ruby
PG::UndefinedColumn: ERROR:  column users.processor does not exist
LINE 1: SELECT "users".* FROM "users" WHERE "users"."processor" IS N...
```
