### ISSUE TITLE
Should we update to default to action_controller.default_url_options?

### ISSUE THREAD

**Issue by afomera** [pay-rails/pay#422]
We noticed while pairing that we were defaulting to action_mailer.default_url_options in this location: https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/billable.rb#L17-L19

Should this be updated to use `action_controller.default_url_options` in addition / instead?

**Comment by excid3** [comment]
What benefit do we get using the `action_controller` options? I can't remember.

I used mailers because I assumed you're most likely to have that configured.
