### ISSUE TITLE
Coupons and Promotion Codes

### ISSUE THREAD

**Issue by excid3** [pay-rails/pay#423]
At the very least, we should store these on the Pay::Subscription records if they were applied.

I'd like to avoid adding too many models, so if we can get by without adding a coupon model, that would be nice.

Hard part will be supporting Braintree and Paddle coupons in a consistent fashion.

**Comment by adrianthedev** [comment]
I couldn't find any way to apply coupons to subscriptions using `pay`. Is there a recommended way, or at least "this is how I hacked it" way?

I'm also using Jumpstart BTW.

**Comment by adrianthedev** [comment]
To be more clear, I'd like to give the customer the option to apply the discount before starting a subscription, so he can have the discounted price as his first subscription payment.

Ex: I sell a $100 subscription and the customer does not have one yet, if I give him a 10% discount code, he'd pay $90 for his first invoice and $100 for the next one.

**Comment by excid3** [comment]
You can pass them in as arguments to the subscription. Check the stripe API docs, we just pass them along currently.

**Comment by excid3** [comment]
Correct! 

I'm going to probably add support for this soon because I also need to add some stripe tax support so it'll be good to tackle together.

**Comment by excid3** [comment]
Discounts and Tax rates are now recorded in the `Pay::Charge` model, so I'm going to close this. 

Will be updating Jumpstart Pro at some point soon to add a field for Promo Code on the checkout page.
