### ISSUE TITLE
2.x branch

### ISSUE THREAD

**Issue by guillaumebriday** [pay-rails/pay#433]
Hey

Could you create a 2.x branch that points to https://github.com/pay-rails/pay/tree/v2.7.2 so we could submit fix for 2.x version? Until we move to 3.x

For instance, [on this line](https://github.com/pay-rails/pay/blob/v2.7.2/app/models/pay/subscription.rb#L27), I would like to add:

```ruby
where(status: %w[trialing active])
```

Thanks

**Comment by excid3** [comment]
Done 👍

**Comment by guillaumebriday** [comment]
Awesome, thanks!
