### ISSUE TITLE
Question regarding Subscription Receipt Emails Not Sending for New Subscriptions

### ISSUE THREAD

**Issue by k2director** [pay-rails/pay#434]
Question! Is Pay supposed to send its receipt.html.erb email when a user first subscribes to a subscription, OR just when an existing subscription is charged subsequent months?

I ask because my app has created many test Stripe Checkout subscriptions for new users in the last week, but Pay has never generated an email when payment is successfully received for the new subscription (even though my app via the Stripe CLI in Development is getting the web hook notifications from Stripe that a customer has been created, a charge succeeded, a checkout session completed, invoice created/finalized/paid, and subscription created/updated). 

At first I thought I had a problem with sending emails altogether, but yesterday noticed that my app DID indeed send out a "Your upcoming subscription renewal" email over the weekend for a user subscription I had created a few weeks ago. Looking at my logs, I see Stripe sent a post, and Pay picked it up and launched an email job, which delivered the email.

So I guess emails are working, but I'm still not getting an email when an unsubscribed user successfully subscribes for the first time, and so it occurred to me that maybe that's not what that receipt.html.erb email is supposed to be doing? Maybe it's just supposed to send on monthly renewals? 

Thanks much!

**Comment by excid3** [comment]
Receipts are sent when the `charge.succeeded` webhook is received. If you're not running the Stripe CLI to forward webhooks, you won't have any emails sent.

```bash
stripe listen --forward-to localhost:3000/pay/webhooks/stripe
```

I don't see that in the new docs, but I'll make sure to add that.

**Comment by excid3** [comment]
Added notes to the docs.

The Stripe CLI is required for getting the full experience of Pay in development with Stripe, but I did my best so the basics would work with out as best we can.

**Comment by excid3** [comment]
Also! Forgot to mention, webhooks are now processed by background jobs so make sure your background workers are being processed.

Sounds like you're receiving the webhooks with the CLI, so that would be the next place to check.

**Comment by k2director** [comment]
Thanks for the quick response(s) Chris! Hmmmm, so yes, my Stripe CLI is definitely getting the 'charge.succeeded' notification: 
2021-09-13 10:56:35   --> charge.succeeded [evt_3JZJOPJWQDOuraVy0dY1smzs]

And my email jobs are working because Pay is successfully sending out the "Your upcoming subscription renewal" emails, when it gets "invoice.upcoming" notifications from Stripe. For instance, this Webhook coming into the Stripe CLI produces the following Sidekiq job: 

Webhook:
2021-09-13 13:08:28   --> invoice.upcoming [evt_1JZLS3JWQDOuraVyI6ZkLa0u]
2021-09-13 13:08:28  <--  [200] POST http://localhost:3000/pay/webhooks/stripe/ [evt_1JZLS3JWQDOuraVyI6ZkLa0u]

Resulting Job: 
[ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 0b430bc3-8c01-4663-a6c7-7bb6811a37a7) to Sidekiq(mailers) with arguments: "Pay::UserMailer", "subscription_renewing", "deliver_now", {:params=>{:billable=>#<GlobalID:0x00007f9b64477f78 @uri=#<URI::GID gid://invoices/User/19>>, :subscription=>#<GlobalID:0x00007f9b64477488 @uri=#<URI::GID gid://invoices/Pay::Subscription/3>>, :date=>Mon, 20 Sep 2021 14:06:46.000000000 PDT -07:00}, :args=>[]}

So if my background email jobs are being triggered properly for some Webhook events (invoice.upcoming), but not other events (charge.succeeded), do you think it could still be a background job issue? 

By the way, I'm using the Pay version right before the 3.0 update...

**Comment by excid3** [comment]
Ah you're not on Pay 3. Got it. That version wouldn't create a job for the mailer.

Here's the webhook processor:
https://github.com/pay-rails/pay/blob/2.x/lib/pay/stripe/webhooks/charge_succeeded.rb#L11

It will only send an email if you have the receipts gem in your app. Maybe that's why?

**Comment by k2director** [comment]
Ah, ok, I think that's it! I do not have the Receipts gem. I will look into that! And also, I'm going to look at the upgrade to 3.0 as soon as I get a few more things done! But thanks for clearing this up, nothing is wrong, I just got confused about what the behavior to expect...

**Comment by excid3** [comment]
Yep! And that's a good point you bring up though. We can still send receipt emails, but we could leave out the PDF attachments if the receipts gem was not there.

**Comment by excid3** [comment]
Fixed Stripe so it will send receipt emails if receipts is not in the Gemfile. 👍
