### ISSUE TITLE
NoMethodError `extra_billing_info?' in Pay::UserMailer#receipt

### ISSUE THREAD

**Issue by pbmarcano** [pay-rails/pay#439]
I went through the setup and configuration without any hitches but once it was time for the `Pay::UserMailer#receipt` to be sent out I got a `NoMethodError: undefined method 'extra_billing_info?' for [User Object]`.

I don't see the migration that adds `extra_billing_info` in the Pay 3.0 [CreatePayTables](https://github.com/pay-rails/pay/blob/dab8f65fbcd32537a15cc02c87e0920800ee5d02/db/migrate/1_create_pay_tables.rb) but I see it in the [billable_migration](https://github.com/pay-rails/pay/blob/dab8f65fbcd32537a15cc02c87e0920800ee5d02/lib/generators/active_record/templates/billable_migration.rb)

From what I can tell this method is only referenced in the `#receipt` and `#refund` mailer views.

Not sure if this is something that we're missing from a migration in pay 3.0 or if this is is something from a previous version that needs to be removed from views.

Thanks.

**Comment by ronakabhattrz** [comment]
Hey, @pbmarcano I got the same issue, and even when I try to override the mailer view then it keeps taking the existing one, not a custom one.

**Comment by excid3** [comment]
We used to add that model to your User / Account / Team model so we can include VAT or other details in receipts.

That's now an _optional_ column you can put on your model and we'll include it in the receipts.

I'll update the email so doesn't raise an error if the column doesn't exist. 👍

**Comment by pbmarcano** [comment]
Thanks @excid3.

And yes @ronakabhattrz, I noticed that too, I couldn't override the views.

**Comment by excid3** [comment]
Pushed up a fix for the `extra_billing_info`

Email views work fine for me. I ran `rails g pay:email_views` and modified the receipts email to only render `HELLO WORLD`

Confirmed it works:

```ruby
irb(#<UserMailerTest:0x00007fc52c15f830>):004:0> email.parts.first.to_s
=> "Content-Type: text/html;\r\n charset=UTF-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n    <style>\r\n      /* Email styles need to be inline */\r\n    </style>\r\n  </head>\r\n\r\n  <body>\r\n    HELLO WORLD\r\n\r\n  </body>\r\n</html>\r\n"
```

**Comment by excid3** [comment]
Pushed a new release for this fix. 👍

**Comment by ronakabhattrz** [comment]
Thanks, @excid3.

**Comment by ronakabhattrz** [comment]
@excid3 @pbmarcano
it's working fine I just check so I closed this issue.

**Comment by pbmarcano** [comment]
My errors are gone! I am not getting any emails in letter_opener, but I think it's unrelated...

Thanks, @excid3!
