### ISSUE TITLE
NoMethodError: undefined method `update_customer!' for [Pay::Customer object]

### ISSUE THREAD

**Issue by pbmarcano** [pay-rails/pay#440]
Getting a NoMethodError on the Pay::CustomerSyncJob. [Line 6](https://github.com/pay-rails/pay/blob/dccb2a29815183e164df951aa54900c087ea97f5/app/jobs/pay/customer_sync_job.rb#L6) calls `#update_customer!` on the Pay::Customer object:

```ruby
module Pay
  class CustomerSyncJob < ApplicationJob
    queue_as :default

    def perform(pay_customer_id)
      Pay::Customer.find(pay_customer_id).update_customer!
    rescue ActiveRecord::RecordNotFound
      Rails.logger.info "Couldn't find a #{class_name} with ID = #{id}"
    end
  end
end
```

Yet `#update_customer!` is not defined [on the model](https://github.com/pay-rails/pay/blob/dab8f65fbcd32537a15cc02c87e0920800ee5d02/app/models/pay/customer.rb).

**Comment by pbmarcano** [comment]
I also just caught a `NameError` on `class_name`.

**Comment by excid3** [comment]
Oops, yep. Forgot all about that.

**Comment by excid3** [comment]
@pbmarcano got time to try #441 for me?

**Comment by pbmarcano** [comment]
No errors! But not syncing the first & last name either...

**Comment by excid3** [comment]
It only re-syncs the name if email changed.

**Comment by pbmarcano** [comment]
Got it. Then it's working great haha!
