### ISSUE TITLE
undefined method `set_payment_processor' for #<User:0x00007f8c3891bcb8>

### ISSUE THREAD

**Issue by shawndeprey** [pay-rails/pay#450]
This issue is related to #324 

In setting up pay & stripe I ran into a very similar issue to the above thread while following the [same guide](https://www.youtube.com/watch?v=MKWq_soCzsQ) as that thread. After much digging into the suggested solution on that thread, I believe I've at least found the issue though I don't know if there's a good solution to it.

## The Issue
After setting up my local environment per the instructions on the above video, I ran into the following error after trying to run the `set_payment_processor` function on the user model. Note, this is with `include Pay::Billable` on the `User` model.

```bash
irb(main):001:0> User.first.set_payment_processor :stripe
D, [2021-10-02T21:51:22.827900 #67] DEBUG -- :   User Load (0.9ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `set_payment_processor' for #<User:0x00007f8c3891bcb8>)
```

I did some digging into the [Pay::Billable](https://github.com/pay-rails/pay/blob/52a1b082ffa0aff3ba4dd79c200c940b7958bd0f/lib/pay/billable/sync_customer.rb) module and found that the module doesn't actually have any of those methods. The module which does seem to have all of the necessary relations and methods is [Pay::Attributes::CustomerExtension](https://github.com/pay-rails/pay/blob/52a1b082ffa0aff3ba4dd79c200c940b7958bd0f/lib/pay/attributes.rb#L25). Unless I am mistaken, it would seem like since the publishing of the video guide above, the proper module to include on User models is no longer `Pay::Billable` but instead `Pay::Attributes::CustomerExtension`. As shown below, the usage of this module on the User model seems to produce the results that Pay::Billable is supposed to, however, I can't find anywhere in the setup documentation that this is the correct module to use on the User model so in all honestly this potentially seems like a bug to me. [These docs](https://github.com/pay-rails/pay/blob/master/docs/3_customers.md) were linked as the resolution for this error on the previous thread, but since I can't confirm which module is supposed to be included on User models via the docs I am creating this issue.

```bash
irb(main):003:0> user.set_payment_processor :stripe
D, [2021-10-02T21:47:53.758208 #53] DEBUG -- :    (0.3ms)  BEGIN
D, [2021-10-02T21:47:53.766998 #53] DEBUG -- :   Pay::Customer Update All (0.9ms)  UPDATE "pay_customers" SET "default" = $1 WHERE "pay_customers"."owner_id" = $2 AND "pay_customers"."owner_type" = $3  [["default", false], ["owner_id", 1], ["owner_type", "User"]]
D, [2021-10-02T21:47:53.768796 #53] DEBUG -- :   Pay::Customer Load (0.4ms)  SELECT "pay_customers".* FROM "pay_customers" WHERE "pay_customers"."owner_id" = $1 AND "pay_customers"."owner_type" = $2 AND "pay_customers"."deleted_at" IS NULL AND "pay_customers"."processor" = $3 ORDER BY "pay_customers"."id" ASC LIMIT $4  [["owner_id", 1], ["owner_type", "User"], ["processor", "stripe"], ["LIMIT", 1]]
D, [2021-10-02T21:47:53.792391 #53] DEBUG -- :   Pay::Customer Create (1.0ms)  INSERT INTO "pay_customers" ("owner_type", "owner_id", "processor", "default", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["owner_type", "User"], ["owner_id", 1], ["processor", "stripe"], ["default", true], ["created_at", "2021-10-02 21:47:53.790564"], ["updated_at", "2021-10-02 21:47:53.790564"]]
D, [2021-10-02T21:47:53.793670 #53] DEBUG -- :    (0.8ms)  COMMIT
D, [2021-10-02T21:47:53.797938 #53] DEBUG -- :   Pay::Customer Load (0.4ms)  SELECT "pay_customers".* FROM "pay_customers" WHERE "pay_customers"."owner_id" = $1 AND "pay_customers"."owner_type" = $2 AND "pay_customers"."default" = $3 AND "pay_customers"."deleted_at" IS NULL LIMIT $4  [["owner_id", 1], ["owner_type", "User"], ["default", true], ["LIMIT", 1]]
=> #<Pay::Customer id: 1, owner_type: "User", owner_id: 1, processor: "stripe", processor_id: nil, default: true, data: nil, deleted_at: nil, created_at: "2021-10-02 21:47:53", updated_at: "2021-10-02 21:47:53", plan: nil, quantity: nil, payment_method_token: nil>
```

## Additional Context

Gemfile

```ruby
gem 'pay', '~> 3.0.21'
gem 'stripe', '~> 5.38.0'
```

.env (Obscured for privacy, but the keys are live and valid)

```
STRIPE_PUBLIC_KEY=pk_test_xxx
STRIPE_PRIVATE_KEY=sk_test_xxx
STRIPE_SIGNING_SECRET=whsec_xxx
```

Please let me know if there is any additional context needed to assess the issue.

**Comment by excid3** [comment]
Pay 3 uses `pay_customer` instead of `include Pay::Billable`. See the docs: https://github.com/pay-rails/pay/blob/master/docs/1_installation.md#models
