### ISSUE TITLE
Payment Confirmation page not showing confirmation form?

### ISSUE THREAD

**Issue by adamhowell** [pay-rails/pay#451]
![Screen Shot 2021-10-03 at 8 30 16 AM](https://user-images.githubusercontent.com/26133/135753757-1a2c0cdc-4d19-40d4-8ac4-92c7b863f869.png)

I have a user that's running into the payment confirmation flow and, when looking at this screen above:

A) just a heads up, the `<%= t(".confirm_description") %>` was missing on line 14 of the views/payments/show.html.erb

and B) the form has class="hidden" here and doesn't seem to be unhiding. I'm masquarading as my user here, so I just wasn't sure if it was an issue with the form or something else. Any help would be appreciated, thanks!

**Comment by excid3** [comment]
A - Line 14 is for error messages from Stripe.js: https://github.com/pay-rails/pay/blob/master/app/views/pay/payments/show.html.erb#L14

B - Have to share some more details about the payment intent like the status and things.

**Comment by adamhowell** [comment]
Continuing this conversation in the jumpstart-pro repo instead…

**Comment by excid3** [comment]
@adamhowell released a new version that probably fixes this. Update the pay gem and that should work now.
