### ISSUE TITLE
Forwarding Subscription metadata to Charge metadata

### ISSUE THREAD

**Issue by jaahoo** [pay-rails/pay#458]
Hi,
when I use
`user.payment_processor.subscribe(metadata: {foo: bar}, ...)`
I see them in Stripe admin under Subscriptions and I see them in DB pay_subscriptions table.
However the charge from this subscription doesn't have metadata
Only immediate charges save metadata in Stripe admin and pay_charges table
`user.payment_processor.charge(metadata: {foo: bar}, ...)`
I think it should be forwarded from Subscription to Charge

**Comment by excid3** [comment]
Stripe does that automatically and webhooks will record that to the Charge.

**Comment by jaahoo** [comment]
Yes this is test for subscription metadata, this works fine no problem here.
But when I subscribe with metadata a charge is created WITHOUT metadata.
I think that subscribe metadata should be pass to charge metadata.
In my project I have an Item that I could charge right away or subscribe to it.
And I save id and name of this item to metadata and then I find all charges for this Item.
`Pay::Charge.where("metadata->>'item_id' = ?", @item.id)`
But charges created by subscription are without metadata

**Comment by excid3** [comment]
And you have the Stripe CLI running?
