### ISSUE TITLE
Best way to modify the `billable#subscribe` method?

### ISSUE THREAD

**Issue by rathboma** [pay-rails/pay#469]
Hey Chris and co :-).

I've managed to build my app only using a single product so that I can use the library, and I have a question about customizing the `subscription` model.

My object model is (basically):

User `has many` Workspaces.

So I'd like to link a subscription to a workspace (add `workspace_id` to `Pay::Subscription`).

I've followed the guide about customizing the `Pay` models, but I still don't see an easy path to change the `billable#subscribe` method to pass through extra properties for `Pay::Subscription`.

Is this something you'd consider, or do you think it's better to just manually add the workspace after creating the subscription?

If I were doing this without `pay`, and directly using the stripe code, I'd create a subscription in an after-create hook for the workspace.

**Comment by excid3** [comment]
Subscribe just passes along the arguments to the API, so if you want to include say metadata, just pass that in. 

```ruby
subscribe(metadata: { workspace_id: @workspace.id })
```

Or you can also do it in webhooks. Up to you.

**Comment by rathboma** [comment]
Hey! So yes I understand the metadata section and how it forwards to Stripe, but what do you think about automating the opposite - Automatically adding a new association to the `Pay::Subscription` record model when calling `subscribe`?

**Comment by rathboma** [comment]
Ok, figured out a little hack :-)

```ruby

module SubscriptionExtensions
  extend ActiveSupport::Concern

  included do
    belongs_to :workspace
    before_validation :set_workspace
  end

  def set_workspace
    self.workspace_id ||= self.metadata["workspace_id"].to_i
  end

end

```

**Comment by excid3** [comment]
Yep, that's what I would recommend. 👍
