### ISSUE TITLE
Redirect webhook route through a custom controller

### ISSUE THREAD

**Issue by kb1995** [pay-rails/pay#471]
Thanks a lot for the amazing work on this gem!

I just moved from a custom Stripe integration over to Stripe Checkout + the Pay gem.

Everything worked fine until I pushed to production. I noticed that my webhook events were erroring out.

I then quickly realised it's because I'm using the Lockup gem (simple auth) for my sidekiq dashboard.

The way that I went around it before was link my stripe webhook through a controller

```
post "/stripe", to: "stripe_event/custom_webhook#event"`
```

```
module StripeEvent
  class CustomWebhookController < StripeEvent::WebhookController

    # skip lockup check, only relevant for admin features
    skip_before_action :check_for_lockup, raise: false

  end
end
```

I just wanted to check if it's safe to do that for the Pay gem as well. So would something like this work?

```
post "/pay/webhooks/stripe", to: "stripe_event/custom_webhook#event"
```

Many thanks!

**Comment by excid3** [comment]
Lockup lets you put the password in the URL, so you wouldn't need to modify Pay's controller at all. Just include the lockup_codeword in your Stripe webhook URL.

```
http://somedomain.com/or_path/?lockup_codeword=secret
```

**Comment by kb1995** [comment]
@excid3 Thanks for the quick reply - I just tested it and unfortunately this method is not working as expected

Error from stripe:

```
<html><body>You are being <a href="https://domain.io/lockup/unlock?return_to=%2Fpay%2Fwebhooks%2Fstripe">redirected</a>.</body></html>
```

Stripe URL is `https://domain.io/pay/webhooks/stripe?lockup_codework=secret`

I will investigate further in the meantime

**Comment by excid3** [comment]
Hmm, wonder why Lockup would be doing a redirect?

Also you can inject the skip_before_action by using the same approach as here: https://github.com/pay-rails/pay/blob/master/docs/8_customizing_models.md#customizing-pay-models

Just inject a module into the `Pay::Webhooks::StripeController` instead.
