### ISSUE TITLE
Improve Stripe credentials documentation (or remove the page)

### ISSUE THREAD

**Issue by ro31337** [pay-rails/pay#496]
There is a page right here https://github.com/pay-rails/pay/blob/master/docs/stripe/2_credentials.md - which is blank. It's probably worth mentioning something like "Documentation is in progress, please come back later" or just remove the page if documentation is not required.

Or (ideally) it should contain the documentation about Stripe credentials.

**Comment by guillaumebriday** [comment]
It has been filled up a bit https://github.com/pay-rails/pay/blob/master/docs/stripe/2_credentials.md
