### ISSUE TITLE
Paddle webhooks via html not changing subscription status

### ISSUE THREAD

**Issue by kwhandy** [pay-rails/pay#557]
Hi guys, I'm trying to cancel subscription using paddle overlay button but the subscription status not updated even the cancellation succeed, any idea about this?

**Comment by excid3** [comment]
We'll need some more information to help with anything.

**Comment by kwhandy** [comment]
> We'll need some more information to help with anything.

```ruby
def cancel
        if @user.payment_processor.subscribed?
            @cancellation = @user.payment_processor.subscription.paddle_cancel_url
        else
            flash[:alert] = "You don't have premium subscription to cancel."
            redirect_to billing_path
        end
        
    end
```

I am doing this with my custom billing controller, and render (at)cancellation variable using link_to and include the success page url, after click it will redirect to Paddle's cancel then redirect to success page. But the strange is, the webhook updating that subscription except the subscription 'status' which still in *active* state instead should be *canceled* or *cancelled*. So I wonder if am I doing the wrong procedure. @excid3

**Comment by mikekreeki** [comment]
I noticed this as well. When the user cancels or I cancel his subscription in Paddle admin, the webhook only sets `ends_at`, but `Pay::Subscription#status` stays as `active`. 

My frontend incorrectly checks only `#status` to determine if the plan is active or not. So I guess, I will do a cron job that will update `#status` to `canceled` when `ends_at` date comes.

Any downside with this approach? Thanks.

**Comment by excid3** [comment]
The status isn't really important since the statuses are inconsistent across all the different payment processors. It's the `ends_at` timestamp that you want to be looking at.

**Comment by mikekreeki** [comment]
Thanks @excid3, that's super helpful 👍

**Comment by kwhandy** [comment]
So what do you mean by that is I can't check user with the gem's `@user.payment_processor.subscribed?` and you recommend to make a custom function to check subscription status? @excid3
