### ISSUE TITLE
Being redirected to home page instead of Stripe Checkout

### ISSUE THREAD

**Issue by jschee** [pay-rails/pay#575]
Authentication: Devise

I believe I have everything configured correctly(very clean instructions 👍🏼). This is my current problem: Let's say a user clicks the checkout button partial and is redirected to stripe checkout, but decides to jump back to prior page. If that user clicks checkout again, user is no longer redirected to stripe checkout, but instead localhost:3000.

When I open up dev tools and clear my cookies, re-login user, click checkout, I am directed to stripe checkout once again.

Am I missing a step? Should I be resetting user's processor_id if user does not proceed to checkout?

```
# model
class User < ApplicationRecord
 pay_customer
end
```

```
# controller
class CheckoutsController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_authorized
    def show
      current_user.set_payment_processor :stripe
      current_user.payment_processor.customer
		
      @checkout_session = current_user.payment_processor.checkout(
        mode: "subscription",
        line_items: "some_price"
      )
   end
end
```

```
#view
<script src="https://js.stripe.com/v3/"></script>

<%= render partial: 'pay/stripe/checkout_button', locals: { session: @checkout_session, title: "Checkout" } %>
```

**Comment by excid3** [comment]
Hard to say without some more details. 

I typically recommend redirecting to the session URL directly in the controller. It's much easier.
