### ISSUE TITLE
Stripe PaymentIntent for SCA getting it's source removed, then fails

### ISSUE THREAD

**Issue by kyleschmolze** [pay-rails/pay#577]
Hi there! First off, thanks for the amazing gem. 

I'm getting a very weird error that I haven't been able to pin down, and would super appreciate any help. I'm trying to get SCA with 3D auth confirmations working on the front end, so all of these requests are happening with the 4000 0027 6000 3184 Stripe test number to simulate 3D auth.

I am _intermittently_ seeing the Stripe PaymentIntent that is created using the code below throw a `Pay::Stripe::Error`.

```ruby
    begin
      user.set_payment_processor :stripe
      user.payment_processor.payment_method_token = @payment_method_id # can confirm this is getting set!
      user.payment_processor.charge(@purchase.total_cents)
    rescue Pay::ActionRequired => e
      return e.payment
    rescue Pay::Stripe::Error => e
      binding.pry # i'm debugging in here trying to figure out what happened and seeing the error message below
      raise e
    end
```

The error looks like this:
`#<Pay::Stripe::Error: (Status 400) (Request req_zIAoTKj97i15d8) You cannot confirm this PaymentIntent because it's missing a payment method. You can either update the PaymentIntent with a payment method and then confirm it again, or confirm it again directly with a payment method.>`

The really weird thing is how intermittent this is! Sometimes it works perfectly, and sometimes it fails with the above error message. Even though I can confirm that a valid `payment_method_token` is getting attached, it's somehow getting removed! So I went into the Stripe logs in the Dashboard to compare the randomly successful attempts with the randomly failing ones, and I see some more funny behavior. 

Here's the successful charge going through (the events on the left are reverse chronological):
![image](https://user-images.githubusercontent.com/1200038/159815836-54a6ed39-e5d6-4cb6-9454-9ef274b7125a.png)

You can see that the charge went through just fine. 

Now look at the failed one!

![image](https://user-images.githubusercontent.com/1200038/159815900-45eff6c3-f4c2-4c6c-ba6b-d47f7cdf0795.png)

A request was sent "From your application" to `source_cancel` on the PaymentIntent?? So somehow the PaymentIntent was created, needed confirmation, then my app told Stripe to _remove_ the "source" (aka remove the payment method), and then try to confirm it again or something, and then Stripe complains because there's no payment method? I am quite confused! 

Any pointers in any direction would be MUCH appreciated. Thank you so much!

**Comment by kyleschmolze** [comment]
Ok, thanks for that. You've made me realize that the screenshots above don't describe my bug accurately. The payment intents in those screenshots are the ones which are successfully created, and I *am* manually denying some of them, so that I can retry the request and reproduce the bug. 

That's not the bug! 

When the bug happens, no PaymentIntent is created on Stripe's end, because the request to create one fails, and the reason for that is that no payment method is passed into the request to create one. However, I *am* passing in a payment method to Pay's `charge` method [here](https://github.com/pay-rails/pay/blob/072af4ab2e1d2f85d9c12190532648abc629d5a3/lib/pay/stripe/billable.rb#L84). 

I placed a `binding.pry` in that method and got debugging. Basically, the problem is that even after `add_payment_method(payment_method_token, default: true)` is called _with_ a `payment_method_token`, `pay_customer.default_payment_method` is coming back `nil`. So the "make this payment method default" is failing in some sense. I can see the requests going off to _make_ it the default. I can see the attempt, but somethings not working because `pay_customer.default_payment_method` seems to (50% of the time) come back `nil`, and then the whole request fails.

Any ideas what could be causing that?

**Comment by kyleschmolze** [comment]
I'm also not sure why there's a need to `extract_attributes` and then `update!` with them, although there may be good reason. Could we replace it with a simple `update_all default: false` and then `pay_payment_method.update_attribute :default, true` to simplify a bit? I admit I don't understand this library as well as you!

**Comment by excid3** [comment]
This method saves a payment method (hence the name), so it needs to extract the attributes we need to save for it. If you removed that, then it would be an empty payment method with default set to true or false.

**Comment by excid3** [comment]
I get what you're saying now! I'm thinking the better solution will be to filter out the existing payment method ID when we mark the existing payment methods as `default: false`

```ruby
# Ignore the existing payment method ID here
pay_customer.payment_methods.where.not(id: pay_payment_method.id).update_all(default: false) if default

# Then update it on its own
pay_payment_method.update!(attributes)
```

**Comment by excid3** [comment]
We walked through the permutations of existing records in the db, and I think we also want to reload the default_payment_method every time just to be safe so I made that change too.

Check out this commit where we changed it and let me know if it fixes your issue! 1e58c7e

**Comment by excid3** [comment]
Ping @kyleschmolze 👍

**Comment by kyleschmolze** [comment]
Sorry I thought I commented already - it worked! Thank you!!

**Comment by excid3** [comment]
Fantastic!
