### ISSUE TITLE
config.active_job.queue_name_prefix breaks webhooks

### ISSUE THREAD

**Issue by dpaola2** [pay-rails/pay#589]
To reproduce, set the `config.active_job.queue_name_prefix` to something like `"YourApp_production"` in your configuration (`application.rb` or `production.rb`). 

Then, observe that while webhook processing jobs are queued, they are never processed.

I'm using Sidekiq if that matters.

**Comment by excid3** [comment]
You added the new queue to sidekiq?

**Comment by excid3** [comment]
@dpaola2 Going to close this, but feel free to reopen if you have some more details. 👍

**Comment by dpaola2** [comment]
Sorry Chris! Project got put onto the back burner.
