### ISSUE TITLE
`Pay::Subscription#name` not updating via web hook

### ISSUE THREAD

**Issue by joemasilotti** [pay-rails/pay#597]
I'm using `pay_subscriptions.name` to determine which plan a customer is on. I do all checkout/payment via the Stripe Portal. Now that there are 2 plans, folks can upgrade/downgrade between them. However, the database record doesn't seem to be updated. The old plan's name and `metadata` columns don't seem to change – but the `updated_at` timestamp does.

What more info can I provide to help debug this? If it helps, the entire app is [open source](https://github.com/joemasilotti/railsdevs.com) but I understand that's a lot of code to dig through to help with my issue!

**Comment by excid3** [comment]
You would use the `swap` method on a subscription to upgrade or downgrade. https://github.com/pay-rails/pay/blob/master/docs/6_subscriptions.md#swap-a-subscription-to-another-plan

`name` is intended for separating out subscriptions. A customer could have multiple subscriptions with your product. 

The `processor_plan` is the plan/price ID. Pay doesn't have any knowledge of how `processor_plan`s relate to each other, so you'd need to build that portion. 

In the future, we may implement a Pay::Plan model with some associations for upgrading and downgrading.

**Comment by joemasilotti** [comment]
> You would use the `swap` method on a subscription to upgrade or downgrade. https://github.com/pay-rails/pay/blob/master/docs/6_subscriptions.md#swap-a-subscription-to-another-plan

Is it not possible to let the customer do this themself via the Stripe Customer Portal? Ideally I don't have to build out any UI around payments just for this flow.

> `name` is intended for separating out subscriptions. A customer could have multiple subscriptions with your product.
> 
> The `processor_plan` is the plan/price ID. Pay doesn't have any knowledge of how `processor_plan`s relate to each other, so you'd need to build that portion.

I'm not sure I follow. Are you saying I should be using `processor_plan` instead of `name` to differentiate the different plans/products in my app with custom logic?

**Comment by excid3** [comment]
> Is it not possible to let the customer do this themself via the Stripe Customer Portal? Ideally I don't have to build out any UI around payments just for this flow.

That would be a question for the Stripe docs, not Pay.

**Comment by excid3** [comment]
> I'm not sure I follow. Are you saying I should be using processor_plan instead of name to differentiate the different plans/products in my app with custom logic?

`processor_plan` is the Price ID in Stripe. `name` is only a concept in Pay and doesn't have anything to do with Stripe.

**Comment by joemasilotti** [comment]
>> Is it not possible to let the customer do this themself via the Stripe Customer Portal? Ideally I don't have to build out any UI around payments just for this flow.

> That would be a question for the Stripe docs, not Pay.

Sorry, I wasn't clear. This already is possible with Stripe Customer Portal. But the subscription update (`name` and `pay_name`) aren't updating on `Pay::Subscription` when the subscription changes.

> > I'm not sure I follow. Are you saying I should be using processor_plan instead of name to differentiate the different plans/products in my app with custom logic?

> `processor_plan` is the Price ID in Stripe. `name` is only a concept in Pay and doesn't have anything to do with Stripe.

Perhaps a better question would be: What is the recommended approach to differentiate what plan someone is subscribed to via Pay?

**Comment by excid3** [comment]
> Perhaps a better question would be: What is the recommended approach to differentiate what plan someone is subscribed to via Pay?

Use `processor_plan`

> But the subscription update (name and pay_name) aren't updating on Pay::Subscription when the subscription changes.

The Billing Portal would not be updating the `pay_name` metadata on the Subscription. It would update the `processor_plan`.

**Comment by joemasilotti** [comment]
Got it. I'll refactor. Thanks for the help Chris!

**Comment by marckohlbrugge** [comment]
Thanks for the comments guys. I ran into the same issue thinking `plan_name` was the preferred way of identifying plans. Switched to `processor_id` now 👍

**Comment by davidalejandroaguilar** [comment]
Definitely surprising behavior:

```rb
Business.last.payment_processor.subscription
# => 
# #<Pay::Stripe::Subscription:0x000000017b957820
# metadata: {"pay_name"=>"Pro Plan", 
#  name: "pro",
#  ...

Business.last.payment_processor.subscription.swap(premium_stripe_price_id) 
# => 
# #<Pay::Stripe::Subscription:0x000000017b957820
# metadata: {"pay_name"=>"Pro Plan", },
#  name: "pro",
#  ...

# Potential source of bugs
Business.last.payment_processor.subscribed?(name: "premium")
# => false

Business.last.payment_processor.subscribed?(processor_plan: premium_stripe_price_id)
# => true
```

Thanks for opening this @joemasilotti and @excid3 for clarifying.
