### ISSUE TITLE
undefined method `enabled_processors=' && undefined method `emails' for Pay:Module (NoMethodError) 

### ISSUE THREAD

**Issue by Tioneb12** [pay-rails/pay#599]
I'm trying to install stripe with pay gem with the readme and the gorails video (It's  very different). 

I followed all step to the initalizer but get several errors :
undefined method `enabled_processors='  for Pay:Module (NoMethodError)
undefined method `emails' for Pay:Module (NoMethodError)

I

**Comment by excid3** [comment]
The video is out of date and we're going to update that sometime soon.

**Comment by Tioneb12** [comment]
Great ;)

But why I get this errors ? I followed the pay gem readme step by step...

**Comment by excid3** [comment]
The readme is for the latest version which hasn't been released yet. It will come out in the next week or two.

I'd recommend you use it, but you'll need to use the gem from GitHub.

**Comment by excid3** [comment]
I think we're going to release the new Pay early next week. 👍

**Comment by Tioneb12** [comment]
Oh, great news 🤩
