### ISSUE TITLE
Optional receipt mail PDF attachment

### ISSUE THREAD

**Issue by mguidetti** [pay-rails/pay#600]
In our implementation of Pay we prefer to link to Stripe's hosted receipts in the receipt email body rather than attach our own PDF through the Receipts gem. (No disrespect to that great gem!) 

Previously I prevented the PDF attachment on the mail by just not including the Receipts gem in our Gemfile. This seemed to do the trick, but now that there is a check for valid gem dependency versions, the app will error on launch: `[Pay] receipts gem must be version ~> 2 (RuntimeError)` 

Should this be changed to allow an optional dependency on the receipt gem? If not, could you recommend a way to exclude the PDF attachment on receipt emails? Maybe it should be an option in the new email configuration?

**Comment by excid3** [comment]
Thanks! That was a mistake in our check. Receipts gem will always be optional.

**Comment by mguidetti** [comment]
Fastest fix I've ever seen. Thanks! 🙇🏻‍♂️

**Comment by excid3** [comment]
No problem! You caught me at the perfect time! 

This is the kind of stuff I wanted to iron out before we release the new Pay version, so huge thanks for catching this!
