### ISSUE TITLE
Clarification on the Stripe Connect documentation examples [label: marketplaces]

### ISSUE THREAD

**Issue by Mar1cX** [pay-rails/pay#606]
Hi,

For my specific cases with **Destination Charge** (same applies for Direct Charges) usage, I attempted to use the pay gem **Stripe Connect** side of functionality with pay_merchants, etc. While following the examples it was difficult to apply written methods by the gem to do the functionality. 

1. For the cases with a custom account (in my case), it would be best to show that create_account can be changed for such usage without diving deep into the `create_account` method and the whole Merchant class file.
2. `account_link` and `login_link` should be left for Express account type as if I'm correct both methods are applied for that type of account.
3. While the `transfer` does seem to make sense, the part with the account charge seems slightly strange to me.
  - charge is not part of the `Merchant` methods, which leads it to be part of `Billable`/`Charge` classes.
  - charge is applied on the `pay_customer` while the examples were hinting at charging the `pay_merchant`.
4. For my specific case - during user creation, a Stripe account is created without external_account (debit card) added to it. The charge part is making confusion again in this case, because it seems that a debit card is required at that moment, maybe I'm mistaking it here, but it did not seem that the charge is being done to a customer by the examples.

I believe that the functionality of the pay gem is right there, but documentation makes it rather hard to grasp it and use it without additional modifications. Plus lack of any blogs/tutorials of any Stripe Connect usages with this gem makes it even more difficult. Maybe updated documentation would be helpful with the "step by step" type of usage.

**Comment by henryeticom** [comment]
I Strongly agree with this the documentation for Merchant documentation needs to be rewritten for it to be clear on the charges, as mentioned above. @excid3
