### ISSUE TITLE
`pay_customer': wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by programthis** [pay-rails/pay#613]
I am trying to use stripe_attributes to store in the customer record as defined in the wiki but have been getting this error. It is essentially just copied and pasted from the wiki so not sure what is going wrong here.

`.rvm/gems/ruby-2.7.0/gems/pay-3.0.24/lib/pay/attributes.rb:64:in `pay_customer': wrong number of arguments (given 1, expected 0) (ArgumentError)`

Rails version: 7.0.2.3
Ruby version: 2.7.0
Pay gem version 3.0.24

```
class User < ApplicationRecord
	pay_customer stripe_attributes: :custom_stripe_customer_attributes_method

	def custom_stripe_customer_attributes_method(pay_customer)
		{
			address: {
				city: pay_customer.owner.city,
				country: pay_customer.owner.country
			},
			metadata: {
				pay_customer_id: pay_customer.id,
				user_id: id # or pay_customer.owner_id
			}
		}
	end
end
```

**Comment by excid3** [comment]
That feature hasn't been released yet so you need to use Pay from master.

**Comment by programthis** [comment]
@excid3 what do you mean by Pay from master? And should it not be in the wiki if it hasn't been released yet?

**Comment by excid3** [comment]
You're reading the docs from master. 

If you want to read the docs for your version, you must switch to the tag for that release.

**Comment by programthis** [comment]
Oh ok I understand, thanks!

**Comment by programthis** [comment]
@excid3 So I've switched the gem to be using the master version but no data is actually coming through. In the object response json, metadata just shows as blank. My code is the same as above.

**Comment by marckohlbrugge** [comment]
I just ran into the same issue on the latest `pay` version (6.3.3).

Either I'm misunderstanding something, or many of the code examples are wrong.

```ruby
pay_customer stripe_attributes: :stripe_attributes

# This does NOT work (shown in many examples)
def stripe_attributes
  { … }
end

# This DOES work
def stripe_attributes(pay_customer)
  { … }
end
```

**Comment by excid3** [comment]
Yeah, it passes the pay_customer object in.

Which docs need updating?

**Comment by marckohlbrugge** [comment]
> Yeah, it passes the pay_customer object in.
> 
> Which docs need updating?

Looks like you already found it 👍
