### ISSUE TITLE
Question: Isn't Pay supposed to create a `Pay::Charge` for every monthly subscription invoice paid?

### ISSUE THREAD

**Issue by feliperaul** [pay-rails/pay#643]
Before I issue a PR I'm opening this question for clarification.

After a successful subscription is created, pay creates a `Pay::Charge` in the database  (see https://github.com/pay-rails/pay/blob/73f53778ea2c411992d65380d4b38572f2faaa12/lib/pay/stripe/subscription.rb#L85-L88)

The comment there states that we're doing it during the subscription sync if we already have the latest invoice; otherwise **let webhooks handle it**.

So, if the subscription is made with a free trial, there's no latest_invoice.charge with status `succeeded`. The expectation by looking at the source code is that there would be a webhooks handling the charges later on.

However, even with stripe `cli` running (and processing all other webhooks) I never had a `Pay::Charge` created when future `invoice.paid` events arrived. Digging at the source code, I couldn't find any webhooks registered handling this.

Is this the expected behavior? Because as of right now, we get a new `Pay::Charge` only if the subscription is created with a succeeded payment attached to it; all later payments in the subscription (that generate `invoice.paid` webhooks) are not handled and thereby do not generate `Pay::Charge`s in the database.

Is the idea here to only create a `Pay::Charge` for the first subscription charge, and leave to the developer to implement his webhooks for handling later subscription payments?

**Comment by feliperaul** [comment]
Update: based on this comment

https://github.com/pay-rails/pay/blob/73f53778ea2c411992d65380d4b38572f2faaa12/lib/pay/stripe.rb#L63-L67

I think the idea was to subscribe to `stripe.charge.succeeded` to capture charges BOTH from individual charges AND subscriptions.

However, this is the list of webhooks I get when a new subscription is created:

```
payment_method.attached
setup_intent.succeeded
customer.updated
setup_intent.created
checkout.session.completed
customer.updated
invoice.created
invoice.finalized
invoice.paid
invoice.payment_succeeded
customer.subscription.created
```

So subscriptions do not send `charge.succeeded` events. This is coherent with the Stripe docs [here](https://stripe.com/docs/billing/subscriptions/webhooks#events).

**Comment by excid3** [comment]
Please provide some steps to reproduce the issue and we'll get it sorted.
