### ISSUE TITLE
Is there a way to change the name in the receipt?

### ISSUE THREAD

**Issue by pbmarcano** [pay-rails/pay#644]
I pull my user's "names" from Twitter (its a twitter app). Some users have emojis in their names so I get an error when the pdf receipt is getting generated.

`Prawn::Errors::IncompatibleStringEncoding Your document includes text that's not compatible with the Windows-1252 character set. If you need full UTF-8 support, use external fonts instead of PDF's built-in fonts.`

Is there a good way I can change the name that goes into the PDF? Maybe a good method to monkey patch? (`pay_customer.windows_1252_safe_name`)

**Comment by excid3** [comment]
You can define `def pay_customer_name` on your model to override the name. Otherwise it will try `name` and `first_name + last_name` on the model.

See here:
https://github.com/pay-rails/pay/blob/bf650513ecdac0e58e3c25bd5abb9b3ff2b78bf1/app/models/pay/customer.rb#L65-L66

**Comment by henrydjacob** [comment]
I have the same issue even after implementing pay_customer_name
