### ISSUE TITLE
Storing card data in the Subscription instead of User

### ISSUE THREAD

**Issue by jean-francois-labbe** [pay-rails/pay#67]
Hi,

I've noticed that the follow fields are added to the user table.
```ruby
add_column Pay.billable_table, :card_type, :string
add_column Pay.billable_table, :card_last4, :string
add_column Pay.billable_table, :card_exp_month, :string
add_column Pay.billable_table, :card_exp_year, :string
```

Why don't you store them in the subscription?
Because a user can have multiple subscription and a different card per subscription.
That will allow us to display which card has been registered for a specific subscription.

**Comment by excid3** [comment]
This is the user's default card. Both Stripe and Braintree have default cards on the Customer object, so we're saving that information here.

We may want to additionally add this to the subscription if a specific card is used for the Subscription, but it will use the default card on the customer by default.

It may be useful to add a Pay::PaymentMethod to keep track of these.

**Comment by excid3** [comment]
Also useful thing to note:

This first version of Pay is intended to make payments simple, not support everything out of the box. That's why we don't have things like multiple payment methods yet since a lot of subscription products simply have one active card on file and aren't charging multiple cards.

I know you've got a bit more of a complicated use case, so this may be something we can add sooner than later.

**Comment by jean-francois-labbe** [comment]
Thanks for taking my case into account, I know it's not a classic one.

I don't need this for now, but I think it's a good idea to be able to tell which card was used at payment time.

Since you're talking about first version, do you have any idea of what you'd like to add before releasing it, or if the api will change a lot before v1?

**Comment by excid3** [comment]
The payment method used is saved to every Charge, so you know which one was used historically.

The only thing we don't have support for right now is handling specific payment methods for specific subscriptions.

The API should basically stay the same for v1 as it is now unless we find any glaring holes. :)

**Comment by excid3** [comment]
I'm going to close this, but if anyone wants to open a PR for this, they're welcome to.

We probably want to store the card details and `payment_method_id` on the Subscription. This might also be a good time to add a new model simply to cache a copy of the payment_methods.
