### ISSUE TITLE
"Invalid string: BAh7CEkiCG...7b80c2b880; must be at most 200 characters" when using client_reference_id feature

### ISSUE THREAD

**Issue by sammovale** [pay-rails/pay#670]
When using the newly implemented `client_reference_id`, the implementation uses Rails `to_sgid`. However this generates a string that is often over 200 characters resulting in Stripe returning a 400. When application and model names are short this results in a shorter URI and an overall shorter value that gets under the threshold. Nevertheless, when the user_id or application or model name is long, it will go over the 200 characters.

**Comment by sammovale** [comment]
For further context, I am trying to use this feature to further scope the `Pay::Charge` model to a `Booking` and  `User` (Currently the user has the `pay_customer` defined in its model). To do this I was trying to pass metadata through the checkout but that does not propagate the metadata to the `payment_intent` or `charge`.

The client_reference_id looks promising but seems its implementation of using sgid will override the polymorphic association on the `Pay::Change` that I wish to retain for the user model.

I get the basic premise of the document describing the `ChargeExtensions` to add functionality such as a `belongs_to :order` however, how can this be done using Stripe Checkout when all callbacks make the metadata nil when using Checkout. Seems that using this feature and trying to further scope a `Pay::Charge` may not work unless going through client_reference_id.

**Comment by excid3** [comment]
Still no update from Stripe on this. They didn't seem to have thought about this kind of use case strangely enough.

**Comment by marckohlbrugge** [comment]
I'm running in to the same issue. The sgid that is generated is 202 characters long.

I'm not holding my breath for Stripe to increase the limit. Are there any suggested workarounds? 

Maybe we can implement `model.from_client_reference_id(client_reference_id)` + `model.to_client_reference_id` and leave it to the user to implement these?

**Comment by excid3** [comment]
I talked with them several times about it, but nothing has changed.

Stripe mentioned that even though the `client_reference_id` is something you could manipulate on the Pricing Table, why would you? You'd end up paying for someone else's account if you did. I think that seems fair?

I like the `to_client_reference_id` `from_client_reference_id` and we could have those default to `User-1` and then you could override to provide your own implementation.

```ruby
def to_client_reference_id
  to_param
end
```

```ruby
module Pay
  class Customer
    def self.from_client_reference_id(client_reference_id)
      model_name, id = client_reference_id.split("-", 2)
      model_name.constantize.find(id)
    end
  end
end
```

**Comment by marckohlbrugge** [comment]
> Stripe mentioned that even though the client_reference_id is something you could manipulate on the Pricing Table, why would you? You'd end up paying for someone else's account if you did. I think that seems fair?

Depending on one's implementation, this could be a security issue. If I secretly start a subscription for your account I might end up seeing your usage data on the invoices. And worse, I might be able to trick customer support into giving me access to your account as I'd be able to prove ownership of the email address associated with the billing account, etc.

---

It's unfortunate Stripe isn't responsive regarding the length limitation. I think the next best solution is a custom serializer/deserializer that takes up less space.

---

Related: Stripe is beta testing the ability to pass in a Stripe Customer ID for checkout sessions originating from the pricing table. See https://stripe.com/docs/payments/checkout/pricing-table#customer-session

I just implemented this, and it seems to work as expected. Of course it only solves for the Stripe Pricing Table functionality. Not any other places where you might use the client reference ID.

**Comment by excid3** [comment]
Alright, we've decided to just change our implementation and maybe in the future we can use SGIDs.

Our format is going to be `"Model::Name/ID"` and we'll keep a list of models that use Pay so we can validate client_reference_ids against the Pay model list (preventing tampering the way that SGIDs did). We opted for a `/` between the model name and ID to match GlobalIDs and allow UUIDs as the ID, etc.

You can get a `client_reference_id` through a Pay::Customer with `stripe` as the processor.

```ruby
client_reference_id = Pay::Stripe.to_client_reference_id(@user) #=> "Admin::User/1"
```

When a Stripe Checkout Session Completed event comes in, it will lookup the record by the client reference ID with the following method:
```ruby
Pay::Stripe.find_by_client_reference_id("Admin::User/1") #=> #<Admin::User id="1">
```
