### ISSUE TITLE
API version error in latest release v5.0.0

### ISSUE THREAD

**Issue by aashishdhawan** [pay-rails/pay#680]
I am using pay 5.0 and stripe 7.0 gem, and it is throwing following error. 

Pay::Stripe::Error (Invalid Stripe API version: 2022-08-02):

I am not sure but this seems to be wrong 
https://github.com/pay-rails/pay/pull/675/files#diff-025f7375983867135a58d4ee2d3d90226591a447c719966d95d923402f557e84R39

I guess it should say 2022-08-01 instead of 2022-08-02 (I could be wrong)

**Comment by excid3** [comment]
Use 5.0.1 👍
