### ISSUE TITLE
Webhooks not coming thourgh locally

### ISSUE THREAD

**Issue by simonsapiel** [pay-rails/pay#692]
Hi are the docs still up to date as it would seem that none of the supposed webhooks are coming through? I've correclty added the signing_secret to be the one

```
stripe listen --forward-to localhost:3000/pay/webhooks/stripe
```
outputs. I also don't have any `pay.rb` initializer as the webhook endpoints are supposed to be added automatically? I cannot find them in my routes though.

The only route for pay is

```
pay_path  /pay  Pay::Engine
```

**Comment by excid3** [comment]
What do the logs show?

**Comment by simonsapiel** [comment]
Nothing. The server is not being hitted by any requests related to the webhooks and neither is the local server running stripe listen getting any hits.

**Comment by simonsapiel** [comment]
For some reason all the webhooks are going into my staging app. I can verify this from the stripe webhooks logs.

**Comment by excid3** [comment]
The Stripe CLI is separate from standard webhooks that you configure on the Stripe dashboard.
