### ISSUE TITLE
Add email for `stripe.customer.subscription.trial_will_end`

### ISSUE THREAD

**Issue by excid3** [pay-rails/pay#695]
It would be great for Pay to send emails to remind customers when trials are ending.

> **customer.subscription.trial_will_end**
> Occurs three days before a subscription’s trial period is scheduled to end, or when a trial is ended immediately (using trial_end=now).

We might want two separate email contents for this so that we can denote the trial has ended or will end in X days.

**Comment by cjilbert504** [comment]
I'd like to take this one on.

**Comment by excid3** [comment]
All yours my friend.
