### ISSUE TITLE
Locale setting

### ISSUE THREAD

**Issue by dvodvo** [pay-rails/pay#696]
It is not clear where the locale should be set for the stripe javascript rendering of the card interface.
controller sets `    @setup_intent = current_user.payment_processor.create_setup_intent` 
```
  <%= form_with url: purchase_product_path(id: @product.id), params: {product_pricing: params[:product_pricing_id]},
    id: "payment-form",
    data: {
      locale: I18n.locale,
      setup_intent: @setup_intent.client_secret
    } do |form| %>
```
does render a `data-locale` attribute
```
<form id="payment-form" data-locale="it" data-setup-intent="seti_1LiDFPK5XhmyYNpJW0Ez5Z8D_secret_MR5QwW9TZIm2Rmf8OkvNNfI4wDIvM0p" action="/products/12/purchase" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="UgWpzjbQ6mygncKMcC77jDuaNKaCxrp4GJbBFWlkVXkrbmWt1hY_3f7L7ntrNZbLp-Bnh4r0v4R7kc-AHlk7rg" autocomplete="off">
```
but has no effect as the rendering is unchanged from base version.
![image](https://user-images.githubusercontent.com/716130/190353628-6dbbf773-7536-4ac5-a18a-24b938c1a422.png)

**Comment by excid3** [comment]
You would need your Javascript to read that and use it with Stripe.js when you create Elements.

https://stripe.com/docs/js/elements_object/create#stripe_elements-options-locale
