### ISSUE TITLE
Charges format

### ISSUE THREAD

**Issue by dvodvo** [pay-rails/pay#699]
On [this page of the docs](https://github.com/pay-rails/pay/blob/master/docs/5_charges.md) it states
```
@user.payment_processor.charge(15_00) # $15.00 USD
```
However, when an action processes
```
    charge_decimal_value = (@unit_price * @product_pricing.units.to_d)
    charge_decimal_value_to_send = ActionController::Base.helpers.number_with_precision(charge_decimal_value, precision: 2).to_s.gsub(".", "_")
puts charge_decimal_value_to_send
    current_user.payment_processor.charge(charge_decimal_value_to_send)
```
The rescue error message logged, after having confirmed `29_40`is returned as
```
Invalid integer: 29_40
```
I found this curious as [as far as I can remember the Stripe docs](https://stripe.com/docs/api/prices/create?lang=ruby)  state a string of cents.

Thus,
```
    charge_decimal_value = ( @unit_price * @product_pricing.units.to_d * 100)
    charge_decimal_value_to_send = charge_decimal_value.round()
```
returns the integer `2940`  which passes stripe requirements.

**Comment by excid3** [comment]
Pay and Stripe always use cents.
