### ISSUE TITLE
How to create a product?

### ISSUE THREAD

**Issue by Cushty** [pay-rails/pay#713]
Hi how can a user create a product, I have got the connect onboarding implemented but not sure how to create a product via the API? Thanks

**Comment by Cushty** [comment]
Ah ok, will Pay take care of the webhooks or will I need to add them manually? Thanks

**Comment by excid3** [comment]
Webhooks for products or what do you mean?

**Comment by Cushty** [comment]
yep webhooks for products that i create via the Stripe gem, thanks

**Comment by excid3** [comment]
To do what? We don't have any models for products or prices.

**Comment by Cushty** [comment]
Ah ok, I will use the stripe CLI, thanks

**Comment by Cushty** [comment]
1 question will you be making an updated Pay tutorial? I have a pro sub on your tutorial platform but nothing updated yet, thanks

**Comment by cjilbert504** [comment]
@Cushty - I'll add this to our backlog of videos to make.
