### ISSUE TITLE
Allow env variables to override configuration

### ISSUE THREAD

**Issue by jean-francois-labbe** [pay-rails/pay#73]
Hi,

What do you think about giving the highest priority to configuration from env variables?
[here](https://github.com/jasoncharnes/pay/blob/d372897f1912fe7baa57e22d8df939e7ce00f03e/lib/pay/stripe/api.rb#L9) the priority is: secrets, credentials, env variables.

This doesn't allow us to use env variables to override configuration in review env or staging env

That would be interresting to use the same priority as in rails for DATABASE_URL for [example](https://github.com/rails/rails/blob/b75192845a6aa89b35c857e9f3de443ae1a0fbd5/railties/test/application/initializers/frameworks_test.rb#L232)

What do you think?

**Comment by excid3** [comment]
ENV should probably be first to allow overrides. 👍 PR?

**Comment by jean-francois-labbe** [comment]
almost ready

**Comment by jean-francois-labbe** [comment]
here is the PR: https://github.com/jasoncharnes/pay/pull/74
