### ISSUE TITLE
Feature Request: Store the subscription created date

### ISSUE THREAD

**Issue by mpvosseller** [pay-rails/pay#731]
Would you be open to storing the actual subscription created date?

There is `created_at` but that is the time the record was created in our database and not the date the subscription was created at the processor. The dates could differ significantly if the original webhook wasn't processed immediately or wasn't processed at all and we synced it later. 

Implementation would be similar to #694
Would add a new column `processor_created_at` and set it to based on  the `:created` field in the Stripe subscription object.

Happy to implement this in Stripe if you can do the other processors.

**Comment by excid3** [comment]
I think it would be fine to just set `created_at` to match the remote subscription. There's no real value in knowing when our database record was created.

**Comment by mpvosseller** [comment]
Great, will send a PR soon.

**Comment by excid3** [comment]
We already do this for Charges, but not Subscriptions. https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/charge.rb#L36

Should be as simple as copying this line over. I can probably tackle that tonight.
