### ISSUE TITLE
Braintree JS Elements

### ISSUE THREAD

**Issue by grichardomi** [pay-rails/pay#75]
Could not get Braintree/Paypal CC  to populate, using Braintree payments resource links.

Does anybody have a Braintree client presentation JS elements to share?

Thanks!

**Comment by excid3** [comment]
I don't have a reference handy at the moment for ya, but can walk you through it real quick.

I'm just using their Drop-in JS from https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/javascript/v3

You can get the Braintree client token by running `Pay.braintree_gateway.client_token.generate`

Intercept submit, call the `requestPaymentMethod` on your braintree drop-in instance in JS. Append the `user[processor]=braintree` and `user[card_token]` set to `payload.nonce` hidden fields and then submit the form.

I'm using `Rails.fire(form, 'submit')` to trigger the form submit.

**Comment by grichardomi** [comment]
Any form code snippets?

**Comment by grichardomi** [comment]
My credentials are valid. 

I get this when I ran Pay.braintree_gateway.client_token.generate:
undefined method `client_token' for nil:NilClass

Any idea?

**Comment by excid3** [comment]
You have the Braintree gem in your Gemfile, right? The Braintree initialization happens only if it finds that gem.

https://github.com/jasoncharnes/pay/blob/master/lib/pay/engine.rb#L13

Wheich then defines the `Pay.braintree_gateway`

https://github.com/jasoncharnes/pay/blob/master/lib/pay/braintree/api.rb#L4-L16

**Comment by grichardomi** [comment]
I restored the app with the old gem file, without branintree and expected it work. Go figure.

You are my savior.

Thank you!

**Comment by excid3** [comment]
Haha! I got confused by that the other day too. :)
