### ISSUE TITLE
Overeager dependency required (Rails).

### ISSUE THREAD

**Issue by zackgilbert** [pay-rails/pay#750]
It looks like the Pay gem requires loading all of Rails (instead of the individual components that it relies one): 
https://github.com/pay-rails/pay/blob/304f344f1c11d92a75714343f559c893997f87c7/gemfiles/rails_master.gemfile#L26

I have a Rails API app that doesn't load all of rails, but only specific gems: 
```
gem 'actionmailer', '~> 7'
gem 'activejob', '~> 7'
gem 'activemodel', '~> 7'
gem 'activerecord', '~> 7'
gem 'activestorage', '~> 7'
gem 'railties', '~> 7'
```

But once I include the Pay gem, it appears to load in all of Rails, including two unnecessary libraries:
<img width="336" alt="Screen Shot 2022-12-05 at 2 20 13 PM" src="https://user-images.githubusercontent.com/432526/205735327-a441a528-da21-45cd-a053-52ea6d5f679d.png">
<img width="427" alt="Screen Shot 2022-12-05 at 2 20 36 PM" src="https://user-images.githubusercontent.com/432526/205735340-5237b91b-7266-4e1e-92a8-690711f4b878.png">

There might be others that are unnecessary for the Pay gem, but that I'm including. It would be nice if you narrowed down your dependencies to only what you are actually dependent upon. This might help cut down on the build time and potential conflicts.

Just thought I'd share.

**Comment by excid3** [comment]
PRs welcome
