### ISSUE TITLE
Issue with emails in receipt PDF

### ISSUE THREAD

**Issue by marckohlbrugge** [pay-rails/pay#752]
Seems like there's a bug in rendering the support email in the PDF receipts.

```
pay (6.1.0)
receipts (2.1.0)
```

```ruby
Pay.setup do |config|
  config.support_email = "Handle Horse <marc@handle.horse>"
end
```

![CleanShot 2022-12-13 at 22 19 35@2x](https://user-images.githubusercontent.com/93276/207372672-89d01eb0-5798-469f-b165-772e8a77d72d.png)

**Comment by cjilbert504** [comment]
Yeah, I was able to reproduce. Seems that those angle brackets are the issue. I'll look into this further. Thanks for pointing this out @marckohlbrugge.

**Comment by excid3** [comment]
This is because Receipts expects the email to be just the plain email. We'll need to update the Receipts gem to handle this.

I'm thinking we'll need to parse with the Mail gem or regex to grab just the email for the mailto link, etc.

**Comment by excid3** [comment]
This should be fixed @marckohlbrugge 👍 

We decided to have Pay cast it as a `Mail::Address` when it's assigned, so we can parse out only the email when we send it to Receipts to render the PDF. That way Receipts stays simpler and doesn't need the Mail dependency.
