### ISSUE TITLE
Pay Blocks Stripe API Key In CI Only

### ISSUE THREAD

**Issue by Petercopter** [pay-rails/pay#769]
```
Rails 7.0.4
Pay 6.3.1
```

I've been using Stripe for awhile. I just setup Pay, and now my Stripe related tests are failing in the CI (Github Actions) only. They don't fail locally.  As soon as I remove Pay it starts working again. Local is MacOS.

I've also tried removing the initializer, and it still doesn't work. It seems like Pay is not handing off the credentials in the CI correctly. Looking at the code, it seems like Stripe should be getting the private key from Pay, but I still can't explain why I'm seeing different results locally.

I thought maybe this line in `environment/test.rb` was related, but nothing yet...
```
  config.eager_load = ENV['CI'].present?
```

```
Failure/Error:
 Stripe::Transfer.create(
   amount:,
   currency:,
   description:,
   destination:,
   transfer_group:
 )
     
Stripe::AuthenticationError:
  No API key provided. Set your API key using "Stripe.api_key = <API-KEY>". You can generate API keys from the Stripe web interface. See https://stripe.com/api for details, or email support@stripe.com if you have any questions.
```

That key is being set in `config/initializers/stripe.rb`

```
Stripe.api_key = Rails.application.credentials.dig(:stripe, :private_key) || 'totally-valid-api-key'
```

**Comment by cjilbert504** [comment]
I think you'll definitely want to drop the initializer, I think that's more of the Stripe gem itself way of doing things and use either Rails credentials or environment variable as mentioned [here](https://github.com/pay-rails/pay/blob/master/docs/2_configuration.md#credentials)

Maybe check the format of the credentials for Stripe in your credentials and that they are set for the proper environment??

They should match:
```yml
stripe:
  private_key: xxxx
  public_key: yyyy
  signing_secret:
  - aaaa
  - bbbb
  ```

I'll see what else I can think of until but hopefully that's some sort of starting point.

**Comment by Petercopter** [comment]
Right, I have the keys setup in the credentials like this as well.

```
stripe:
  public_key: "pk_test_..."
  private_key: "sk_test_..."
```

**Comment by Petercopter** [comment]
WELL this is awkward. It was because I was never decrypting credentials in the CI before.

I had this
```
Stripe.api_key = Rails.application.credentials.dig(:stripe, :private_key) || 'totally-valid-api-key
```
So Stripe was always getting A key, it never mattered if it was correct, because the interactions with Stripe were recorded with VCR.

Sorry for wasting your time, thanks so much for this gem and all the other great things you do for the Rails community! 🎉

**Comment by excid3** [comment]
Doh! I don't think I would have guessed that one but it makes perfect sense. 🤪
