### ISSUE TITLE
NameError: uninitialized constant Pay::Mail after upgrading to 6.3.1

### ISSUE THREAD

**Issue by fidalgo** [pay-rails/pay#770]
During my Ruby 3.2 upgrade took the time to also update all other gems, so pay got updated 
-  pay (6.1.0)
+ pay (6.3.1)

-  receipts (2.1.0)
+ receipts (2.2.0)

If I comment on the line where I set the support email in the pay initializer I get the app to load
`#  config.support_email = "helpme@example.com"`

otherwise, I cannot get zeitwerk to load the app:

```
rails zeitwerk:check 
rails aborted!
NameError: uninitialized constant Pay::Mail
```

**Comment by cjilbert504** [comment]
Hmm, I wasn't able to reproduce this behavior. I spun up a new rails app, added Pay (6.3.1), setup a pay.rb initializer which made the assignment `config.support_email = "helpme@example.com"` and ran the `zeitwerk:check` task which reported everything was ok.

I'm not sure where it's getting the constant name of `Pay::Mail` from though. The only place I can think of is inside of `lib/pay.rb` but I don't know why it would be looking for a constant of that name. 

I'll look into this more and see what I can find out, but if you have any additional insight you can provide it would be appreciated, @fidalgo.

**Comment by excid3** [comment]
Does your Gemfile.lock not have the `mail` gem in it? It's one of the dependencies we expect your app to have installed.

And yeah @cjilbert504, https://github.com/pay-rails/pay/blob/master/lib/pay.rb#L101 could probably be `::Mail::Address` so it's explicitly not looking in the Pay namespace.

**Comment by fidalgo** [comment]
OK the problem was the `mail` gem was not declared on the `Gemfile`, despite being a direct dependency of `actionmailer` at least:
```
21:    actionmailer (7.0.4.2)
26:      mail (~> 2.5, >= 2.5.4)
```

So after adding:
`gem "mail"` to the Gemfile the problem went away.

@excid3 agree that `::Mail::Address`  makes the dependency more explicit, also if we depend on the `mail` gem, we should set it explicitly in the gemspec, I guess.

**Comment by excid3** [comment]
We depend on Rails in the gemspec, which in turn requires https://github.com/pay-rails/pay/blob/master/pay.gemspec#L24

Did you customize application.rb to only require a subset of Rails instead of `require "rails/all"`?

That's the only thing I can think of that would cause your situation.

@cjilbert504 started #771 to explicitly require the top level Mail constant, so that will help some with the error clarity.

I am thinking now that we might want to explicitly `require "action_mailer"` as well to make sure it's loaded.

**Comment by fidalgo** [comment]
Yes, I do not require `rails/all`.

**Comment by excid3** [comment]
That's what I figured. What parts of Rails do you not require other than ActionMailer?

We depend on most of Rails I think:
- ActiveRecord
- ActiveJob
- Routes / Controllers
- ActiveSupport
- ActionMailer

**Comment by fidalgo** [comment]
```
require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
# require "action_mailbox/engine"
require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
require "rails/test_unit/railtie"
```
