### ISSUE TITLE
`payment_processor.processor_id` returning `nil`

### ISSUE THREAD

**Issue by dynelight** [pay-rails/pay#781]
Hello. 

I am using the pay gem to create new stripe customers and create default subscriptions. When we create the stripe customers, we save the stripe ID on our database for when we reference to checkout, we can pass the ID. 

We could not help but notice that all the new checkouts were creating a new customer. So, I digged in and found out our model creation was assigning `nil` to the Stripe ID. 

We found out that the following sentence we returning `nil`: 

```
      stripe_id = self.payment_processor.processor_id

      subscription = self.payment_processor.subscribe(
        plan: self.plan.stripe_id,
        trial_period_days: 14
      )
```

`stripe_id` in this case is `nil`. However, if I did it the other way around: 

```
      subscription = self.payment_processor.subscribe(
        plan: self.plan.stripe_id,
        trial_period_days: 14
      )

      stripe_id = self.payment_processor.processor_id
```

Then the `stripe_id` is being returned. 

Questions: 

- Is this order important? 
- Where exactly is the customer ID being created? Our group declaration does have the following declared: 
`pay_customer default_payment_processor: :stripe`
- Do I need to somehow wait for any of these requests to finish before I get the `stripe_id`? 

Thanks so much!

**Comment by excid3** [comment]
Customers are lazy created, so they are only created when you attempt to checkout. That way if you have a potential

**Comment by dynelight** [comment]
Got it. So from what I understood, it makes total sense for the `stripe_id` to be created after the `subscribe` but not before, right? If that is the case then there was an error on my code. I think we can close after you confirm this. 

Thanks :) @excid3
