### ISSUE TITLE
Devise reconfirmable email address not syncing

### ISSUE THREAD

**Issue by drewscott** [pay-rails/pay#79]
When config.reconfirmable is set to true and after the new email address has been confirmed, the email that is synced with stripe is the previous address and not the most recent changed address.

**Comment by excid3** [comment]
It will use the email address in the `email` field, so if that hasn't been updated, then it will use the old email address.

**Comment by drewscott** [comment]
It seems after the billable class is updated is does a check to see if the email was updated. This would only be true after the user clicks the confirmation email link and the email field is updated to use the devise unconfirmed_email.

So the EmailSyncJob is only performed after the email field has changed. But I can't quite put my finger on what's causing this issue.

**Comment by excid3** [comment]
Devise won't update the `email` field until the new email has been confirmed.

**Comment by drewscott** [comment]
Thats correct, and once that email field is updated the EmailSyncJob is performed

**Comment by excid3** [comment]
Doesn't seem like you want to do that sooner because they haven't confirmed it. You could put in an invalid email in and you don't want to sync that right away.
