### ISSUE TITLE
Could not find generator 'pay:email_views'

### ISSUE THREAD

**Issue by weefunker** [pay-rails/pay#81]
rails generate pay:email_views
Running via Spring preloader in process 16092
Could not find generator 'pay:email_views'. Maybe you meant 'kaminari:views', 'devise:views' or 'erb:mailer'

Seems like migrations ghost run on the gem until another proceeding migration is run. No rows were added to project schema.

Issue happened when using Jumpstart Rails basic

**Comment by excid3** [comment]
Totally missed this issue! `rails g pay:email_views` is working for me, and I don't think we changed anything. Might have been something with spring?
