### ISSUE TITLE
#subscribed? returns false with active subscription

### ISSUE THREAD

**Issue by spencerldixon** [pay-rails/pay#811]
If I use more than one named plan, when calling `.subscribed?` on a user with an active subscription (without specifying which plan), it can return `false`. 

This is because by default, with no args `subscribed?` includes the `Pay.default_product_name` in it's query. This makes it difficult to see at a glance if a user is actively subscribed regardless of plan name.

You could check each plan by name with `subscribed?(plan: "1")`, but I would expect `subscribed?` not to filter by plan name unless explicitly specified in the args.

I'd be happy to do a PR for this if this is ok?

**Comment by excid3** [comment]
It sounds like you're misusing the `name` parameter. This would be used for when a user has multiple separate subscriptions in a single product. Think Twitch where you might subscribe to different streamers.

**Comment by darkporpoise** [comment]
As a workaround `.subscribed?(name: nil)` will return true regardless of which subscription is active. It's not hugely intuitive though

**Comment by spencerldixon** [comment]
Hi Chris! I think you might be right, but here's a bit more context

I've got Stripe set up with four products and when a user subscribes to one via the checkout I'm setting the metadata to save off the plan name in my db with (`{ subscription_data: { metadata: { pay_name: "Plan 1" } } }`) so I can show it back to the user later (you are subscribed to: Plan 1)

The problem here is that I expected `subscribed?` (without any args) to check for any active subscription regardless of name, but it was filling in `default`, effectively doing `subscribed?(name: "default")`, which caused subscribed users to show as unsubscribed for me as I was overriding the default `pay_name`.

Tom's right, you can do `subscribed?(name: nil)` to check all subscriptions, but I would expect this to be the default behaviour when you do `subscribed?` without specfiying a name.

Am I trying to work against Stripe here? Is there a better way?

**Comment by excid3** [comment]
Yeah, you don't want to do that. The `name` is for separate subscriptions entirely. You should probably keep the name as `default` because you want to query against the `processor_plan` column for that.

For example: If you want all the subscriptions on a certain tier, you would query where `processor_plan: ["monthly-plan-1", "annual-plan-1"]`

I think you can pass an array into the `subscribed?(name: "default", plan: ["monthly", "annual"])`, but I can't remember. If not, we should patch it.
