### ISSUE TITLE
Broken SCA confirm page - unpkg.com

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [pay-rails/pay#812]
With pay `6.3.1` SCA confirm page works.

Since pay `6.3.2` we get the following error on the SCA payment confirmation page:

```
caught SyntaxError: The requested module 'https://unpkg.com/@hotwired/stimulus' does not provide an export named 'Application'
```

https://github.com/pay-rails/pay/commit/7b2f8a33d6522b5571ead2f82ac3fb6bdd863da1 commit seems to have caused the problem.

**Comment by excid3** [comment]
Whoopsie. Will take a look.

**Comment by excid3** [comment]
You are correct! I'll get a release cut with that fix shortly.

**Comment by ZilvinasKucinskas** [comment]
I just upgraded to `6.3.4`, tested with a Stripe test clock and it works! 🎉 

Thanks, @excid3.
