### ISSUE TITLE
Could Chris make a demo video on GoRails?

### ISSUE THREAD

**Issue by claeusdev** [pay-rails/pay#82]
i have just stumbled on this... wondering if @excid3 would be kind enough to make a video on how to use it.. Thanks

**Comment by excid3** [comment]
That's the plan! It may take me a little bit, because we need to update this for the new Stripe SCA changes first.

**Comment by claeusdev** [comment]
Oh, wonderful... Can't wait for this...

**Comment by RailsCod3rFuture** [comment]
When you create the demo video, I'm definitely checking it out! I would like to hit the ground running with this gem.

**Comment by excid3** [comment]
I'll try and put something together this week or next now that I've released version 2.0!

**Comment by RailsCod3rFuture** [comment]
Very nice. I'm looking forward to it.

**Comment by eugenedm** [comment]
Any vids guys? Would love to see a few shortcuts... Thank you

**Comment by excid3** [comment]
Got sucked into other things but I have marked time on my calendar to do an introduction tomorrow.

**Comment by eugenedm** [comment]
Thanks a lot! It would be great.. ;)

**Comment by excid3** [comment]
Here's a getting started guide I just recorded: https://www.youtube.com/watch?v=hYlOmqyJIgc

I'll be adding more videos soon.

**Comment by eugenedm** [comment]
This is an unwritten manual in the video... Love it.. Chris! Thank you! :) 
I will through the video and implement it right away.

p.s. Wow, it's Chris himself...I didn't realize it. When I started with Rails I mainly watched your videos and got inspired. You were my first teacher when I started learning Rails.

**Comment by CodingFu** [comment]
Thanks for the video! I'll use this gem on my new project.
