### ISSUE TITLE
Paddle exception, on cancel_now, when deleting user.

### ISSUE THREAD

**Issue by vincentritter** [pay-rails/pay#820]
When a user/pay_customer is deleted from the database, with an active subscription, an exception is thrown here during the `cancel_now!` call:
https://github.com/pay-rails/pay/blob/master/lib/pay/paddle/subscription.rb#LL96C7-L98C11

Exception, thrown by Paddle:
`You don't have permission to access this resource`

For context, I am using Devise, and it's throwing from here:
`Pay::Paddle::Error in Devise::RegistrationsController#destroy`

Even cancelling the subscription beforehand, manually, still causes this issue.

This is happening on a "sandbox" account locally, and cannot confirm, yet, if this happens in production.

Devise does delete the user successfully, but Paddle's subscription still remains active and would have to be deleted/cancelled in the Paddle Dashboard, which isn't ideal.

**Comment by excid3** [comment]
Does your API key not have permission to cancel the subscription for some reason?

**Comment by vincentritter** [comment]
@excid3 – Ah, thank you for pointing me in that direction. Classic case of RTFM.

I mistakingly used the SDK API key instead of the Auth Code... which solves the issue.

For anyone seeing this, the `Auth Code` can be found here:
Live: https://vendors.paddle.com/authentication
Sandbox: https://sandbox-vendors.paddle.com/authentication
