### ISSUE TITLE
Support for Stripe Terminal

### ISSUE THREAD

**Issue by HoganMcDonald** [pay-rails/pay#828]
Love the gem for accepting payments on site, but most of our payments are collected in person with Stripe terminal. The workflow for stripe terminal is slightly different than the normal charge workflow supported by pay.

the TLDR is that you first create a payment_intent without a payment method connected to it, you update the amount on this unpaid payment_intent, then you use the [Terminal SDK](https://stripe.com/docs/terminal/payments/collect-payment) to collect payment method. When you do that, the terminal will display the current total and allow customers to tap/swipe/insert their card. Once they do, a payment method will have been attached to the payment_intent in stripe and it is now completable. 

So my problem is that I need to create a payment_intent without a payment_method and then be able to add that later when I go to capture the payment. Is there a way to accomplish this in the gem currently? if not, is there at least a way to make sure that payment_intents captured outside the flow still get persisted as pay charges that I can associate with my Order record?

Thanks

**Comment by HoganMcDonald** [comment]
Update to this for folks trying to do the same thing I am. I ended up having to create a stripe paymentIntent manually on the server, complete the stripe card terminal checkout flow as they explain it in their docs, then when I want to capture it on the server, I can create a Pay::Charge object this way:

```
# payment intent must be created with a customer id, otherwise Pay::Charge won't be created later.
@payment_intent = Stripe::PaymentIntent.create({
                                                 customer: customer.payment_processor.customer.id,
                                                 amount: amount_owed,
                                                 currency: 'usd',
                                                 payment_method_types: ['card_present'],
                                                 capture_method: 'manual'
                                               })
```

```
# capture payment endpoint 
payment_intent = Stripe::PaymentIntent.capture(params[:payment_intent_id])
@pay_charge = Pay::Stripe::Charge.sync(payment_intent.latest_charge)
```

The end result is a Pay::Charge record that is created synchronously so I can use it in the controller for my api response (instead of waiting for it to be created in a webhook). 

Hope this helps others, but it would still be cool to see the first step handled in a cleaner way in Pay than having to create a payment intent myself.

**Comment by excid3** [comment]
I'm going to add a shortcut for making a payment intent for Stripe customers. That way you can use `@user.payment_processor.create_payment_intent(...)` and we can auto-include the customer ID, set a default for the currency, etc.

Then we can probably also have a `terminal_charge(amount)` method that could set the payment_method_types and/or capture method.

**Comment by HoganMcDonald** [comment]
I was able to test this and it works well. It allows me to delete almost all the rest of our code that deals with stripe directly. I'll be integrating this into our POS system later this month.

Thank you @excid3!
