### ISSUE TITLE
[Pay] stripe gem must be version ~> 8 errors out if stripe version >= 9.0.0

### ISSUE THREAD

**Issue by 800a7b32** [pay-rails/pay#839]
When stripe version is equal to 9.0.0,  app containing pay gem fails to boot.

[`Pay::Engine.version_matches?(required: "> 8", current: ::Stripe::VERSION) || (raise "[Pay] stripe gem must be version ~> 8")`](https://github.com/pay-rails/pay/blob/master/lib/pay/stripe.rb#L40)

**Comment by excid3** [comment]
Major version changes introduce breaking changes so we will not support 9 until it is tested thoroughly.

**Comment by 800a7b32** [comment]
will move this issue to jumpstart-pro as stripe is defaulting to 9.0.0
