### ISSUE TITLE
Error when trying to create standard connect account with business type

### ISSUE THREAD

**Issue by oladejihenry** [pay-rails/pay#852]
i tried doing this in my controller

 `account = @user.merchant_processor.create_account(
            type: 'standard',
            email: current_user.email,
            business_type: 'individual',
            business_profile: {
                url: 'http://lvh.me'
            }
        )`

 but when i try running the code i get this error 

```
You cannot create Standard connected accounts with capabilities via API.
```
 but when i remove the business_type and business_profile i was able to create the standard account for some weird reason. when i checked the log i see this 
` {
  "type": "standard",
  "email": "sample@gmail.com",
  "business_type": "individual",
  "business_profile": "http://lvh.me",
  "capabilities": {
    "card_payments": {
      "requested": "true"
    },
    "transfers": {
      "requested": "true"
    }
  }
}`

as seen above it keeps adding capabilities for some weird reason.

**Comment by oladejihenry** [comment]
Also is it possible that this `@user.set_payment_processor :stripe, stripe_account: "acct_1234"` can be added to the README for connected account/marketplace because i spent almost all day trying to troubleshoot it. #565

**Comment by oladejihenry** [comment]
I was able to solve the first problem by doing this
`
account = Stripe::Account.create({
            type: 'standard',
            email: current_user.email,
            business_type: 'individual'
        })

        @user.pay_merchants.find_or_create_by(
            processor_id: account.id,
            processor: :stripe 
        )
`

> i tried doing this in my controller
> 
> `account = @user.merchant_processor.create_account( type: 'standard', email: current_user.email, business_type: 'individual', business_profile: { url: 'http://lvh.me' } )`
> 
> but when i try running the code i get this error
> 
> ```
> You cannot create Standard connected accounts with capabilities via API.
> ```
> 
> but when i remove the business_type and business_profile i was able to create the standard account for some weird reason. when i checked the log i see this ` { "type": "standard", "email": "sample@gmail.com", "business_type": "individual", "business_profile": "http://lvh.me", "capabilities": { "card_payments": { "requested": "true" }, "transfers": { "requested": "true" } } }`
> 
> as seen above it keeps adding capabilities for some weird reason.

**Comment by excid3** [comment]
Since Stripe doesn't allow that, you'll want to include `capabilities: nil` so that our default values don't get included in the request.
