### ISSUE TITLE
Dependency on rails-html-sanitizer

### ISSUE THREAD

**Issue by shmeltex** [pay-rails/pay#86]
Question: Is there a need to have rails-html-sanitizer as a dependency? Doesn't look like it being used anywhere.
This dependency conflicts with Rails 6.0 dependency on a higher version of rails-html-sanitizer.

**Comment by jasoncharnes** [comment]
@shmeltex yeah, this just bit me too. I don't remember why I added that in there, but the test suite still runs the same when I remove it. 

I updated master to remove the dependency.
