### ISSUE TITLE
Swap plan at end of period instead of immediately

### ISSUE THREAD

**Issue by xfalcon727** [pay-rails/pay#87]
How do I swap an user's subscription plan at end of billing cycle instead of immediately?

current_user.subscription.swap(plan)

This swaps the plan immediately.

**Comment by excid3** [comment]
None of the APIs support this, so you'd have to build it yourself.

The easiest way would be to use a webhook from them and change the plan once the cancellation even comes in.

**Comment by xfalcon727** [comment]
I found this answer on stackoverflow by Garet Claborn works.

[Stripe: downgrade a user at “period end”](https://stackoverflow.com/questions/16820212/stripe-downgrade-a-user-at-period-end)

The code in my rails code is below.

`
processor_id = current_user.subscription.processor_id
subscription = Stripe::Subscription::retrieve(processor_id)

Stripe::Subscription.update(
              processor_id,
              {
                cancel_at_period_end: false,
                items: [
                  {
                    id: subscription.items.data[0].id,
                    plan: plan_id,
                  }
                ],
                prorate: false,
                trial_end: subscription.current_period_end
              }
            )`
