### ISSUE TITLE
Cannot verify signature without a `StripeEvent.signing_secret`

### ISSUE THREAD

**Issue by arielwulkan** [pay-rails/pay#88]
Getting `Cannot verify signature without a 'StripeEvent.signing_secret'`. Even though `signing_secret` is correctly setup on `credentials` file.

**Comment by excid3** [comment]
If you open a rails console and run `Pay::Stripe.signing_secret` what do you get?

**Comment by arielwulkan** [comment]
If I run `Pay::Stripe.signing_secret` I get `nil`. Bit if I run `Rails.application.credentials.stripe[Rails.env.to_sym][:signing_secret]` I do get the correct value.

**Comment by excid3** [comment]
Ah, you've got it flipped. Environment should be first, not second.

```
production:
  stripe:
    signing_secret: x
```

**Comment by arielwulkan** [comment]
That's right Chris! Perfectly working now.
