### ISSUE TITLE
undefined local variable or method `pay_subscription' for Pay::PaddleBilling::Subscription:Class

### ISSUE THREAD

**Issue by dimsonggg** [pay-rails/pay#893]
Hello, thank you for the best gem for paddle :)

I am getting the above exception after cancel now subscription hook from paddle billing dashboard.

.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/paddle_billing/subscription.rb:57:in `sync'

ruby 3.2.2

gem 'rails', '7.1.1'
gem "pay", git: "https://github.com/pay-rails/pay.git", branch: "main"
gem "paddle", "~> 2.1"

**Comment by excid3** [comment]
Please provide a full stacktrace.

**Comment by dimsonggg** [comment]
[ActiveJob] [Pay::Webhooks::ProcessJob] [2e76f3c8-2bea-472d-be15-e9bb35825d5c] Error performing Pay::Webhooks::ProcessJob (Job ID: 2e76f3c8-2bea-472d-be15-e9bb35825d5c) from Async(default) in 269.47ms: NameError (undefined local variable or method `pay_subscription' for Pay::PaddleBilling::Subscription:Class):
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/paddle_billing/subscription.rb:57:in `sync'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/paddle_billing/webhooks/subscription.rb:6:in `call'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/webhooks/delegator.rb:50:in `call'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:133:in `block in finish'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:25:in `block in iterate_guarding_exceptions'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:24:in `each'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:24:in `iterate_guarding_exceptions'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:121:in `each'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:132:in `finish'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:256:in `block in finish_with_values'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:255:in `each'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:255:in `finish_with_values'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/fanout.rb:248:in `finish'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:64:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/webhooks/delegator.rb:35:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/webhooks.rb:7:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/app/models/pay/webhook.rb:8:in `process!'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/pay-6319c09c27c9/lib/pay/webhooks/process_job.rb:5:in `perform'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/execution.rb:69:in `block in _perform_job'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/execution.rb:68:in `_perform_job'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:32:in `_perform_job'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/execution.rb:52:in `perform_now'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.1/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:40:in `block in instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/notifications.rb:206:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:39:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.1/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/instrumentation.rb:26:in `perform_now'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/logging.rb:18:in `block in perform_now'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:39:in `tagged'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/tagged_logging.rb:135:in `tagged'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/broadcast_logger.rb:232:in `method_missing'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/logging.rb:25:in `tag_logger'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/logging.rb:18:in `perform_now'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/execution.rb:30:in `block in execute'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/reloader.rb:77:in `block in wrap'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/execution_wrapper.rb:92:in `wrap'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/reloader.rb:74:in `wrap'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `instance_exec'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/callbacks.rb:141:in `run_callbacks'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/execution.rb:28:in `execute'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activejob-7.1.1/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/Users/dmytrotopor/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'

**Comment by excid3** [comment]
We can just use `object.customer_id` here instead. We don't need the subscription, all we're trying to get is the `customer_id` and we've already got it. 👍

**Comment by excid3** [comment]
@dimsonggg give main a try now. 👍 

Accidentally closed via commit, so reopen if that didn't fix it.
