### ISSUE TITLE
[BUG] DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2.

### ISSUE THREAD

**Issue by wscourge** [pay-rails/pay#913]
## Bug Report

**Describe the Bug:**
I get the following warning:

    ActiveSupport::DeprecationException: DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from <main> at /opt/app/config/environment.rb:5) (ActiveSupport::DeprecationException)
    /usr/local/bundle/gems/pay-6.8.1/lib/pay/env.rb:42:in `secrets'
    /usr/local/bundle/gems/pay-6.8.1/lib/pay/env.rb:25:in `find_value_by_name'
    /usr/local/bundle/gems/pay-6.8.1/lib/pay/stripe.rb:63:in `private_key'
    /usr/local/bundle/gems/pay-6.8.1/lib/pay/stripe.rb:46:in `setup'
    /usr/local/bundle/gems/pay-6.8.1/lib/pay/engine.rb:33:in `block in <class:Engine>'

**To Reproduce:**

1. Use RoR 7.1.2
2. Use pay 6.8.1

**Expected Behavior:**
No warning.

**Actual Behavior:**
Warning

**Screenshots (if applicable):**
 n/a

**Environment:**
- Pay gem version: 6.8.1
- Ruby version: 3.2.2
- Rails version: 7.1.2
- Operating System: macos

**Additional Context:**
 n/a

**Possible Fix:**
self-explanatory

**Steps to Reproduce with Fix (if available):**
 n/a

**Related Issues:**

https://www.reddit.com/r/rails/comments/17cixft/comment/kbo4110/?utm_source=share&utm_medium=web2x&context=3

**Labels to Apply:**
idk

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Already fixed in main. 👍
