### ISSUE TITLE
Can't get emails to send

### ISSUE THREAD

**Issue by xfalcon727** [pay-rails/pay#92]
Emails are not sending. This is my pay.rb in config/initializers

```
Pay.setup do |config|
  config.billable_class = 'User'
  config.billable_table = 'users'

  config.chargeable_class = 'Pay::Charge'
  config.chargeable_table = 'pay_charges'

  # For use in the receipt/refund/renewal mailers
  config.business_name = "Example"
  config.business_address = "1600 Pennsylvania Avenue NW"
  config.application_name = "Example App"
  config.support_email = "contact@example.com"

  config.send_emails = true

  config.automount_webhook_routes = true
  config.webhooks_path = "/webhooks" # Only when automount_webhook_routes is true
end
```
I have Sendgrid on Heroku. Emails are working for other parts of my app like devise confirmable. Is there anything else I need to config like config/environments/production.rb?

**Comment by excid3** [comment]
Do you have your Stripe webhooks configured to send to the app?

**Comment by xfalcon727** [comment]
I don't. Do i need to in order for emails to work?

```
def receipt(user, charge)
      @user, @charge = user, charge

      if charge.respond_to? :receipt
        attachments[charge.filename] = charge.receipt
      end

      mail(
        to: to(user),
        subject: Pay.email_receipt_subject,
      )
    end
```

Also, what is charge in this code for the UserMailer? My users will pay for a subscription and not do single charges. Will a charge be created if they are paying for subscriptions? How do I lookup this charge?

**Comment by excid3** [comment]
Yep, Stripe sends you a webhook when the user is charged, so we use that to send out the receipt emails.

Subscriptions create charges every billing period (month, year etc). This happens in Stripe, so the only way your app can be notified of a charge is with a webhook.

**Comment by excid3** [comment]
Check out the Stripe CLI as well, it'll help you send webhooks to your local environment for testing.

**Comment by xfalcon727** [comment]
Thank you. Where do I put the signing secret to my Stripe webhook? Is it in config/initializers/stripe.rb? Is that where I also configure my Stripe api key to get webhooks set up correctly? Once I get those two set up, will Pay know what to do with the webhooks automatically? If not, what else do I need to do?

I appreciate you and Jason creating this gem. It has been very helpful.

**Comment by excid3** [comment]
You'll drop the signing secret in next to your stripe credentials: https://github.com/pay-rails/pay#stripe

And yeah, Pay should know what to do with the webhooks. It will automatically send out receipt emails for you and handle other webhooks. If you're curious, here are the ones we currently process: https://github.com/pay-rails/pay/blob/master/lib/pay/stripe/webhooks.rb

**Comment by excid3** [comment]
In stripe, you'll have to add the webhook to /webhooks/stripe (unless you customized the url)

**Comment by xfalcon727** [comment]
I wasn't able to download Stripe CLI, but I tested it out locally using ngrok and it works just fine. However, when I try to set it to my Heroku app for production, I keep getting a 404 Error Not Found.

I have `config.webhooks_path = "/webhooks"` in pay.rb and set the endpoint url in Stripe to `https://example.herokuapp.com/webhooks/stripe` and it keeps failing. Am I doing anything wrong? Do you know why it keeps failing?

**Comment by xfalcon727** [comment]
Found out the reason why it wasn't working in production. I added these in my rails credentials:
```
development:
  stripe:
    private_key: xxxx
    public_key: yyyy
    signing_secret: zzzz

production:
  stripe:
    private_key: xxxx
    public_key: yyyy
    signing_secret: zzzz
```
but forgot to remove my old stripe config code in production.rb

**Comment by excid3** [comment]
Ah gotcha! 👍

**Comment by t3t5uo** [comment]
Hi, I am getting an error 500 with my webhooks in heroku. I have the webhook configured in stripe to poing to mysite.heroku.com/pay/webhooks/stripe and the stripe credentials set up in my secrets file for production. 

Is there something else i need to do get pay to work with stripe webhooks in heroku ?
