### ISSUE TITLE
How to create subscription manually with no processor?

### ISSUE THREAD

**Issue by uurcankaya** [pay-rails/pay#93]
Is there a method to set the user as "subscribed" bypassing processors?

Something like:

user.subscribe(name: 'Plan1')

**Comment by excid3** [comment]
Like you want to give a user a free subscription?

You can probably just create a subscription directly with a fake processor:

```ruby
user.subscriptions.create(processor: 'free', processor_id: 'free', processor_plan: 'Plan1')
```

Probably some other required data, but that could work. You also will probably have to update your views so those users can't access the "update card" and upgrade plan functionality.
