### ISSUE TITLE
How to apply discounts to a subscription?

### ISSUE THREAD

**Issue by xfalcon727** [pay-rails/pay#95]
I want to apply a discount to a subscription when a user signs up. How can I do this?

**Comment by excid3** [comment]
You can either pass a coupon as an attribute when you create a new subscription. https://stripe.com/docs/api/subscriptions/create#create_subscription-coupon

Or you can update the Stripe Customer with the coupon.

**Comment by xfalcon727** [comment]
Didn't realize it was that simple to pass a coupon id when subscribing. For anyone else that was wondering, here's the code:

```
user.processor = 'stripe'
user.card_token = token
user.subscribe(plan: plan.id, coupon: 'coupon-id')
```

**Comment by excid3** [comment]
Easy peasy! I tried to make sure it forwards along any options to Stripe like if you called Stripe directly.
