### ISSUE TITLE
How do I add idempotency_key to new subscription?

### ISSUE THREAD

**Issue by xfalcon727** [pay-rails/pay#98]
How do I prevent someone from accidentitly getting charged multiple times?

Can I send an idempotency_key while subscribing the user? I tried the code below, but it only created the customer and didn't subscribe the user.

```
idempotency_key = SecureRandom.hex(6)

user.subscribe(plan: plan.id, idempotency_key: idempotency_key)
```

If this is not how it should be done, what way do you recommend to prevent duplicate charges? Thanks!

**Comment by excid3** [comment]
It looks like Stripe requires it as a second hash of arguments. Probably have to update the gem to accept that, and I'm not sure if Braintree supports idempotency keys, but we should look into that too.

```ruby
charge = Stripe::Charge.create({
  amount: 2000,
  currency: "usd",
  source: "tok_visa", # obtained with Stripe.js
  description: "Charge for jenny.rosen@example.com"
}, {
  idempotency_key: "tGeDzrwzPrBJAPHP"
})
```

**Comment by xfalcon727** [comment]
Yeah I saw it as a second hash in the documents as well. 

Do you implement some work around in your code to prevent duplicate charges using this gem?

**Comment by excid3** [comment]
No, not currently. I'm just issuing one request and not retrying it. Would be a nice addition to support this.

**Comment by xfalcon727** [comment]
Ah i see. I think the user clicked the submit payment button multiple times really fast and it triggered multiple charges. Would this persson be issuing multiple requests when they press the button like this? How would I prevent this from happening again?

**Comment by excid3** [comment]
Yep, and you would need to set the idempotency key if you didn't add Javascript to disable the button as soon as the initial click happened.

**Comment by xfalcon727** [comment]
Got it. Thanks for your help!

**Comment by swistaczek** [comment]
Hey @excid3, I would like to ask if we can open this task? In an application that is based on jumpstart-pro we noticed a problem with multiple subscriptions at the same time. As you can guess, this could be very problematic for subscribers :).
