### ISSUE TITLE
[Feature Request] Ignore test webhook events on live

### ISSUE THREAD

**Issue by donnguyen** [pay-rails/pay#999]
## Bug Report

**Describe the Bug:**

With the fact that for Connect webhooks, both live and test webhooks will be sent to production webhook URLs. This will create lots of unnecessary issues on production. Example: `No such subscription: 'sub_1PNVK7CCbWsu'; a similar object exists in test mode, but a live mode key was used to make this request.`

**Possible Fix:**

Perhaps a configuration to bypass webhook events based on `livemode` attribute? What are you thoughts, Chris?

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
I think you meant to select "Live mode only" when creating your webhook. From Stripe:

> The Events your platform's [Connect Webhook Endpoints](https://stripe.com/docs/connect/webhooks) receive will vary based on the type of connection your platform has to the connected account. There are three configuration options:
> 
> Live mode only: When a connected account is connected only in live mode to your platform, the live Events and test Events are sent to your live Connect Webhook Endpoint.
> 
> Test mode only: When a connected account is connected only in test mode to your platform, the test Events are sent to your test connect Webhook Endpoint. Live Events are never sent.

> Live mode and test mode: When a connected account is connected in live and in test mode to your platform, the live Events are sent to your live connect Webhook Endpoint and the test Events are sent to both the live and the test connect Webhook Endpoints.

https://support.stripe.com/questions/connect-account-webhook-configurations

**Comment by donnguyen** [comment]
Hi @excid3,

I don't think we get to control these behaviours as it states here: `Live mode only: When a connected account is connected only in live mode to your platform, the live Events and test Events are sent to your live Connect Webhook Endpoint.` As in you live webhook endpoint always get tests events from connected account.

We are willing to implement the update, but your input on best approach is much appreciated.

Cheers

**Comment by excid3** [comment]
I glossed over that, interesting. I wonder what the use case of having test events in production is for. I don't quite get that.

Not sure how best to implement that. Something like this is best I can come up with.

```ruby
event = verified_event
queue_event(event) unless Rails.env.production? && !event.livemode
```

But I guess this should be configurable in case someone does want to process test mode events in production?

**Comment by donnguyen** [comment]
@excid3 thanks. I have raised a PR here: https://github.com/pay-rails/pay/pull/1001, can you please take a look? cheers
